### ISSUE TITLE
Some question in train

### ISSUE THREAD

**Issue by xuxiaoxxxx** [mit-han-lab/bevfusion#100]
![image](https://user-images.githubusercontent.com/55653936/184534455-5bef8d7b-f640-42ae-a9bc-d88ee26c72c6.png)
During training I encount this problem, can you help me?
**problem:** python: /opt/conda/conda-bld/magma-cuda113_1619629459349/work/interface_cuda/interface.cpp:901: void magma_queue_create_from_cuda_internal(magma_device_t, cudaStream_t, cublasHandle_t, cusparseHandle_t, magma_queue**, const char*, const char*, int): Assertion `queue->dCarray__ != __null' failed.

**Comment by kentang-mit** [comment]
We will start answering questions related to the errors encountered during training using our schedule after we release the training code.
