### ISSUE TITLE
how to download the map extension

### ISSUE THREAD

**Issue by junwenjiao** [mit-han-lab/bevfusion#102]
when I try `python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes`.I can not find nuscenes_infos_xxx_mono3d.coco.json.And I do not find how to download the map extension.
wish your answer.

**Comment by qfwysw** [comment]
![image](https://user-images.githubusercontent.com/53482524/185023372-5a92d94a-98b1-44de-9f14-19eeab3adc3a.png)
Hi, you can get it in nuscene.

**Comment by junwenjiao** [comment]
just unzip it?but I can not find the right folder structure like  author said.

**Comment by junwenjiao** [comment]
mmdetection3d
├── mmdet3d
├── tools
├── configs
├── data
│   ├── nuscenes
│   │   ├── maps
│   │   ├── samples
│   │   ├── sweeps
│   │   ├── v1.0-test
|   |   ├── v1.0-trainval
This one.

**Comment by junwenjiao** [comment]
I can not find nuscenes_infos_xxx_mono3d.coco.json.And I see the create_data.py but find something about json.

**Comment by kentang-mit** [comment]
The mono3d file is not needed for this project.

**Comment by junwenjiao** [comment]
thanks for your help.Best wish!

**Comment by kentang-mit** [comment]
Great, I will temporarily close this issue because it is resolved. Feel free to reopen if you have further questions.
