### ISSUE TITLE
TimeoutError: [Errno 110] Connection timed out

### ISSUE THREAD

**Issue by junwenjiao** [mit-han-lab/bevfusion#104]
when I try `torchpack dist-run -np 8 python tools/test.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml pretrained/bevfusion-det.pth --eval bbox`.
it shows that :
`Downloading:` "https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_tiny_patch4_window7_224.pth" to `/home/panwb/.cache/torch/hub/checkpoints/swin_tiny_patch4_window7_224.pth`

while `TimeoutError: [Errno 110] Connection timed out
`and`urllib.error.URLError: <urlopen error BEVFusion: <urlopen error [Errno 110] Connection timed out>>'

my envs is ubuntu18.04.these dependencies are builded following ReadME.

wish for your help.

**Comment by kentang-mit** [comment]
It seems to be a problem related to your Internet connection. Perhaps you can try whether it is possible to download this file in your browser (everything is normal on my side). I would say that if you find it hard to access this file on Github, you may remove the initialization config (lines 23-25 [here](https://github.com/mit-han-lab/bevfusion/blob/c53e2283b0ebd00b5adbed8b3de0d39362ad3287/configs/nuscenes/det/transfusion/secfpn/camera%2Blidar/swint_v0p075/default.yaml#L23)) and the evaluation script should still work.

**Comment by junwenjiao** [comment]
thanks for your answer!By following your tip,I run it.But there are some warning like:'UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument.'and ' No pre-trained weights for SwinTransformer, training start from scratch
'

**Comment by kentang-mit** [comment]
I think for the `torch.meshgrid` warning I am also seeing it, so I do not think it is a problem. For weights loading, it should be OK because you will load our pretrained checkpoint.
