### ISSUE TITLE
OptionalCUDAGuard

### ISSUE THREAD

**Issue by FuzhiYang** [mit-han-lab/bevfusion#105]
Hi Haotian,

In the recent commit, "OptionalCUDAGuard" is added in mmdet3d/ops/bev_pool/src/bev_pool.cpp. I just wonder what is the purpose of this module? 
I built the code in the old version (without OptionalCUDAGuard). Will this cause some potential errors? 

Thanks,
Fuzhi

**Comment by kentang-mit** [comment]
Hi Fuzhi,

This will not cause potential errors if you are not debugging the single BEV pooling op. `OptionalCUDAGuard` is related to the discussions in [this issue](https://github.com/mit-han-lab/bevfusion/issues/63). 

Best,
Haotian

**Comment by FuzhiYang** [comment]
Got it. Thank you very much!

**Comment by kentang-mit** [comment]
No problem. I'm closing this issue temporarily because the issue is resolved.
