### ISSUE TITLE
Problem with create data 

### ISSUE THREAD

**Issue by songlilucky** [mit-han-lab/bevfusion#11]
```
File "bevfusion/tools/data_converter/create_gt_database.py", line 275, in create_groundtruth_database
    image_idx = example["sample_idx"]
KeyError: 'sample_idx'
```
 I  find that code Collect3D class in  `/mmdet3d/datasets/pipelines/formating.py` is different from origin code in mmdetection3d . The new code will miss the key `sample_idx`.

A lot of thanks for your kindly reply :)

**Comment by xczhanjun** [comment]
@songlilucky yes, I found the same problem . 
Please add and edit two lines in 
mmdet3d/datasets/nuscenes_dataset.py
def get_data_info(self, index: int) -> Dict[str, Any]:
        info = self.data_infos[index]
        data = dict(
            token=info["token"],
 +++++++++   sample_idx=info['token'],

and 
change this line in the same function:
camera_intrinsics[:3, :3] = camera_info["cam_intrinsics"]
=====> 
camera_intrinsics[:3, :3] = camera_info["camera_intrinsics"]

**Comment by songlilucky** [comment]
> camera_intrinsics

 Thanks! That solves the problem!

**Comment by sborse3** [comment]
@zhijian-liu, @xczhanjun thanks for the great work and this fix. I faced this issue as well, and it fixed my problem
