### ISSUE TITLE
Waymo Performance and Code

### ISSUE THREAD

**Issue by agent-sgs** [mit-han-lab/bevfusion#110]
This is a nice work. Would you release the code and performance evaluation on the Waymo Open Dataset?
I expect your positive response.

**Comment by kentang-mit** [comment]
Yes. We will release some experiment code on Waymo. We are working on code cleanning now.

**Comment by Son-Goku-gpu** [comment]
@kentang-mit Thanks for your open-source code! May I know if you would release both training&evaluation code and pre-trained models in this week?

**Comment by Son-Goku-gpu** [comment]
@kentang-mit I see. I'd like to incoporate your model on Waymo into my framework, would you like to give a rough time for releasing your code? Thanks a lot!

**Comment by kentang-mit** [comment]
@Son-Goku-gpu Glad to here that! we are working hard towards a new release in mid September.

**Comment by kentang-mit** [comment]
Closed due to inactivity.

**Comment by Rtakaha** [comment]
Hi, I am also looking forward to your code for Waymo Open Dataset. It will be great :)

I don't want to rush you, but would you tell me if the code is going to be released soon? Or does it take a little more time?

Thank you very much for your great work!
