### ISSUE TITLE
No such file or directory: ':/usr/local/cuda-11.0:/usr/local/cuda-11.0/bin/nvcc'

### ISSUE THREAD

**Issue by oneway3124** [mit-han-lab/bevfusion#111]
(bevfusion) root@ea6778bb3974: bevfusion# python setup.py develop
running develop
/root/miniconda3/envs/bevfusion/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/root/miniconda3/envs/bevfusion/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing mmdet3d.egg-info/PKG-INFO
writing dependency_links to mmdet3d.egg-info/dependency_links.txt
writing top-level names to mmdet3d.egg-info/top_level.txt
/root/miniconda3/envs/bevfusion/lib/python3.8/site-packages/torch/utils/cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'mmdet3d.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'mmdet3d.egg-info/SOURCES.txt'
running build_ext
error: [Errno 2] No such file or directory: ':/usr/local/cuda-11.0:/usr/local/cuda-11.0/bin/nvcc'
(bevfusion) root@ea6778bb3974:~/bevfusion#

**Comment by oneway3124** [comment]
Hi Sir,

Can you tell me why?

**Comment by oneway3124** [comment]
(base) root@8cd1c5a2b9cd:~# /usr/local/cuda
cuda/      cuda-11.0/

**Comment by oneway3124** [comment]
Yes, I check it.

**Comment by oneway3124** [comment]
![2](https://user-images.githubusercontent.com/3787176/186041195-df6971a3-48bc-4378-adba-4fb24589d8b6.png)

![1](https://user-images.githubusercontent.com/3787176/186041171-51e37aea-f7c1-49f2-9856-e921b740bf80.png)

**Comment by kentang-mit** [comment]
I see. What about pointing the `CUDA_HOME` variable to `/usr/local/cuda/` (or `/usr/local/cuda-11.0`)?

**Comment by oneway3124** [comment]
Thanks. I have tried these debug methods. But it is also not ok.
So I have switched to another GPU server for this environment.
![3](https://user-images.githubusercontent.com/3787176/186097992-e4d15094-365c-4db5-9e11-039893ebf4af.png)

**Comment by oneway3124** [comment]
That is cuda 10.

**Comment by kentang-mit** [comment]
Glad that the problem is resolved on another machine! I'm not sure why CUDA 11.x is not working on your machine since I am also using CUDA 11.x.

**Comment by oneway3124** [comment]
It maybe is a reason that the AI cloud machine from "http://gpu.ai-galaxy.cn/".

**Comment by tiancaipipi110** [comment]
Which server did you switch to ?

**Comment by tiancaipipi110** [comment]
@oneway3124  Which server did you switch to?
