### ISSUE TITLE
Multi camera fusion 

### ISSUE THREAD

**Issue by MayLkn** [mit-han-lab/bevfusion#123]

**Comment by MayLkn** [comment]
I hope to explain the multi-camera fusion, thank you

**Comment by kentang-mit** [comment]
Hi @MayLkn,

Thanks for the interest. I'd suggest you to have a look at those papers in the **Acknowledgements** section of our README document. 

Best,
Haotian

**Comment by VeeranjaneyuluToka** [comment]
Related to this again andd i might use this thread further understanding as well. I was trying to understand camera-to-BEV transformation (am looking into LSS and BEVDet) with implementation, could you point out me where exactly this is?
