### ISSUE TITLE
nvcc fatal : Unsupported gpu architecture 'compute_80'

### ISSUE THREAD

**Issue by usmanraza121** [mit-han-lab/bevfusion#127]
after running "**python setup.py develop"** I faced the above error.

**error: command '/usr/local/cuda/bin/nvcc' failed with exit code 1**

currently, I have installed Cuda-10.2. however, if run the above command with Cuda-11.7 or 9.2 it gives an error and suggests installing Cuda-10.2. 
can it only be compiled with Cuda-10.2? no other Cuda-version?

Thank you

**Comment by MayLkn** [comment]
> 

Cuda11.1 can also，

**Comment by kentang-mit** [comment]
Hello folks,

Would you mind sharing the GPUs you are using? The reason why you meet with this error is that `compute_80` and `sm_80` is too new for your nvcc compiler. You can simply remove the corresponding line in setup.py.

Best,
Haotian

**Comment by usmanraza121** [comment]
@kentang-mit  Thank you for your prompt response. I'm using GTX TITAN X GPU (12GB).

**Comment by usmanraza121** [comment]
> > 
> 
> Cuda11.1 can also，

Thank you

**Comment by kentang-mit** [comment]
Hi @usmanraza121,

In this case, you can replace that line with `compute_61` and `sm_61`.

Best,
Haotian

**Comment by kentang-mit** [comment]
Closed due to inactivity.
