### ISSUE TITLE
How to show the inference result?

### ISSUE THREAD

**Issue by regular-time** [mit-han-lab/bevfusion#130]
I run the test with:`torchpack dist-run -np 1 python tools/test.py configs/nuscenes/det/centerhead/lssfpn/camera/256x704/swint/default.yaml pretrained/camera-only-det.pth --show --show-dir ./results`, but it didn't work.

**Comment by kentang-mit** [comment]
Hello @regular-time,

lease refer to https://github.com/mit-han-lab/bevfusion/issues/59 for the visualization command. You might need to adjust the box-score threshold.

Best,
Haotian

**Comment by regular-time** [comment]
OK, thanks! @kentang-mit
