### ISSUE TITLE
Understanding the implementation with the paper

### ISSUE THREAD

**Issue by VeeranjaneyuluToka** [mit-han-lab/bevfusion#135]
Hi,

I have been looking into Camera-to-BEV transformation, I am looking into the paper and implementation simulteniously (including LSS and BEVDet). Not really spot the point where the implementation is for this in this repo. 

Wanted to use this thread to understand further implementation as well, so would request you to open for some time till i complete understanding the code and the paper :). Thanks.

**Comment by kentang-mit** [comment]
Hi @VeeranjaneyuluToka,

You can trace the functions in [this file](https://github.com/mit-han-lab/bevfusion/blob/main/mmdet3d/models/vtransforms/lss.py) to understand the implementation.

Best,
Haotian

**Comment by kentang-mit** [comment]
Closed due to inactivity.
