### ISSUE TITLE
how about output bboxes (x,y,z,w,h,l,yaw,b,v)?

### ISSUE THREAD

**Issue by Ehangiun** [mit-han-lab/bevfusion#138]
did i think right?
output has 9 results ,but i don't know the last three numbers mean
thanks

**Comment by kentang-mit** [comment]
Hello @Ehangiun, yaw means the heading angle of the bounding box, v means the velocity (2-dimensional). I did not remember whether we have `b` in the final result, but if there is such a dimensional this might be the batch index (used in batch size > 1 evaluation).

**Comment by kentang-mit** [comment]
Closed due to inactivity.
