### ISSUE TITLE
How to split the dataset into only Sunny/Rainy/Day/Night scene?

### ISSUE THREAD

**Issue by RoyZry98** [mit-han-lab/bevfusion#139]
I notice that you conduct experiments with only Sunny/Rainy/Day/Night scenes in your work. I want to know how you split the dataset into those 4 scenes. Thanks a lot!

**Comment by ssuralcmu** [comment]
It might be possible to use the description information in the list_scenes function in nuscenes-devkit to get keywords such as night and rain to classify the scenes. Here is a useful Colab tutorial for the same- https://colab.research.google.com/github/nutonomy/nuscenes-devkit/blob/master/python-sdk/tutorials/nuscenes_tutorial.ipynb

**Comment by kentang-mit** [comment]
Thanks @ssuralcmu. These experiments are done by @Hanyuezhuohua, perhaps he can provide more insights.

**Comment by Hanyuezhuohua** [comment]
As @ssuralcmu mentions, we manually split these scenes following the scene description in nuscenes dataset(the path is data/nuscenes/v1.0-trainval/scene.json). The Rainy/Night scenes are explicitly given in the "descripton". After that, it is easy to find the Sunny/Rainy/Day/Night val scenes in its original split: [](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/splits.py#L102). Hope it will be helpful to you！

**Comment by kentang-mit** [comment]
Temporarily closed due to inactivity.
