### ISSUE TITLE
Training details

### ISSUE THREAD

**Issue by sborse3** [mit-han-lab/bevfusion#15]
Hi! Could you share the training command for the baseline model (without BEVFusion) to get started? Thanks

**Comment by kentang-mit** [comment]
Hi @sborse3,

We will provide the training details in future release after we finish more experiments on GPUs with smaller memory. For the baselines, I recommend you to have a look at the official schedule of TransFusion-L and BEVDet. 

Best,
Haotian

**Comment by linyanAI** [comment]
Can I ask if there is a schedule for training code?
