### ISSUE TITLE
Training details of bevfusion-det: one stage or two stage training method?

### ISSUE THREAD

**Issue by HatakeKiki** [mit-han-lab/bevfusion#151]
Thank you for your release of the training details. But lidar-only and camera-only details are released not fusion model. I wonder the fusion model uses one stage training for 20 epochs using the configs provided or I need to reproduce lidar-only model first and fine-tuning on this one? One stage training may be tricky with object sample part.

**Comment by kentang-mit** [comment]
We use two-stage training.
