### ISSUE TITLE
Ablation Studies

### ISSUE THREAD

**Issue by Sukbin-Lim** [mit-han-lab/bevfusion#152]
First, Thank you for your great work!

Do you have a plan to open ablation studies?
I want to use BEVFusion with ResNet50 as an image backbone. 

In addition, Do you have any results using Pointpillars instead of VoxelNet?

**Comment by kentang-mit** [comment]
BEVFusion with ResNet50 will also work, and it's performance is around ~68mAP on nuScenes val. We can release it in the future after some code cleanning.

PointPillars support is also on our roadmap. We haven't tried out it yet now.
