### ISSUE TITLE
running on pycharm

### ISSUE THREAD

**Issue by zhenghw111** [mit-han-lab/bevfusion#164]
How do I launch the script using torchpack if I want to run it on pycharm？
![image](https://user-images.githubusercontent.com/108120679/193978824-b2bd5323-bc60-4842-8693-69bade0dbec3.png)

**Comment by kentang-mit** [comment]
Sorry I have never used PyCharm before. One workaround will be using the IDE to edit the code and launch training/testing jobs in the terminal. Hope that will help.

**Comment by kentang-mit** [comment]
No problem. I'll close this issue since it is resolved.
