### ISSUE TITLE
Missing lr_config in config file

### ISSUE THREAD

**Issue by Capchenxi** [mit-han-lab/bevfusion#17]
Hello Haotian, 
I got an error "'ConfigDict' object has no attribute 'lr_config'" when trying to train the bevfusion model with configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml. I think the lr_config is not set in the yaml file. Do I missing anything here?
Thank.

**Comment by kentang-mit** [comment]
Hi @Capchenxi,

Thanks for your interest! We are planning to release the training schedule in the future, please stay tuned! 

Best,
Haotian
