### ISSUE TITLE
Question about tracking

### ISSUE THREAD

**Issue by whoakang** [mit-han-lab/bevfusion#171]
Thanks for your amazing job! have a question that how to use centerpoint to achieve 3D box tracking？

**Comment by kentang-mit** [comment]
I think we used the tracker from Tianwei's CenterPoint [implementation](https://github.com/tianweiy/CenterPoint/tree/master/tools/nusc_tracking) and fed in our detection predictions.

**Comment by whoakang** [comment]
Thanks for your reply！
i test detection model used this command：torchpack dist-run -np 8 python tools/test.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml pretrained/bevfusion-det.pth --eval=bbox

should i change yaml file to this：configs/nuscenes/det/centerhead/lssfpn/camera/256x704/swint/default.yaml, to achieve tracking?

**Comment by kentang-mit** [comment]
You can just save the predictions from our detector and feed it to a separate tracker module from Tianwei. I think that will be the easiest way to use BEVFusion as a tracking baseline.

**Comment by whoakang** [comment]
ok，i’will try this way，thanks.

**Comment by kentang-mit** [comment]
Great. I'll close this issue since it is resolved.
