### ISSUE TITLE
Odd evaluation results

### ISSUE THREAD

**Issue by yangxh11** [mit-han-lab/bevfusion#175]
I get mAP=0.630 and NDS=0.685 when using
`torchpack dist-run -np 2 python tools/test.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml pretrained/bevfusion-det.pth --eval bbox`

But get  mAP=0.647 and NDS=0.692 when using
`torchpack dist-run -np 2 python tools/test.py configs/nuscenes/det/transfusion/secfpn/lidar/voxelnet_0p075.yaml pretrained/lidar-only-det.pth --eval bbox`

The code and pretrained weights are downloaded from offical. Why the lidar-only model has better performance than the camera+lidar model?

**Comment by kentang-mit** [comment]
Please make sure you used the latest code and checkpoint. We updated the input preprocessing pipeline recently. Loading old checkpoint / loading new checkpoint with the old codebase will not give you the correct results.
