### ISSUE TITLE
About the init_cfg.checkpoint of the backbone

### ISSUE THREAD

**Issue by sunnyHelen** [mit-han-lab/bevfusion#176]
Hi, thanks a lot for sharing the great work. I notice a good pre-trained model for Camere backbone is helpful to get a better effect.
How did you get the pre-trained model "swint-nuimages-pretrained.pth"? And what the data volume?
Thanks a lot~

**Comment by kentang-mit** [comment]
The Swin-T model is pretrained on nuImages 2D object detection task following the convention of almost all camera-LiDAR fusion papers (that uses nuScenes). You can refer to [official mmdet3d repo](https://github.com/open-mmlab/mmdetection3d/tree/master/configs/nuimages) for details of model training on nuImages.

**Comment by sunnyHelen** [comment]
Ok, got it. Many thanks.

**Comment by sunnyHelen** [comment]
Hi, I checked the official mmdet3d repo. It seems that there's no training configs of the training of swinT. Can you release the  pretraining configs of it? Or how can I find the proper way to train a swinT model on nuImages 2D object detection task?

**Comment by kentang-mit** [comment]
Sorry I don't have the bandwidth to check whether my previous experiment config can work with the latest codebase, so the release plan will be delayed. However, I think it should be quite easy to get started from the mmdetection3d codebase. I remember that they provided some example for ResNet101-based detectors. You may just change the image backbone to SwinT.

**Comment by sunnyHelen** [comment]
Yes, they provide different settings. And I'm confused about whether you pretrained on COCO and which model you used for the 2D detection task. Could you give me a suggestion to find the same setting as yours~
<img width="435" alt="image" src="https://user-images.githubusercontent.com/28101548/196368818-03c56b5e-23fb-4458-83dc-cea619c948d5.png">

**Comment by sunnyHelen** [comment]
That's helpful. Thanks a lot.
