### ISSUE TITLE
How to specify  The graphics card number during  multi-gps  training？

### ISSUE THREAD

**Issue by liwuhen** [mit-han-lab/bevfusion#182]

**Comment by kentang-mit** [comment]
Hi @liwuhen,

To change the number of GPUs you can simply change the `-np` argument in the `torchpack` command. E.g.:

```bash
torchpack dist-run -np 4 ...
```

means that you want to use 4 GPUs.

Best,
Haotian

**Comment by liwuhen** [comment]
thank you!

But, for example,  I want to use some graphics   eg: 1, 4, 7 graphics card
What are the startup commands ？

**Comment by kentang-mit** [comment]
You're welcome. For your use case, please just try out
```bash
CUDA_VISIBLE_DEVICES=1,4,7 torchpack dist-run -np 3 ...
```

**Comment by kentang-mit** [comment]
Closed due to inactivity.
