### ISSUE TITLE
Velocity GT question

### ISSUE THREAD

**Issue by meghanagao** [mit-han-lab/bevfusion#183]
https://github.com/mit-han-lab/bevfusion/blob/0e5b9edbc135bf297f6e3323249f7165b232c925/tools/data_converter/nuscenes_converter.py#L265

// convert velo from global to lidar
for i in range(len(boxes)):
                velo = np.array([*velocity[i], 0.0])
                velo = velo @ np.linalg.inv(e2g_r_mat).T @ np.linalg.inv(l2e_r_mat).T
                velocity[i] = velo[:2]

This code in nuscenes_converter.py that the velocities from box_velocity(). After that, this piece of code seems to convert it from global to lidar. What is the reasoning behind this conversion?

**Comment by meghanagao** [comment]
Got it, so the annotations used for training are in the LiDAR-centric coordinate system and then converted to global coordinate system after inference. Is that correct?

**Comment by kentang-mit** [comment]
Yes.

**Comment by kentang-mit** [comment]
Closed due to inactivity.
