### ISSUE TITLE
about batch_size

### ISSUE THREAD

**Issue by zhenghw111** [mit-han-lab/bevfusion#186]
Hi, where can I change the batch_size?

**Comment by VeeranjaneyuluToka** [comment]
I think it is **samples_per_gpu**. You can find in one the configs files based on the training model you are using (Camera or lidar or lidar+camera).

**Comment by kentang-mit** [comment]
Yes. @VeeranjaneyuluToka is correct. You can override:

```yaml
data:
  samples_per_gpu: [desired number]
```
