### ISSUE TITLE
How to train fusion model?

### ISSUE THREAD

**Issue by Wolfwjs** [mit-han-lab/bevfusion#189]
Thanks for your nice work.

When I use this command to train a fusion model, how to load the lidar weights trained in the first stage?
`torchpack dist-run -np 8 python tools/train.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml`

**Comment by kentang-mit** [comment]
You can use the `--load-from` flag.
