### ISSUE TITLE
The model used in the code seems to contradict with the paper 

### ISSUE THREAD

**Issue by testpku** [mit-han-lab/bevfusion#191]
Thx for sharing this great work!
In the paper, it said that centerpoint is used as the detector head. However in the code, center point only contains the camera folder, not like transfusion which contains camera+lidar folder. Do you only use transfusion for multi-modal data?

**Comment by kentang-mit** [comment]
We also used CenterHead for multi-modal fusion on the Waymo dataset. The results are available on the official leaderboard, but we haven't publicly released the code.
