### ISSUE TITLE
this is boring issue,sorry

### ISSUE THREAD

**Issue by lloveapple** [mit-han-lab/bevfusion#197]
Why didn't I see the publications published

**Comment by kentang-mit** [comment]
Thanks for your interest. The paper was not accepted to a previous venue despite receiving an unanimous acceptance recommendation from all reviewers. We will keep polishing it and improve the open source quality such that this work can further benefit the community.

**Comment by lloveapple** [comment]
thank you, come on

**Comment by CarlHuangNuc** [comment]
bad news......

**Comment by kentang-mit** [comment]
Closed due to inactivity.
