### ISSUE TITLE
Box score tuning

### ISSUE THREAD

**Issue by carlinds** [mit-han-lab/bevfusion#199]
Hi! 

How should one interpret (and tune) the box-score parameter used in the visualization? 
I understand it does not directly map to confidence, but it's used similarly I guess.

**Comment by kentang-mit** [comment]
This is used to suppress duplicate predictions. I guess NMS with threshold 0 will also work. Generally we adjust this value such that the visual quality of our demo looks best.

**Comment by kentang-mit** [comment]
Closed due to inactivity.
