### ISSUE TITLE
About the inference time

### ISSUE THREAD

**Issue by zyl1336110861** [mit-han-lab/bevfusion#2]
@zhijian-liu Thank you very much for your sharing! I am reading your paper recentely. I see that your optimized model can run about 100ms per frame. So I am curious about what is the efficiency bottleneck now. Is it the Swin-T process?

**Comment by kentang-mit** [comment]
Hello @zyl1336110861, thanks for your interest in our work! The efficiency bottleneck is the LiDAR backbone, which is a SparseConvNet. Previously we also study the optimization of SparseConv in the system-level and hardware-level. You are welcomed to check out our recent papers [TorchSparse](https://torchsparse.mit.edu) and [PointAcc](https://pointacc.mit.edu).

**Comment by zyl1336110861** [comment]
@kentang-mit Ok! I will refer to these papers! Thank you very much!

**Comment by kentang-mit** [comment]
You are welcome.

**Comment by zyl1336110861** [comment]
@kentang-mit Hi, please see here [,](https://github.com/traveller59/spconv/issues/383) is that true? It says that [spconv2.x](https://github.com/traveller59/spconv) is greatly faster than torchsparse.

**Comment by zyl1336110861** [comment]
@kentang-mit Hi, please see [here](https://github.com/traveller59/spconv/issues/383 ) , is that true? It says that [spconv2.x](https://github.com/traveller59/spconv) is greatly faster than torchsparse.
