### ISSUE TITLE
problem with debugging on pycharm

### ISSUE THREAD

**Issue by Z-chocking** [mit-han-lab/bevfusion#200]
I wanted to debug the project on pycharm and removed the `dist.init()`  function in reference to[ what others had done](https://github.com/mit-han-lab/bevfusion/issues/143)。
Then I run it in pycharm debug mode:
`tools/train.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml --run-dir nbev_result/`
But this is an error：
![image](https://user-images.githubusercontent.com/92561600/197489359-15c0b12a-f245-4b9e-803c-961d94be52de.png)
What should I do？It seems that I didn't initialize the distribution

**Comment by kentang-mit** [comment]
Sorry but I'm not an expert in Pycharm. Would you mind having a look at this issue: https://github.com/mit-han-lab/bevfusion/issues/172 to see whether it is possible to replace torchpack.distributed with torch.distributed? This might be helpful. If it won't work, I would suggest you to use the IDE to edit the code and debugging using command line tools.

**Comment by Z-chocking** [comment]
Thanks for your reply.I have solved this problem by modifying some code in this work
