### ISSUE TITLE
Is spconv used in BEVFusion?

### ISSUE THREAD

**Issue by Birdylx** [mit-han-lab/bevfusion#201]
hi, thanks for your excellent work, I have a question about lidar branch.
As paper said, you use voxelnet to extract lidar feature, the original voxelnet doesn't use spconv, I want to know spconv is used in bevfusion implementation

Best,
Birdy.

**Comment by VeeranjaneyuluToka** [comment]
I also wanted to get the reference of SparseEncoder that we are using as a backbone in LiDAR branch.

**Comment by zhijian-liu** [comment]
Yes, we have used `spconv` in the current implementation of BEVFusion. It's the same implementation as MMDetection3D.

**Comment by Birdylx** [comment]
@zhijian-liu Thanks for your reply.
