### ISSUE TITLE
question about training process

### ISSUE THREAD

**Issue by hualuojingye** [mit-han-lab/bevfusion#203]
Hello,thanks for your contribution in fusion. I'm a freshmen in this area.Recently I'm doing some related work.I have a question about the training process.
Do lidar branch and image branch train together or separately?Looking forward to hearing from you.

**Comment by VeeranjaneyuluToka** [comment]
LiDAR barch and Image branch are parallel till the feature extraction stage, then fuse the features and then it is a single pipeline from there. So i think we can say that training happens togather in case of LiDAR and Camera fusion. However would also interested to know if there is a intitutive explanation. Thanks!

**Comment by zhijian-liu** [comment]
We first pre-train the LiDAR branch and then fine-tune both branches together.

**Comment by kentang-mit** [comment]
Closed due to inactivity.
