### ISSUE TITLE
evaluation encounters mpirun: not found

### ISSUE THREAD

**Issue by luoyuchenmlcv** [mit-han-lab/bevfusion#21]
Dear Haotian, 
Thanks for your great work!

I am trying to evaluate the detection model on a single GPU machine by running the following in terminal:

**torchpack dist-run -np 1 python tools/test.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml pretrained/bevfusion-det.pth --eval bbox**

it gives me 

**/bin/sh: 1: mpirun: not found**

when I am running

 **torchpack dist-run -np**

it gives me 

**torchpack dist-run: error: argument -np/--nproc: expected one argument**

when I am running

 **torchpack dist-run -np 1**

it gives me 

**/bin/sh: 1: mpirun: not found**

I am not sure what could be the problem, could that be due to the single GPU machine, or something else?

A lot of thanks for your kindly reply :)

**Comment by luoyuchenmlcv** [comment]
Thanks a lot Haotian, the mpirun not found issue is solved, however after successfully installing mpich and mpi4py, running the evaluation command gives another error:

**[mpiexec@container-c6d211be3c-365c285e] match_arg (utils/args/args.c:159): unrecognized argument allow-run-as-root
[mpiexec@container-c6d211be3c-365c285e] HYDU_parse_array (utils/args/args.c:174): argument matching returned error
[mpiexec@container-c6d211be3c-365c285e] parse_args (ui/mpich/utils.c:1597): error parsing input array
[mpiexec@container-c6d211be3c-365c285e] HYD_uii_mpx_get_parameters (ui/mpich/utils.c:1649): unable to parse user arguments
[mpiexec@container-c6d211be3c-365c285e] main (ui/mpich/mpiexec.c:149): error parsing parameters**

And mpirun version looks like this:
![image](https://user-images.githubusercontent.com/102636806/173489793-cf8e8868-667e-48ec-8c42-8e936a1f24bf.png)

**Comment by kentang-mit** [comment]
I remember that I met with similar problem before with openmpi=3.x, and I just checked our machine, it has openmpi =4.1.1. My mpi4py version is 3.0.3. I'm not sure whether upgrading openmpi to 4.x will help solve this issue. Maybe @zhijian-liu can provide more insights if that does not work.

**Comment by kentang-mit** [comment]
Is it possible not to run `torchpack` in the root mode or in a container?

**Comment by songlilucky** [comment]
Install openmpi not mpich can solve the problem

**Comment by songlilucky** [comment]
if your machine do not have `openmpi`,  you can also use other dist-run method to solve this problem

> Install openmpi not mpich can solve the problem

**Comment by kentang-mit** [comment]
Thanks for the comment @songlilucky!

**Comment by luoyuchenmlcv** [comment]
> if your machine do not have `openmpi`, you can also use other dist-run method to solve this problem
> 
> > Install openmpi not mpich can solve the problem

Thanks for your suggestion, openmpi-3.1.3 has already been installed, the error seems somewhere else.

**Comment by luoyuchenmlcv** [comment]
> Is it possible not to run `torchpack` in the root mode or in a container?

When I only run python*, it gives me error like this, but I suspect this might be due to not running torchpack?
![image](https://user-images.githubusercontent.com/102636806/173991733-805eac2d-5e4a-41bc-bb56-24c5f3eca780.png)

**Comment by kentang-mit** [comment]
Hi @luoyuchenmlcv, I mean you should still use torchpack to launch the script, but instead of running in a docker and as a root user, I would recommend you to run in the normal mode, and not as a root user. Hope that is clear enough.

**Comment by luoyuchenmlcv** [comment]
> Hi @luoyuchenmlcv, I mean you should still use torchpack to launch the script, but instead of running in a docker and as a root user, I would recommend you to run the script directly in the host mode, and not as a root user. Hope that is clear enough.

Thanks for your suggestion, now I am only able to run code in cloud service, I add a new user to linux system to run as the host mode seems difficult, I have to install python, conda env and everything else. 

I guess the problem might be torchpack, is there any standard test to see if torchpack can work?

**Comment by luoyuchenmlcv** [comment]
Hello Haotian,
Finally solved.
The issue is that in the virtual machine there's an empty env variable name that affects mpirun parsing. So sorry for taking your time to address such a stupid problem.

**Comment by PeisongCheng** [comment]
@luoyuchenmlcv I have the same problem. Could you tell me how to solve this? Thanks a lot!

**Comment by luoyuchenmlcv** [comment]
> @luoyuchenmlcv I have the same problem. Could you tell me how to solve this? Thanks a lot!

What exactly is your issue?

**Comment by PeisongCheng** [comment]
![image](https://user-images.githubusercontent.com/48945941/174063861-0f4838c5-b17b-4d24-8e61-e68388cb0c97.png)

**Comment by PeisongCheng** [comment]
@luoyuchenmlcv this is my issue.

**Comment by luoyuchenmlcv** [comment]
> @luoyuchenmlcv this is my issue.
I guess you are using mpich instead of openmpi

please follow this link to download openmpi:
https://sites.google.com/site/rangsiman1993/comp-env/program-install/install-openmpi

after finishing installation of openmpi, 

sudo ldconfig

then

pip install mpi4py

then try running eval command to see if problem solved.

**Comment by kentang-mit** [comment]
> Hello Haotian, Finally solved. The issue is that in the virtual machine there's an empty env variable name that affects mpirun parsing.
> 
> After finishing the evaluation, the detection results are as follows, seem little bit lower than the test result: ![image](https://user-images.githubusercontent.com/102636806/174053668-9b0a2295-eafe-4194-9b23-d974840450a0.png)
> 
> ![image](https://user-images.githubusercontent.com/102636806/174055960-4870b736-b52a-4137-b05c-a751e125682e.png)
> 
> The eval log: [RTX A5000 24GB.txt](https://github.com/mit-han-lab/bevfusion/files/8918350/RTX.A5000.24GB.txt)
> 
> My env ![image](https://user-images.githubusercontent.com/102636806/174059762-50e01b43-3394-4687-8169-736d65e03d17.png)

Hi @luoyuchenmlcv, your evaluation results are actually a bit higher than what I get on the validation set (68.39 mAP and 71.32 NDS). The reported results in your screenshot are on the **test** split.

**Comment by kentang-mit** [comment]
> ![image](https://user-images.githubusercontent.com/48945941/174063861-0f4838c5-b17b-4d24-8e61-e68388cb0c97.png)

I would suggest that you follow the advice of @luoyuchenmlcv to install openmpi 4.1.1 and mpi4py 3.0.3. After that you can try out the same command again.

**Comment by PeisongCheng** [comment]
@luoyuchenmlcv @kentang-mit Thanks a lot!

**Comment by kentang-mit** [comment]
You are welcome @PeisongCheng. I'll leave this issue open for discussions on MPI.

**Comment by Trent-tangtao** [comment]
> 
Hi,
I have the same problem. Could you tell me how to solve this? Thanks a lot!
![image](https://user-images.githubusercontent.com/49675059/174424669-e92cb91b-850b-4f19-9d0b-cca58ac61edd.png)

**Comment by Trent-tangtao** [comment]
> > Is it possible not to run `torchpack` in the root mode or in a container?
> > I run the following code in the root folder:
> > root@container-c6d211be3c-365c285e:/# python /root/autodl-tmp/bevfusion/tools/test.py /root/autodl-tmp/bevfusion/configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml pretrained/bevfusion-det.pth --eval bbox
> 
> it gives me error like this, but I suspect this might be due to not running torchpack? ![image](https://user-images.githubusercontent.com/102636806/173992026-badca714-fa6c-4b72-b526-471f7736e562.png)
> 
> but mpirun seems working when running a hello_c.c file under root: ![image](https://user-images.githubusercontent.com/102636806/173993917-9c5240db-9caf-4c04-bec1-f58c6a23281c.png)

Hi,
I have the same problem. Could you tell me how to solve this? Thanks a lot!
![image](https://user-images.githubusercontent.com/49675059/174424713-e1fb479d-b92a-4680-80ed-4de745ae243c.png)

**Comment by luoyuchenmlcv** [comment]
> > > Is it possible not to run `torchpack` in the root mode or in a container?
> > > I run the following code in the root folder:
> > > root@container-c6d211be3c-365c285e:/# python /root/autodl-tmp/bevfusion/tools/test.py /root/autodl-tmp/bevfusion/configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml pretrained/bevfusion-det.pth --eval bbox
> > 
> > 
> > it gives me error like this, but I suspect this might be due to not running torchpack? ![image](https://user-images.githubusercontent.com/102636806/173992026-badca714-fa6c-4b72-b526-471f7736e562.png)
> > but mpirun seems working when running a hello_c.c file under root: ![image](https://user-images.githubusercontent.com/102636806/173993917-9c5240db-9caf-4c04-bec1-f58c6a23281c.png)
> 
> Hi, I have the same problem. Could you tell me how to solve this? Thanks a lot! ![image](https://user-images.githubusercontent.com/49675059/174424713-e1fb479d-b92a-4680-80ed-4de745ae243c.png)

Hi, this KeyError is due to not running torchpack, if read the torchpack [source code ](https://github.com/zhijian-liu/torchpack/blob/master/torchpack/launch/launchers/drunner.py), MASTER_HOST system env variable is added, so you must run torchpack

**Comment by kentang-mit** [comment]
Hi @Trent-tangtao, I believe @luoyuchenmlcv is correct, you will need to launch the script using  torchpack.

**Comment by hongjiacheng1014** [comment]
Hi @luoyuchenmlcv @kentang-mit, I have a problem about where to place the data which generated by the 'create_data.py' file.
When the data in the directory of mmdet3d, I tried to test.
![image](https://user-images.githubusercontent.com/103634663/176397811-9d6b9a76-73cc-4a8d-bf90-b149ab89ff41.png)
I occurred this error.
![image](https://user-images.githubusercontent.com/103634663/176397898-9f3c75a4-3665-448f-bb22-f87f86455fa9.png)
So I change the directory of data. I placed the data in the directory of bevfusion.
![image](https://user-images.githubusercontent.com/103634663/176397811-9d6b9a76-73cc-4a8d-bf90-b149ab89ff41.png)
I occurred this error.
![image](https://user-images.githubusercontent.com/103634663/176399338-9629f893-b901-4e54-b2ae-234440d40b99.png)

**Comment by Trent-tangtao** [comment]
> Hi @luoyuchenmlcv @kentang-mit, I have a problem about where to place the data which are generated by the 'create_data.py' file. When the data in the directory of mmdet3d, I tried to test. ![image](https://user-images.githubusercontent.com/103634663/176397811-9d6b9a76-73cc-4a8d-bf90-b149ab89ff41.png) I occurred this error. ![image](https://user-images.githubusercontent.com/103634663/176397898-9f3c75a4-3665-448f-bb22-f87f86455fa9.png) So I change the directory of data. I placed the data in the directory of bevfusion. ![image](https://user-images.githubusercontent.com/103634663/176397811-9d6b9a76-73cc-4a8d-bf90-b149ab89ff41.png) I occurred this error. ![image](https://user-images.githubusercontent.com/103634663/176399338-9629f893-b901-4e54-b2ae-234440d40b99.png)

I think you maybe just placed the data and **the previous pkl files** in the directory of bevfusion.  You need regenerated new pkl files.

**Comment by hongjiacheng1014** [comment]
> > Hi @luoyuchenmlcv @kentang-mit, I have a problem about where to place the data which are generated by the 'create_data.py' file. When the data in the directory of mmdet3d, I tried to test. ![image](https://user-images.githubusercontent.com/103634663/176397811-9d6b9a76-73cc-4a8d-bf90-b149ab89ff41.png) I occurred this error. ![image](https://user-images.githubusercontent.com/103634663/176397898-9f3c75a4-3665-448f-bb22-f87f86455fa9.png) So I change the directory of data. I placed the data in the directory of bevfusion. ![image](https://user-images.githubusercontent.com/103634663/176397811-9d6b9a76-73cc-4a8d-bf90-b149ab89ff41.png) I occurred this error. ![image](https://user-images.githubusercontent.com/103634663/176399338-9629f893-b901-4e54-b2ae-234440d40b99.png)
> 
> I think you maybe just placed the data and **the previous pkl files** in the directory of bevfusion. You need to regenerate new pkl files or try "ln -s ".

Thanks @Trent-tangtao I will try this solution.

**Comment by IAMShashankk** [comment]
Hi @kentang-mit 
I am facing the same issue "there are not enough slots....".
My env:
I am running the command on the cluster using slurm.
When I specify the command as `torchpack dist-run -np 1 python tools/test.py` and use only one GPU on cluster it works fine.
But when I want to utilize more gpus i.e 2 or more: `torchpack dist-run -np 4 python tools/test.py` by allocating 4 GPUs using slurm command it results in the same error.

As it is working with 1 GPU, I think there is no problem with mpi or openmp (also I am on the cluster).
Could you please help me with how can I utilize more GPUs to speed up the process?

**Comment by kentang-mit** [comment]
Hi @IAMShashankk,

Would you mind having a look at [this issue](https://github.com/zhijian-liu/torchpack/issues/17)? 

Best,
Haotian

**Comment by CCFQ** [comment]
Hi @kentang-mit 

I have install MPI4py but the problem is still unresolved
![image](https://user-images.githubusercontent.com/100028360/179655962-cae7a7be-40c1-421a-82fe-c0c97900c07f.png)

**Comment by kentang-mit** [comment]
Hi @CCFQ,

Are you using OpenMPI?

Best,
Haotian

**Comment by CCFQ** [comment]
yes install openMPI！

**Comment by CCFQ** [comment]
Hi @kentang-mit 
yes, I do

**Comment by miaochunle** [comment]
> Hello Haotian, Finally solved. The issue is that in the virtual machine there's an empty env variable name that affects mpirun parsing.
> 
> After finishing the evaluation, the detection results are as follows, seem little bit lower than the test result: ![image](https://user-images.githubusercontent.com/102636806/174053668-9b0a2295-eafe-4194-9b23-d974840450a0.png)
> 
> ![image](https://user-images.githubusercontent.com/102636806/174055960-4870b736-b52a-4137-b05c-a751e125682e.png)
> 
> The eval log: [RTX A5000 24GB.txt](https://github.com/mit-han-lab/bevfusion/files/8918350/RTX.A5000.24GB.txt)
> 
> My env ![image](https://user-images.githubusercontent.com/102636806/174059762-50e01b43-3394-4687-8169-736d65e03d17.png)

Wow, you are really great. I really want to know how you train. I'm grateful for a hint

**Comment by kentang-mit** [comment]
Hello @miaochunle,

We will be releasing all training details in the future. Currently I do not have too much bandwidth to clean up the training code. Please stay tuned, thank you!

Best,
Haotian

**Comment by leavesullic** [comment]
Hello there,
I got this cuda error when running `torchpack dist-run -np 8 python tools/test.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml pretrained/bevfusion-det.pth --eval bbox`
![cuda](https://user-images.githubusercontent.com/43094873/186656670-1dd3702b-9dcf-4d98-949d-76d443b2aa18.png)
I don't know why because the evaluation for lidar is totally correct.For example, when I run `torchpack dist-run -np 8 python tools/test.py configs/nuscenes/det/transfusion/secfpn/lidar/voxelnet.yaml pretrained/lidar-only-det.pth --eval bbox`, everything is OK.
Thanks for your help.

yours
tonghui

**Comment by kentang-mit** [comment]
Hi @leavesullic,

Sorry for the late reply. I don't think your question is quite related to the mpirun. Therefore, if the issue still exists, I would recommend you to start a new issue and discuss the problem. It looks like OOM to me, so you can look at the solution [here](https://github.com/mit-han-lab/bevfusion/issues/26) to reduce the memory consumption. 

Best,
Haotian

**Comment by Son-Goku-gpu** [comment]
Hi @leavesullic, I met the same issue ("cuda execution failed with error 2") as you mentioned above, did you resolve it?

**Comment by CCFQ** [comment]
yes .install OpenMPI



---- Replied Message ----
| From | Haotian (Ken) ***@***.***> |
| Date | 07/19/2022 19:44 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [mit-han-lab/bevfusion] evaluation encounters mpirun: not found (Issue #21) |

Hi @CCFQ,

Are you using OpenMPI?

Best,
Haotian

**Comment by lda1049187465** [comment]
> When I am running inside the project folder the error exists: ![image](https://user-images.githubusercontent.com/102636806/173845046-08f15f93-3f25-487e-a31f-63e578b1abce.png)
> 
> When I give them absolute path: ![image](https://user-images.githubusercontent.com/102636806/173845425-ce631a68-3f0f-4154-bfdb-71397ed8a812.png)

Hello, I have the same problem as you when using the autodl cloud server:

Warning: could not find environment variable "-x"

--------------------------------------------------------------------------

mpirun was unable to find the specified executable file, and therefore

did not launch the job. This error was first reported for process

rank 0; it may have occurred for other processes as well.



NOTE: A common cause for this error is misspelling a mpirun command

line parameter option (remember that mpirun interprets the first

unrecognized command line token as the executable).



Node: autodl-container-a2b311863c-21379295

Executable: AutoDLContainerUUID

How did you solve it in the end?

**Comment by lda1049187465** [comment]
> When I am running inside the project folder the error exists: ![image](https://user-images.githubusercontent.com/102636806/173845046-08f15f93-3f25-487e-a31f-63e578b1abce.png)
> 
> When I give them absolute path: ![image](https://user-images.githubusercontent.com/102636806/173845425-ce631a68-3f0f-4154-bfdb-71397ed8a812.png)

Hello, I have the same problem as you when using the autodl cloud server:

Warning: could not find environment variable "-x"

--------------------------------------------------------------------------

mpirun was unable to find the specified executable file, and therefore

did not launch the job. This error was first reported for process

rank 0; it may have occurred for other processes as well.



NOTE: A common cause for this error is misspelling a mpirun command

line parameter option (remember that mpirun interprets the first

unrecognized command line token as the executable).



Node: autodl-container-a2b311863c-21379295

Executable: AutoDLContainerUUID

How did you solve it in the end?

**Comment by catziyan** [comment]
> > When I am running inside the project folder the error exists: ![image](https://user-images.githubusercontent.com/102636806/173845046-08f15f93-3f25-487e-a31f-63e578b1abce.png)
> > When I give them absolute path: ![image](https://user-images.githubusercontent.com/102636806/173845425-ce631a68-3f0f-4154-bfdb-71397ed8a812.png)
> 
> Hello, I have the same problem as you when using the autodl cloud server:
> 
> Warning: could not find environment variable "-x"
> 
> mpirun was unable to find the specified executable file, and therefore
> 
> did not launch the job. This error was first reported for process
> 
> rank 0; it may have occurred for other processes as well.
> 
> NOTE: A common cause for this error is misspelling a mpirun command
> 
> line parameter option (remember that mpirun interprets the first
> 
> unrecognized command line token as the executable).
> 
> Node: autodl-container-a2b311863c-21379295
> 
> Executable: AutoDLContainerUUID
> 
> How did you solve it in the end?

I have the same problem, could you tell me how did you solve it ? thanks

**Comment by keep901** [comment]
> Hello Haotian, Finally solved. The issue is that in the virtual machine there's an empty env variable name that affects mpirun parsing.
> 
> After finishing the evaluation, the detection results are as follows, seem little bit lower than the test result: ![image](https://user-images.githubusercontent.com/102636806/174053668-9b0a2295-eafe-4194-9b23-d974840450a0.png)
> 
> ![image](https://user-images.githubusercontent.com/102636806/174055960-4870b736-b52a-4137-b05c-a751e125682e.png)
> 
> The eval log: [RTX A5000 24GB.txt](https://github.com/mit-han-lab/bevfusion/files/8918350/RTX.A5000.24GB.txt)
> 
> My env ![image](https://user-images.githubusercontent.com/102636806/174059762-50e01b43-3394-4687-8169-736d65e03d17.png)

hi,i have same problem with you,and i have install openmpi4.1.1 and mpi4py3.0.3,can you help me how you solve it? This is very important for me. In the meantime, can you give me your contact information? For ease of communication
![1707291117602](https://github.com/mit-han-lab/bevfusion/assets/56377836/51795287-244c-47b1-bf47-3c08950b58a0)

**Comment by Jaywxy** [comment]
> > Hi @luoyuchenmlcv, I mean you should still use torchpack to launch the script, but instead of running in a docker and as a root user, I would recommend you to run the script directly in the host mode, and not as a root user. Hope that is clear enough.
> 
> Thanks for your suggestion, now I am only able to run code in cloud service, I add a new user to linux system to run as the host mode seems difficult, I have to install python, conda env and everything else.
> 
> I guess the problem might be torchpack, is there any standard test to see if torchpack can work?
> 
> In addition, when running the evaluation cmd, there's a suspicous warning: **Warning: could not find environment variable "-x"** where does this come from?


hello,I get the same error **Warning: could not find environment variable "-x"**, could you please tell me how to deal with it ? thank u very much!

**Comment by Jaywxy** [comment]
> solve

hi,bro,have solve this problem?

**Comment by Jaywxy** [comment]
> For ease of communication

我也是在autodl平台上，好像就是平台问题，但是上面那个老哥好像有正常解决了，不知道他是怎么解决的

**Comment by keep901** [comment]
兄弟，我后面好像也没有解决，放弃了...sry



张林
***@***.***







                       
Original Email
                       
                     

From:"Jaywxy"< ***@***.*** &gt;;

Sent Time:2024/6/22 18:02

To:"mit-han-lab/bevfusion"< ***@***.*** &gt;;

Cc recipient:"keep901"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

Subject:Re: [mit-han-lab/bevfusion] evaluation encounters mpirun: not found(Issue #21)




  
For ease of communication
  
我也是在autodl平台上，好像就是平台问题，但是上面那个老哥好像有正常解决了，不知道他是怎么解决的

**Comment by Jaywxy** [comment]
> 兄弟，我后面好像也没有解决，放弃了...sry 张林 ***@***.*** Original Email From:"Jaywxy"< ***@***.*** &gt;; Sent Time:2024/6/22 18:02 To:"mit-han-lab/bevfusion"< ***@***.*** &gt;; Cc recipient:"keep901"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;; Subject:Re: [mit-han-lab/bevfusion] evaluation encounters mpirun: not found(Issue #21) For ease of communication 我也是在autodl平台上，好像就是平台问题，但是上面那个老哥好像有正常解决了，不知道他是怎么解决的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

谢谢回复，请问后面你是换平台了还是改代码的呀？能给点建议吗？

**Comment by keep901** [comment]
我的建议是不在云服务器上跑，试一下WSL



张林
***@***.***







                       
Original Email
                       
                     

From:"Jaywxy"< ***@***.*** &gt;;

Sent Time:2024/6/22 23:03

To:"mit-han-lab/bevfusion"< ***@***.*** &gt;;

Cc recipient:"keep901"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

Subject:Re: [mit-han-lab/bevfusion] evaluation encounters mpirun: not found(Issue #21)




  
兄弟，我后面好像也没有解决，放弃了...sry 张林 @.*** Original Email From:"Jaywxy"< @.*** &gt;; Sent Time:2024/6/22 18:02 To:"mit-han-lab/bevfusion"< @.*** &gt;; Cc recipient:"keep901"< @.*** &gt;;"Comment"< @.*** &gt;; Subject:Re: [mit-han-lab/bevfusion] evaluation encounters mpirun: not found(Issue #21) For ease of communication 我也是在autodl平台上，好像就是平台问题，但是上面那个老哥好像有正常解决了，不知道他是怎么解决的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
谢谢回复，请问后面你是换平台了还是改代码的呀？能给点建议吗？

**Comment by Jaywxy** [comment]
> 我的建议是不在云服务器上跑，试一下WSL 张林 ***@***.*** Original Email From:"Jaywxy"< ***@***.*** &gt;; Sent Time:2024/6/22 23:03 To:"mit-han-lab/bevfusion"< ***@***.*** &gt;; Cc recipient:"keep901"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;; Subject:Re: [mit-han-lab/bevfusion] evaluation encounters mpirun: not found(Issue #21) 兄弟，我后面好像也没有解决，放弃了...sry 张林 @.*** Original Email From:"Jaywxy"< @.*** &gt;; Sent Time:2024/6/22 18:02 To:"mit-han-lab/bevfusion"< @.*** &gt;; Cc recipient:"keep901"< @.*** &gt;;"Comment"< @.*** &gt;; Subject:Re: [mit-han-lab/bevfusion] evaluation encounters mpirun: not found(Issue #21) For ease of communication 我也是在autodl平台上，好像就是平台问题，但是上面那个老哥好像有正常解决了，不知道他是怎么解决的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 谢谢回复，请问后面你是换平台了还是改代码的呀？能给点建议吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

我昨天解决了这个问题，应该是autodl平台上jupyterlab的问题，使用code远程是能正常多卡训练的。

**Comment by TimDing-aoi** [comment]
> Thanks a lot Haotian, the mpirun not found issue is solved, however after successfully installing mpich and mpi4py, running the evaluation command gives another error:
> 
> **[mpiexec@container-c6d211be3c-365c285e] match_arg (utils/args/args.c:159): unrecognized argument allow-run-as-root [mpiexec@container-c6d211be3c-365c285e] HYDU_parse_array (utils/args/args.c:174): argument matching returned error [mpiexec@container-c6d211be3c-365c285e] parse_args (ui/mpich/utils.c:1597): error parsing input array [mpiexec@container-c6d211be3c-365c285e] HYD_uii_mpx_get_parameters (ui/mpich/utils.c:1649): unable to parse user arguments [mpiexec@container-c6d211be3c-365c285e] main (ui/mpich/mpiexec.c:149): error parsing parameters**
> 
> And mpirun version looks like this: ![image](https://user-images.githubusercontent.com/102636806/173489793-cf8e8868-667e-48ec-8c42-8e936a1f24bf.png)

Hello, have you managed to solve this issue? I am getting the same error
