### ISSUE TITLE
decoder layer

### ISSUE THREAD

**Issue by gubei1998** [mit-han-lab/bevfusion#213]
What's the use of the decoder in configs/secfpn/default.yaml.I can't find them in your paper.

**Comment by gubei1998** [comment]
Thank you very much for your answer,and I want to ask a question about transfusion,Is it useful as a detection head at the end? And it doesn't seem to be used when fusing two modal features?

**Comment by kentang-mit** [comment]
Yes, it is just used as a detection head. Our fusion module is in fact agnostic to the choice of detection head and it also works with the CenterPoint-based head (for example, on Waymo).

**Comment by kentang-mit** [comment]
Closed due to inactivity.
