### ISSUE TITLE
Meaning of the 'img_aug_matrix'and 'lidar_aug_matrix' 

### ISSUE THREAD

**Issue by zhenghw111** [mit-han-lab/bevfusion#218]
Hi, thanks for opening access the nice work!
What is the meaning of the 'img_aug_matrix' and 'lidar_aug_matrix' ?

**Comment by kentang-mit** [comment]
Hi @zhenghw111,

`img_aug_matrix` means the transformation matrix applied to the camera inputs including rotation, flipping and translation. Each can be represented as a 3x3 matrix (changing x, y coordinates of the pixels and keep the z coordinates unchanged).  Similarly `lidar_aug_matrix` records the transformations applied to the point cloud input. 

Best,
Haotian

**Comment by zhenghw111** [comment]
Thanks really! Does `img_aug_matrix` mean the camera extrinsics matrix of the camera?

**Comment by kentang-mit** [comment]
`camera2lidar` is the extrinsics you are looking for. `img_aug_matrix` happens in the pixel coordinate system.

**Comment by kentang-mit** [comment]
Closed due to inactivity.
