### ISSUE TITLE
Details about the Data Augmentation

### ISSUE THREAD

**Issue by Trent-tangtao** [mit-han-lab/bevfusion#22]
Hi,
Thanks for your excellent work! 
Table4e shows that augmentations on both image and lidar inputs are helpful. Can you share the details of these data augmentations and how they align at the bev level?

**Comment by kentang-mit** [comment]
Hi @Trent-tangtao,

Thank you for your interest! The implementation of all data augmentations has already been released in this repo. By the way, we are going to include more details along side with the training code release in the future.

Best,
Haotian
