### ISSUE TITLE
Unbalanced memory usage in multi-card training

### ISSUE THREAD

**Issue by sunnyHelen** [mit-han-lab/bevfusion#221]
When training in multiple GPU cards, it seems that the memory usage is always unbalanced. The highest usage of the 0th card causes my batch size can only reach 2. Do you know how to solve this problem?
<img width="375" alt="image" src="https://user-images.githubusercontent.com/28101548/200024648-183f3761-d771-4cc2-9e52-bfef12097ea5.png">

**Comment by kentang-mit** [comment]
Hi @sunnyHelen,

I didn't observe such unbalanced memory consumption. I remember that 40G is just enough to run batch=4 on our machine for the current version of this codebase. Maybe you can try turning off `cudnn.benchmark` and see if the memory consumption will go down.

Best,
Haotian

**Comment by kentang-mit** [comment]
Closed due to inactivity.
