### ISSUE TITLE
How to read the existing weight file like mmdet3d and continue training after interruption?

### ISSUE THREAD

**Issue by vehicle-jyw** [mit-han-lab/bevfusion#223]
Hello, thank you for your execllent job!
i have a question, i just read this repo and i did not find how to continue training after interruption.

**Comment by kentang-mit** [comment]
Hi @vehicle-jyw,

You may use the `resume_from` flag in the training script.

Best,
Haotian

**Comment by vehicle-jyw** [comment]
I didn't see “--resume_from”“ in the training script which is in the mmdet3d‘s training script.
Is it in the torchpack?

thank you!

**Comment by kentang-mit** [comment]
No it's not part of torchpack. I believe mmcv or mmdet might have implemented this as part of `cfg`. Basically if `cfg.resume_from` is set, the checkpoint resume process will be triggered.

**Comment by kentang-mit** [comment]
Closed due to inactivity.
