### ISSUE TITLE
Oversampling of training dataset

### ISSUE THREAD

**Issue by zlenyk** [mit-han-lab/bevfusion#225]
Hi! Running the training from your configs it looks to me that effective dataset size is ~5x larger than original nuscenes. Are you using some oversampling that is causing this?
I was running 8GPUs with batch size of 2 and I was running 7.7k training steps per epoch, which suggests 7700*16 = 123k training images. I believe that nuscenes train set has ~28k annotated scenes.

Thank you.

**Comment by kentang-mit** [comment]
This is due to the fact that we used CBGS, a standard approach people will use to solve the class imbalance problem on nuScenes. Check out [this paper](https://arxiv.org/abs/1908.09492) for more details.

**Comment by zlenyk** [comment]
Thank you!
