### ISSUE TITLE
About the training of fusion model

### ISSUE THREAD

**Issue by zhenghw111** [mit-han-lab/bevfusion#232]
Hello, after I have trained the Lidar-Only model, how can I add it to the fusion model for training?

**Comment by kentang-mit** [comment]
You could load the pretrained model using the `--load_from` flag. Schedule of the fusion model hasn't been released (will be released by the end of this month).

**Comment by kentang-mit** [comment]
Closed due to inactivity. (By the way, the schedules of the fusion models have been released)
