### ISSUE TITLE
Inference on the nuscenes test split

### ISSUE THREAD

**Issue by dsx0511** [mit-han-lab/bevfusion#233]
Hi Haotian @kentang-mit,

the inference on the nuscenes test set is working from my side (refers to [this issue](https://github.com/mit-han-lab/bevfusion/issues/219)) by running the script `tools/test.py --format-only`. But I want to make sure that I did that correctly:

- I changed line 289  in the file `configs/nuscenes/default.yaml` to `ann_file: ${dataset_root + "nuscenes_infos_test.pkl"}` which allows the dataset loads the info pkl file of the test split
- I changed line 277 of `mmdet3d/datasets/nuscenes_dataset.py` to `annos=None`
- I commented out lines 207-211 in the file `configs/nuscenes/default.yaml` that loads annotations (`LoadAnnotations3D`) in the test pipeline
- I commented out lines 247-259 in the file `configs/nuscenes/default.yaml` that includes the keys of gt data in `Collect3D`

By applying these modifications, is it able to produce the results with the same performance on the nuscenes leaderboard? Or do I need some other changes?

Best,
Shuxiao

**Comment by dsx0511** [comment]
Hi Haotian, thank you very much for your fast response!

**Comment by mayson-128** [comment]
@dsx0511 I was testing out what you had mentioned. Getting the below error.
@kentang-mit 

`Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/bevfusion/mmdet3d/datasets/nuscenes_dataset.py", line 143, in __init__
    super().__init__(
  File "/bevfusion/mmdet3d/datasets/custom_3d.py", line 69, in __init__
    self.pipeline = Compose(pipeline)
  File "/opt/conda/lib/python3.8/site-packages/mmdet/datasets/pipelines/compose.py", line 28, in __init__
    raise TypeError('transform must be callable or a dict')
TypeError: transform must be callable or a dict

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test.py", line 230, in <module>
    main()
  File "tools/test.py", line 169, in main
    dataset = build_dataset(cfg.data.test)
  File "/bevfusion/mmdet3d/datasets/builder.py", line 42, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: NuScenesDataset: transform must be callable or a dict
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[38028,1],0]
  Exit code:    1
--------------------------------------------------------------------------`

**Comment by dikubab** [comment]
For the recent version, I think configs/nuscenes/default.yaml lines 250-259 should not be commented out. It works for me with this exception.

**Comment by fdy61** [comment]
> Hi Haotian @kentang-mit,
> 
> the inference on the nuscenes test set is working from my side (refers to [this issue](https://github.com/mit-han-lab/bevfusion/issues/219)) by running the script `tools/test.py --format-only`. But I want to make sure that I did that correctly:
> 
> * I changed line 289  in the file `configs/nuscenes/default.yaml` to `ann_file: ${dataset_root + "nuscenes_infos_test.pkl"}` which allows the dataset loads the info pkl file of the test split
> * I changed line 277 of `mmdet3d/datasets/nuscenes_dataset.py` to `annos=None`
> * I commented out lines 207-211 in the file `configs/nuscenes/default.yaml` that loads annotations (`LoadAnnotations3D`) in the test pipeline
> * I commented out lines 247-259 in the file `configs/nuscenes/default.yaml` that includes the keys of gt data in `Collect3D`
> 
> By applying these modifications, is it able to produce the results with the same performance on the nuscenes leaderboard? Or do I need some other changes?
> 
> Best, Shuxiao

**Comment by fdy61** [comment]
Sorry,it seemes the content in configs/nuscenes/default.yaml and mmdet3d/datasets/nuscenes_dataset.py has been changed.You said changed line 277 of mmdet3d/datasets/nuscenes_dataset.py to annos=None,but the line 277 now is completely unrelated content
![image](https://github.com/mit-han-lab/bevfusion/assets/134828384/750111c5-d8c2-4f45-bfdb-893ddd893c5d)
