### ISSUE TITLE
Error during tesing

### ISSUE THREAD

**Issue by JiSuanJiDaWang** [mit-han-lab/bevfusion#236]
Hi, I follow the instruction to set up the environment and encountered the following error running command  `torchpack dist-run -np 1 python tools/test.py configs/nuscenes/seg/fusion-bev256d2-lss.yaml pretrained/bevfusion-seg.pth --eval map`
![img_v2_1359bdd7-e7ee-4133-b023-95a671cefd7g](https://user-images.githubusercontent.com/82489384/202630544-177d8870-2127-4702-8478-c1da1304b66c.png)

**Comment by kentang-mit** [comment]
Please consider changing your PyTorch version to 1.10.x and try again.

**Comment by JiSuanJiDaWang** [comment]
Thanks
