### ISSUE TITLE
Assertion error during testing

### ISSUE THREAD

**Issue by JiSuanJiDaWang** [mit-han-lab/bevfusion#238]
Hi, I ran 'torchpack dist-run -np 1 python tools/test.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/default.yaml pretrained/bevfusion-det.pth --eval bbox' and encountered the following error. Can you give me some advice on how to solve it? Thanks.
<img width="633" alt="image" src="https://user-images.githubusercontent.com/82489384/202893341-b6d1e862-54d9-4b34-8878-8491b7368a58.png">

**Comment by kentang-mit** [comment]
Hi @JiSuanJiDaWang,

The config you used is not correct. You can have a try using `configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml`. 

Best,
Haotian

**Comment by JiSuanJiDaWang** [comment]
Thanks! It works now
