### ISSUE TITLE
Error while training the fusion model

### ISSUE THREAD

**Issue by oliver0922** [mit-han-lab/bevfusion#241]
Hi, Thanks for your wonderful work!
I am trying to train the bevfusion model and the command was below.

`torchpack dist-run -np 4 python tools/train.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml
`
However the error occured like this
![Screenshot from 2022-11-24 01-38-57](https://user-images.githubusercontent.com/69920975/203600982-58b0080d-2285-4a27-925a-51f4e38825d8.png)

How can I solve this error?

**Comment by VeeranjaneyuluToka** [comment]
Would you mind mentioning your gpu card details here? I suspect it is due to insufficient GPU memory.

**Comment by oliver0922** [comment]
@VeeranjaneyuluToka 
Thanks for your reply but I don't think that the problem is related to GPU memory.
I used 4 RTX 3090 GPUs.

**Comment by kentang-mit** [comment]
Sorry I missed the issue @oliver0922. It could be the GPU memory issue. Our fusion model is expected to consume >24G GPU memory. You might need to reduce the batch size (`data.samples_per_gpu`).

**Comment by kentang-mit** [comment]
Closed due to inactivity.
