### ISSUE TITLE
Question about a data augmentation

### ISSUE THREAD

**Issue by xxxxhh** [mit-han-lab/bevfusion#244]
Hi, I would like to make a check of whether the GridMask augmentation is used to random mask the grids in the image plane or not. By the way, have you studies the influence of this data augmentation> Thanks!

**Comment by kentang-mit** [comment]
GridMask is not used in any of the results reported in our arXiv version. However, I remember that it works for some cases (e.g. sparse LiDAR + camera).

**Comment by xxxxhh** [comment]
Got that，thanks! So，if I would like to reproduce the results on ArXiv，I should set the ratio parameters in the GridMask as 0 in the configs. Do I understand your points right?



---Original---
From: "Haotian (Ken) ***@***.***&gt;
Date: Sat, Nov 26, 2022 03:46 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [mit-han-lab/bevfusion] Question about a data augmentation (Issue#244)




 
GridMask is not used in any of the results reported in our arXiv version. However, I remember that it works for some cases (e.g. sparse LiDAR + camera).

**Comment by kentang-mit** [comment]
Yes, you are correct.

**Comment by liyih** [comment]
@xxxxhh ，hi, I am wondering have you done the experiment. Whether GridMask will improve the performance of BEVFusion or Not.
Best.
