### ISSUE TITLE
log validation loss

### ISSUE THREAD

**Issue by RG2806** [mit-han-lab/bevfusion#245]
Hey,
      I want to log validation loss as well during validation. What should i change for that?

**Comment by kentang-mit** [comment]
We did not integrate it to the evaluator, but you could try printing them out / logging them [here](https://github.com/mit-han-lab/bevfusion/blob/da751a2c9fa7d436f4ba22427ded5782f3b9a50e/mmdet3d/models/heads/bbox/transfusion.py#L588).

**Comment by RG2806** [comment]
Thanks for the info
