### ISSUE TITLE
recentering box in visualization

### ISSUE THREAD

**Issue by RG2806** [mit-han-lab/bevfusion#247]
Hey,
Thanks for opensourcing this work.
Can you help me understand the reason why you do this?
https://github.com/mit-han-lab/bevfusion/blob/main/tools/visualize.py#L118

thanks

**Comment by kentang-mit** [comment]
I think we did that to make sure the 2D box projections look correct (otherwise there will be some offset on the vertical direction).

**Comment by RG2806** [comment]
Thanks for the info.
