### ISSUE TITLE
The programs will be stuck when training the lidar-only model

### ISSUE THREAD

**Issue by ChongjianGE** [mit-han-lab/bevfusion#249]
Hi, 

Thanks for the wonderful project. I encounter some problems when training the lidar-only model. 
Specifically, the program will be stuck randomly during the training process. When the programs are stuck, some of the GPU-Util will be 0%, while others are 100%, which is shown in the following picture. I have tried to reduce the batchsize (since I guess there might be some OOM errors), but it would not solve the problems. 

Are there any suggestions that you could provide?

Best
<img width="1708" alt="image" src="https://user-images.githubusercontent.com/26426324/204466785-3e854f59-4bfe-45e8-b43c-0c5065da7c49.png">

**Comment by LeongVan** [comment]
I have the same question with you when training LiDAR-only model. I was stop here: 
![1129-2](https://user-images.githubusercontent.com/53937566/204480098-f3e455c8-f029-4b26-8b4f-da8c66b27d37.png)
I used 3 GPUs. When stucking, 2 of them are 100% used and the last one is 0%.

**Comment by sihaoevery** [comment]
Hi everyone,

Just encountered the same issue when training the lidar-only detection.
I use a cluster and submit the job by slurm.  I have 4 A100, 48 CPU cores, and 64G memory. Both the workers_per_gpu and samples_per_gpu are set to 8. The printed log says it will take ~40h. 

Everything seems to be smooth before it comes to epoch 8.  One GPU utility is 0% while others are 100%. Then I tried to resume the model from epoch 7 and it just stuck again in epoch 8.  Nothing is suggested in both the slurm output or error log.

Now I try to train the lidar-camera detection to see if this problem still persists.

Any suggestion would be appreciated.

Thanks in advance

**Comment by LeongVan** [comment]
My problem solved just simply re-run the program...Seems strange, but it works. I've tried many times until it works.

**Comment by sihaoevery** [comment]
> 

Thanks for this information.

Can you provide more information? By 're-run', do you mean train from scratch or resume the model? And what's the setting of batch size and workers for dataloader?

Many thanks.

**Comment by LeongVan** [comment]
> > 
> 
> Thanks for this information.
> 
> Can you provide more information? By 're-run', do you mean train from scratch or resume the model? And what's the setting of batch size and workers for dataloader?
> 
> Many thanks.

I trained from scratch because I was stuck at only epoch 1. I didn't change batch size and workers, so they are default. I checked out that workers is 4 and I can't found the batch size parameter. I'll appreciate if you could guide me where the batch size is set. 
I ran my program on 3 Tesla A100 with 80GB each of them. And the usage of them when training were close to 100% all the training time.

**Comment by LiewFeng** [comment]
I get stuck during the training of lidar only model, too. @zhijian-liu ,could you kindly give any suggestions? Lots of thanks.

**Comment by LiewFeng** [comment]
I use 8 A100 and prepare the enviroment as the readme suggests and don't modify any hyper-parameters. I tried twice but get stuck in the same position.
![image](https://user-images.githubusercontent.com/42316773/229677170-50b4d040-f7e7-4214-a5bf-2cbf879a89b8.png)

**Comment by VeeranjaneyuluToka** [comment]
Are you trying with custom dataset or Nuscenes dataset, i have trying with custom dataset, and ended with the error mentioned in the below issue. https://github.com/mit-han-lab/bevfusion/issues/382, anybody faced this issue and fixed? Thanks!

**Comment by pianogGG** [comment]
I got the same issue， everything seems to be smooth before it comes to epoch 5. One GPU utility is 0% while others are 100%. Good idea? thanks a lot.

**Comment by Ricardolyg** [comment]
change the batch_size in bevfusion/configs/nuscenes/default.yaml
samper per_gpu : 1
worker per_gpu : 1
