### ISSUE TITLE
the problem of training

### ISSUE THREAD

**Issue by yzjalien** [mit-han-lab/bevfusion#251]
first, run:
torchpack dist-run -np 1 python tools/train.py configs/nuscenes/det/transfusion/secfpn/lidar/voxelnet_0p075.yaml
then ,the errors are as follows:
![image](https://user-images.githubusercontent.com/110878028/204698146-4f963c33-5614-4909-ba16-3086cfffb206.png)
here is the cuda information:
![image](https://user-images.githubusercontent.com/110878028/204698314-6ea86f32-e32e-4f5d-9937-07c0b12f5b7d.png)
is  GPU memory not enough? if it is true, how to cut down the training memory?

**Comment by kentang-mit** [comment]
No it might not be enough for training. I think you can definitely use a smaller batch size, but I think 8G will probably be not enough for fusion model training even if you use batch size = 1.

**Comment by yzjalien** [comment]
understood, it failed while i use batch_size to 1.
It seems to expand my gpu memory .
thanks~

**Comment by kentang-mit** [comment]
I'm closing this issue since it is resolved. Feel free to reopen if you have further questions.
