### ISSUE TITLE
Does this code support running in multi-head mode? which means we get the detection and segmentation results simultaneosly

### ISSUE THREAD

**Issue by wjmstf1** [mit-han-lab/bevfusion#252]

**Comment by kentang-mit** [comment]
You can achieve that by specifying both `heads.object` and `heads.map` in the configuration, but this will not give you the best accuracy numbers as discussed in our paper.

**Comment by wjmstf1** [comment]
> 



> You can achieve that by specifying both `heads.object` and `heads.map` in the configuration, but this will not give you the best accuracy numbers as discussed in our paper.

OK. I see. Thank you.
