### ISSUE TITLE
The problem about evaluating the pretrained models

### ISSUE THREAD

**Issue by zhanglk9** [mit-han-lab/bevfusion#255]
I use 4 GPUs(GeForce RTX 3090) to evaluate the the pretrained model by runing the follow:
`torchpack dist-run -np 8 python tools/test.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml pretrained/bevfusion-det.pth --eval bbox`
but the  process always gets stuck and doesn't get the error:
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/100670920/205239772-1e4efa0a-e47c-4a71-b745-891046c9d96f.png">
And I saw that just 0s,1s and 3s GPU was been used.I trid several time but got the same problem.

**Comment by zhanglk9** [comment]
<img width="447" alt="image" src="https://user-images.githubusercontent.com/100670920/205240593-638cd2af-702a-49be-b1ca-01af3b0a8e7a.png">
GPU performance as above

**Comment by kentang-mit** [comment]
In this case it seems that you should not use `-np 8` because you have only 4 GPUs.

**Comment by zhanglk9** [comment]
> In this case it seems that you should not use `-np 8` because you have only 4 GPUs.
Sorry, I made a typo here. I used '-np 4' for testing, and I also tried '-np 1' and '-np 3''-np2',but the problem is the same. Sometimes I could meet this situation:
<img width="934" alt="image" src="https://user-images.githubusercontent.com/100670920/205580664-cbc392cd-cb8e-4705-b34b-8dc280fb3f04.png">

**Comment by kentang-mit** [comment]
It seems that you did not install `mmcv-full==1.4.0` and `mmcv==1.4.0` according to our suggestions in the README.md (otherwise spconv should not be part of mmcv-full). Please follow the instructions carefully and see if you can solve the problem.

**Comment by zhanglk9** [comment]
> It seems that you did not install `mmcv-full==1.4.0` and `mmcv==1.4.0` according to our suggestions in the README.md (otherwise spconv should not be part of mmcv-full). Please follow the instructions carefully and see if you can solve the problem.

https://github.com/mit-han-lab/bevfusion/issues/248#issuecomment-1339317712

I alse think testing the pretrained models with more than 1 GPU can be stuck is a bug

**Comment by kentang-mit** [comment]
Would you mind providing more information about your environment? E.g. CUDA version, PyTorch version, etc. Our recommendation is to use PyTorch 1.10.x + CUDA 11.3. You may also try out our docker environment, I've tested it multiple times on different machines (with CUDA 11.3), and every time I use >1 GPUs to run evaluation and training. 

By the way, the setup instruction in the issue 248 you mentioned is very helpful.

**Comment by kentang-mit** [comment]
Closed due to inactivity.
