### ISSUE TITLE
About tracking and coordinate system

### ISSUE THREAD

**Issue by derekray311511** [mit-han-lab/bevfusion#256]
Hi! I'm here again. I was stuck by two problems these days when I try to perform tracking.  

- Inference coordinate system (Nuscenes):
Do the model inference on the LiDAR coordinates? If yes, where do the yaw angle start from?  
This is my steps to track:  
1. Get outputs from BEVfusion-det model.
2. Format the outputs to nuscenes format.
![image](https://user-images.githubusercontent.com/84118285/205435193-3c2f8f00-f3cc-4772-b0ac-642211e78e2e.png)
3. Transform the objects to global coordinates.
4. Perform tracking same as centerpoint.  

I think the key point is step two. Is there any wrong especially on yaw angle and velocity?  
When I visualize them, some velocity will be on the opposite like this.
I think this cause the poor tracking result in my code.
![image](https://user-images.githubusercontent.com/84118285/205435369-3bcba8be-9e4c-4eaf-ab29-9c9a104ab752.png)

- Do you use bbox threshold when performing tracking?

**Comment by derekray311511** [comment]
Oh! I just fixed the first problem.  
The inference bboxes is [x, y, z, w, l, h, yaw, vx, vy] but not [x, y, z, w, h, l, yaw, b, v].
![image](https://user-images.githubusercontent.com/84118285/205439945-2d34e1eb-ebf5-4c14-b723-7e7626f806ad.png)

**Comment by kentang-mit** [comment]
Sounds good. Good luck for your tracking experiments.

**Comment by xjturjc** [comment]
@derekray311511  Hello, may I know your tracking results on nuScenes validation? I transplanted the tracker from CenterPoint, and the AMOTA is only 0.70. Thanks.

**Comment by derekray311511** [comment]
@xjturjc Hi! I also used the tracker from CenterPoint. I think I got the similar result as you did by directly using the CenterPoint tracker. You can simply get a better result by filtering out the low score bounding boxes. In my case, I set the threshold to 0.025 and got the AMOTA 0.742 on the validation set.

**Comment by changxu-zhang** [comment]
Hi @derekray311511, may I ask how you visualized tracking results from CenterPoint? Is there any off-the-shelf tools that I didn't notice? Thanks

**Comment by derekray311511** [comment]
Hi, @changxu-zhang, I write the visualization code by myself. It use ROS. You can see the code in my repository here, github.com/derekray311511/nusc_tracking

**Comment by changxu-zhang** [comment]
Hi @derekray311511, thanks for your share. I've also built one myself inspired by yours.
