### ISSUE TITLE
Question about Dynamic Fusion Module

### ISSUE THREAD

**Issue by ZhuYUzju** [mit-han-lab/bevfusion#261]
Thanks for your wonderful job. I found that you mentioned the Dynamic Fusion Module in your paper, however, I don't find the corresponding implementation in this repo. Is the "fuser" refer to this? But fuser is composed of only concat and add

**Comment by kentang-mit** [comment]
Hi @ZhuYUzju,

We did not mention that module in our paper. I guess you are referring to the paper from Peking University. The two methods are different though they share the same name. In our experiments, we verified that the "Dynamic Fusion Module" (which is squeeze-and-excitation + conv) is not effective. This is probably we fuse LiDAR and camera features a bit earlier than the researchers from PKU did.

Best,
Haotian
