### ISSUE TITLE
About MACs Scaling

### ISSUE THREAD

**Issue by Monoclinic** [mit-han-lab/bevfusion#268]
Hello, thanks for your great work.
I notice that you scaled up the model to match the MACs of other models, and I wonder which modifications should be applied.
As reported in the paper, scaling up the resolution of input images would bring some improvement, I wonder if it is too costly?
And I guess the increase in the number of attention layers (in transfusion) will be useful?

**Comment by kentang-mit** [comment]
Hi @Monoclinic, what we did is to scale up the resolution a bit. For example if you increase the resolution from 256x704 to 384x1056 as indicated in the ablation study, you should expect a ~2.25x increment in MACs. Using a heavier head / decoder architecture is definitely also feasible.

**Comment by Monoclinic** [comment]
Thanks!
