### ISSUE TITLE
what kind of gpu did you guys used in training

### ISSUE THREAD

**Issue by yy9996** [mit-han-lab/bevfusion#27]
thanks a lot

**Comment by luoyuchenmlcv** [comment]
If I recall correctly, they use 8 A6000 GPU to train the model

**Comment by kentang-mit** [comment]
Hi @yy9996,

We use 8 A6000 GPUs as @luoyuchenmlcv mentioned. We are working on supporting training with 12/24G GPU memory.

Best,
Haotian

**Comment by yy9996** [comment]
that is amazing!thanks
