### ISSUE TITLE
Log model weights and gradients

### ISSUE THREAD

**Issue by RG2806** [mit-han-lab/bevfusion#270]
Hey,
I want to log the model weights and gradients and visualize them as part of my experiments. Can you suggest where should I start for this?
Thanks

**Comment by kentang-mit** [comment]
Model weights are typically saved after each epoch finishes. Removing [this line](https://github.com/mit-han-lab/bevfusion/blob/3d91980d21556bf697f51b717875d0a31e5be2dd/configs/default.yaml#L6) will help you keep all the checkpoints.

For gradients, I believe that you probably have to add custom hooks. You may need to refer to the official document from mmcv/mmdet. We do record the gradient norm using mmcv apis, you can definitely check how mmcv obtains these values.

**Comment by RG2806** [comment]
thanks
