### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by zhangzaibin** [mit-han-lab/bevfusion#276]
Thanks for your great work! I have an issue with the data preparation. I miss the location in the anno file. 
data = dict(
            token=info["token"],
            sample_idx=info['token'],
            lidar_path=info["lidar_path"],
            sweeps=info["sweeps"],
            timestamp=info["timestamp"],
            location=info["location"],
        )

missing the key of "location"

**Comment by kentang-mit** [comment]
Hi @zhangzaibin,

Thanks for your interest. Would you mind creating the info file again using this codebase? I remember that we do include that field [here](https://github.com/mit-han-lab/bevfusion/blob/da93b27d0fe4563eecd46604e6cc5ddf1c5bd1ea/tools/data_converter/nuscenes_converter.py#L193).

Best,
Haotian

**Comment by kentang-mit** [comment]
Closed due to inactivity. Please feel free to reopen if you feel it necessary.
