### ISSUE TITLE
How long does it take to train the model? 

### ISSUE THREAD

**Issue by Yiir-1** [mit-han-lab/bevfusion#279]
Hello！Thanks for your good work ! could you please explain what GPU you used to train models, and how long does it take?

**Comment by kentang-mit** [comment]
It's around 25h for the LiDAR-only pretraining and another 10h for fusion finetuning. We use 8xA6000 GPUs.

**Comment by Yiir-1** [comment]
Thanks! What about  training camera-only BEV segmentation model ? Is it the same to use around 25h for 8*A6000?

**Comment by kentang-mit** [comment]
Yes I think it is roughly correct.
