### ISSUE TITLE
question about origin center

### ISSUE THREAD

**Issue by U201310646** [mit-han-lab/bevfusion#280]
Hi,
the same question #128 but i wanna ask if this change  will have an impact on the lidar's data augmentation? 
> https://github.com/mit-han-lab/bevfusion/blob/6908c57b7800268a9cdf3efeacbfb886d6077d6f/mmdet3d/datasets/nuscenes_dataset.py#L314-L317
origin set to (0.5,0.5,0), the following code wont be executed,this means the center is geometric center of  gt_bboxes_3d above
> https://github.com/mit-han-lab/bevfusion/blob/3d91980d21556bf697f51b717875d0a31e5be2dd/mmdet3d/core/bbox/structures/base_box3d.py#L61-L64      

but i noticed that  the origin here (0.5,0.5,0) in points_in_rbbox function, the center is considered as center of bottom surface to caculate the corners. Is this inconsistent?
> https://github.com/mit-han-lab/bevfusion/blob/3d91980d21556bf697f51b717875d0a31e5be2dd/mmdet3d/core/bbox/box_np_ops.py#L430

**Comment by kentang-mit** [comment]
Hi @U201310646,

Thank you for this issue and sorry for the late response. I was dealing with some other projects these days. After reading the code you pasted, I feel that if the code snippet in `core/bbox/structures/base_box3d.py` is not executed, the origin should be the center of the bottom surface, which matches with the default value in `core/bbox/box_np_ops.py`. But I would have a deeper look at this part and do some rigorous check on whether the GT databases generated by our code is indeed correct. 

Best,
Haotian

**Comment by U201310646** [comment]
Thanks, looking forward to your reply

**Comment by U201310646** [comment]
The x,y,z annotation in Nuscenes is the geometric center. But in LiDARInstance3DBoxes with origin(0.5,0.5,0) the code snippet in _core/bbox/structures/base_box3d.py_ will do nothing for origin. If origin set to (0.5,0.5,0.5), then the origin will be converted to the center of bottom surface, which then matched wth the default args in _core/bbox/box_np_ops.py_. Please correct me if i missuderstood.

**Comment by kentang-mit** [comment]
I think your understanding is correct. I did some check on the GT database generated with the released code and found it to be different from what we generated one year ago (and used in the experiments). I'm running more experiments to verify the impact.

**Comment by U201310646** [comment]
thanks for your reply!

**Comment by YongYongLi123** [comment]
> which then matched wth the default args in _core/bbox/box_np_ops.py_. Please correct me if i missuderstood.

I also have the same doubts, and I think your understanding is correct
