### ISSUE TITLE
Tracking Pipeline

### ISSUE THREAD

**Issue by RG2806** [mit-han-lab/bevfusion#282]
Hey @kentang-mit ,
Thanks for opensourcing this work,
I was interested in tracking part of your pipeline and wanted to replicate the metrics listed on benchmark https://www.nuscenes.org/tracking?externalData=all&mapData=all&modalities=Any
with regards to your repo.

Can you elaborate how should i proceed with this? Which Tracker did you use?

**Comment by kentang-mit** [comment]
Hi @RG2806,

We follow exactly the same tracking implementation as CenterPoint. You may check Tianwei's implementation in [this repo](https://github.com/tianweiy/CenterPoint) for more details.

Best,
Haotian

**Comment by kentang-mit** [comment]
Closed due to inactivity. Please feel free to reopen if you feel it necessary.
