### ISSUE TITLE
About fused model training  method  and  lidar model training method

### ISSUE THREAD

**Issue by Paul-Zhu** [mit-han-lab/bevfusion#284]
hi、thank you for your excellent work！
I am very interesting to know what is the fused model training steps and what is the lidar model training steps. this is my understanding:
(1）about training lidar model method
lidar model direct training 20 epoch according to the config file，is right？
(2）about training fused model method
first，load the lidar model from (1) when training，second，training six epcoh according to the config file，is right？

hope you reply   thanks!

**Comment by kentang-mit** [comment]
Hi Paul,

Yes, your understanding is correct.

Best,
Haotian

**Comment by kentang-mit** [comment]
Closed due to inactivity. Please feel free to reopen if you feel it necessary.
