### ISSUE TITLE
question about GlobalRotScaleTrans

### ISSUE THREAD

**Issue by FrontierBreaker** [mit-han-lab/bevfusion#295]
Hi, I would like to know whether using GlobalRotScaleTrans Augmentation will destroy the  alignment between image and points (by camera matrixs)?

**Comment by kentang-mit** [comment]
No it will not break the alignment. We maintain the multi-sensor alignment by inverting `bev_aug_matrix` (https://github.com/mit-han-lab/mmf-dev/blob/39d39b0e1562a144aae621a02eedb6235142b78b/mmdet3d/datasets/pipelines/transforms_3d.py#L161) in the vtransform module.

**Comment by FrontierBreaker** [comment]
Got it. Thanks!!
