### ISSUE TITLE
Flops counting

### ISSUE THREAD

**Issue by dikubab** [mit-han-lab/bevfusion#298]
How can we count the number of flops and params in each configs?

**Comment by kentang-mit** [comment]
You may refer to [this file](https://github.com/mit-han-lab/bevfusion/blob/main/mmdet3d/models/utils/flops_counter.py) for more details. We use the [thop](https://github.com/Lyken17/pytorch-OpCounter) package.

**Comment by dikubab** [comment]
I have been trying it. But it could not calculate the flops.

**Comment by kentang-mit** [comment]
Would you mind providing more details? I believe this script should work if you inject the `flops_counter` to your test script.

**Comment by kentang-mit** [comment]
Closed due to inactivity. Please feel free to reopen if you feel it necessary.
