### ISSUE TITLE
Which version of mmdetection3d is bevfusion based on?

### ISSUE THREAD

**Issue by mljack** [mit-han-lab/bevfusion#3]
Could you provide the version or commit it forks from?

Thanks a lot!

**Comment by kentang-mit** [comment]
Hi @mljack, if I remember it correctly, we forked our repo from [this commit](https://github.com/open-mmlab/mmdetection3d/tree/60ce864ff76af4316fb9ae56a2a5b7741bfdd9ab).

**Comment by mljack** [comment]
Is it possible to public more training details for these pretrained weights? For example, the training machine GPU count, training time or even training log?

**Comment by kentang-mit** [comment]
Definitely. We train BEVFusion on 8 NVIDIA RTX A6000 GPUs, each with 48G GPU memory. The detection model takes around 35 hours to train and the segmentation model takes 25 hours to train. The training log will be included in future release. We are still working hard to make BEVFusion trainable on GPUs with less memory. Stay tuned for more updates!

**Comment by mljack** [comment]
Super cool! Looking forward your new updates!
