### ISSUE TITLE
image view augmentation ablation study

### ISSUE THREAD

**Issue by AndyYuan96** [mit-han-lab/bevfusion#302]
Hi，I just wonder whether your guys have done image view augmentation ablation study for fusion methods training，for camera-only method，image view augmentation is useful， which is verified in bevdet‘s paper，so I just wonder whether image view augmentation is also useful in camer-lidar fusion training stage。

**Comment by kentang-mit** [comment]
Yes, we did. The results are presented in Table 4 in a reduced schedule. The impact of image augmentation will be smaller under a full schedule.
