### ISSUE TITLE
How to disable CBGS?

### ISSUE THREAD

**Issue by sunnyHelen** [mit-han-lab/bevfusion#303]
Hi Haotian,
I need the performance without CBGS. Could you please give quick guidance about how to disable it? 

Thanks a lot~

**Comment by kentang-mit** [comment]
CBGS can be turned off if you comment out lines 264-265 in [this file](https://github.com/mit-han-lab/bevfusion/blob/db75150717a9462cb60241e36ba28d65f6908607/configs/nuscenes/default.yaml#L264) and reduce the indentation of lines 266-275 by one level.

**Comment by sunnyHelen** [comment]
Got it. Many thanks.

**Comment by kentang-mit** [comment]
No problem. I'm closing the issue since it is resolved.
