### ISSUE TITLE
The gap of only-lidar model

### ISSUE THREAD

**Issue by hht1996ok** [mit-han-lab/bevfusion#305]
Thank you for your contribution, When I trained the only lidar branch, I found that its accuracy could not reach the reported mAP/NDS 64.68/69.28. Is there any additional setting during the training of only-lidar branch?

**Comment by hht1996ok** [comment]
Can you provide the weight of the only-lidar branch weight which trained in train+val set

**Comment by kentang-mit** [comment]
Sorry I missed your issue previously. We did not keep the pretrained models on train+val but it's performance should be similar to TransFusion-L.

**Comment by hht1996ok** [comment]
@kentang-mit Thank you for your reply, I have found a solution from the source code of transfusion. May I ask if you have found the reason for the low precision of the Transfusion branch？

**Comment by kentang-mit** [comment]
One possible reason is that this version of codebase has incorrect settings for the center of gt boxes [here](https://github.com/mit-han-lab/bevfusion/blob/db75150717a9462cb60241e36ba28d65f6908607/mmdet3d/datasets/nuscenes_dataset.py#L321). You should change the center from (0.5, 0.5, 0) back to (0.5, 0.5, 0.5) (default in mmdet3d) to avoid problems in gt database construction.

**Comment by qianqianqianqian** [comment]
> @kentang-mit Thank you for your reply, I have found a solution from the source code of transfusion. May I ask if you have found the reason for the low precision of the Transfusion branch？

I have met the same problem, are there some solutions?

**Comment by hht1996ok** [comment]
> One possible reason is that this version of codebase has incorrect settings for the center of gt boxes [here](https://github.com/mit-han-lab/bevfusion/blob/db75150717a9462cb60241e36ba28d65f6908607/mmdet3d/datasets/nuscenes_dataset.py#L321). You should change the center from (0.5, 0.5, 0) back to (0.5, 0.5, 0.5) (default in mmdet3d) to avoid problems in gt database construction.

Thank you for your reply, I will try it.

**Comment by longsuo** [comment]
> One possible reason is that this version of codebase has incorrect settings for the center of gt boxes [here](https://github.com/mit-han-lab/bevfusion/blob/db75150717a9462cb60241e36ba28d65f6908607/mmdet3d/datasets/nuscenes_dataset.py#L321). You should change the center from (0.5, 0.5, 0) back to (0.5, 0.5, 0.5) (default in mmdet3d) to avoid problems in gt database construction.

 Do I need to rerun the tools/create_data.py after change the center from (0.5, 0.5, 0) back to  (0.5, 0.5, 0.5) ? Looking forward to your response.

**Comment by kentang-mit** [comment]
Yes, that is true. @longsuo
