### ISSUE TITLE
Epoch

### ISSUE THREAD

**Issue by autumn-wong** [mit-han-lab/bevfusion#307]
Thank you for such great work. During the training, I encountered the following problem:
When I train with 2 GPUs, the number in the red box is 815, while the number in the red box is 544 when I train with 3 GPUs. 
Is there any reason behind this?
<img width="797" alt="815" src="https://user-images.githubusercontent.com/93367180/219635156-2dad2137-6c48-48e0-88cc-326406e5a322.png">
<img width="799" alt="544" src="https://user-images.githubusercontent.com/93367180/219635182-e2438400-6740-408d-99d6-69b54c57cb7e.png">

**Comment by kentang-mit** [comment]
I think the behavior is expected. Basically we expect number of iterations x number of gpus to be a constant. Because number of iterations x number of gpus x batch size = dataset size.

**Comment by autumn-wong** [comment]
Oh, I see. I used the nuscenes-mini dataset for the experiment. Because of the equipment, the batchsize can only be set to 1, so 544 * 3 * 1=815 * 2 * 1. Thank you!

**Comment by South-River** [comment]
Hello, 
I also tried to train it on the nuscenes-mini dataset. But I only get 0.42 map and 0.48 NDS under default config. Far worse than the model in the paper. And I'm training the model with full dataset, but I have to wait 5 days.  
So I want to know what's your result?
