### ISSUE TITLE
Is the model ckpt compatible with the ckpt of models in mmdet3d

### ISSUE THREAD

**Issue by FrontierBreaker** [mit-han-lab/bevfusion#309]
Hi, I would like to know whether the pretrained models (e.g., pretrained backbone(voxelnet)) trained in OpenPCDet can be load to a model in mmdet3d? Thanks!

**Comment by kentang-mit** [comment]
I did not have a chance to have a look at the OpenPCDet implementation of the voxelnet backbone, but I could imagine that there must be some conflicts in the model keys. You might need to handle that manually.

**Comment by FrontierBreaker** [comment]
got that, thanks~
