### ISSUE TITLE
Nuscenes train annotation without location key

### ISSUE THREAD

**Issue by rylynchen** [mit-han-lab/bevfusion#311]
Hi, I found a problem in nuscenes_dataset.py, like:
```
    def get_data_info(self, index: int) -> Dict[str, Any]:
        info = self.data_infos[index]

        data = dict(
            token=info["token"],
            sample_idx=info['token'],
            lidar_path=info["lidar_path"],
            sweeps=info["sweeps"],
            timestamp=info["timestamp"],
            location=info["location"],
        )
```
But, in nuscenes_infos_train.pkl info values, without location.
Anyone met the same problem ?

**Comment by kentang-mit** [comment]
Are you using the pkl file generated from mmdetection3d? If so, I would recommend you to either regenerate the info file using our codebase or remove the location term in the `data` dict. Our data preprocessing code does record `location` in the pkl, as indicated [here](https://github.com/mit-han-lab/bevfusion/blob/db75150717a9462cb60241e36ba28d65f6908607/tools/data_converter/nuscenes_converter.py#L203).

**Comment by kentang-mit** [comment]
Closed due to inactivity. Please feel free to reopen if you feel it necessary.

**Comment by rylynchen** [comment]
Thanks for your reply ! Can you show the way how to use nuscenes_converter.py ? I can't find anything about it in README.
