### ISSUE TITLE
Is anyone using `2080ti`x8 to train the fusion model successfully??

### ISSUE THREAD

**Issue by zhanglk9** [mit-han-lab/bevfusion#314]
<img width="358" alt="image" src="https://user-images.githubusercontent.com/100670920/220284213-04a6694b-3386-4d97-a2e0-33ef2e44366e.png">
I change the works to 1,but it still be stuck.

**Comment by kentang-mit** [comment]
I think you might have encountered OOM. 2080Ti does not have enough memory to train the fusion model.

**Comment by kentang-mit** [comment]
Closed due to inactivity. Please feel free to reopen if you feel it necessary.
