### ISSUE TITLE
Decoder

### ISSUE THREAD

**Issue by NoOneUST** [mit-han-lab/bevfusion#315]
Hello,

Your code uses SubMConv to extract features from a sparse point cloud, how should I recover the point cloud using a decoder? I only want to get values of the points existed in the original sparse point cloud.

**Comment by kentang-mit** [comment]
Would you mind specifying what kind of features you need from the original points? If you just need the coordinates, you should be able to pass [this variable](https://github.com/mit-han-lab/bevfusion/blob/db75150717a9462cb60241e36ba28d65f6908607/mmdet3d/models/backbones/sparse_encoder.py#L112) out of the sparse encoder.

**Comment by NoOneUST** [comment]
Thank you for your reply. As you know, the voxel encoder generates a BEV feature map. I hope to have a decoder converting the BEV feature map to the voxel form and make sure the recovered voxel is similar to the voxel converted from points. This is to guarantee the BEV feature map well represents the point clouds.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kentang-mit** [comment]
I see. If that is the case, you probably want to have a unet-like architecture. You can use sparseconvs with stride > 1 to downsample and recover the original features using transposed sparseconv. You may take a look at our [spvnas](https://github.com/mit-han-lab/spvnas) project for more details. This is very similar to segmentation models.

**Comment by kentang-mit** [comment]
Closed due to inactivity. Please feel free to reopen if you feel it necessary.
