### ISSUE TITLE
about fusion 

### ISSUE THREAD

**Issue by study0101** [mit-han-lab/bevfusion#318]
Dear authors:
I tried to adjust the fusion module to the back of SecondFPN , as #103 mentioned,but I got 0map. I have checked the coordinates. Do you know the reason? 
Thanks a lot!

**Comment by kentang-mit** [comment]
I'm not sure about this experiment setting since it is not proposed in our paper. Perhaps you could first verify whether it is possible to reproduce our results.

**Comment by kentang-mit** [comment]
Closed due to inactivity. Please feel free to reopen if you feel it necessary.
