### ISSUE TITLE
image and labels mismatch

### ISSUE THREAD

**Issue by linghai06** [mit-han-lab/bevfusion#319]
Hi. Thanks for open-sourcing this wonderful work. But I got confused when reading and playing with the codes.

I tried tools/visualize.py to visualize the train split of the nuscenes dataset(with configs/nuscenes/seg/camera-bev256d2.yaml) and found that the images and the labels did not match in uv space, such as 

<img width="903" alt="image" src="https://user-images.githubusercontent.com/7567001/220832704-51063323-3a6b-438d-82ba-13e6d1e69eec.png">

But it was OK for the val split. So I dig into the train_pipeline and found that in ImageAug3D you affine transform the images but leave alone the labels and in RandomFlip3D you randomly flip the labels but leave alone the images. Wouldn't this be a problem? 

Looking forward to getting a reply from you. Thank you.

**Comment by kentang-mit** [comment]
Thanks for bringing about the discussion. The logic behind `ImageAug3D` and `RandomFlip3D` is that `ImageAug3D` is only supposed to apply transformations to images, so the LiDAR bounding boxes will not change. In contrast, `RandomFlip3D` is a LiDAR-only augmentation, so it will not influence the images for the same reason. 

The reason why you observe such misalignment of GT boxes and camera images is that we assume no augmentation in the visualization code (see [here](https://github.com/mit-han-lab/bevfusion/blob/db75150717a9462cb60241e36ba28d65f6908607/tools/visualize.py#L141)). The transformation matrix is assumed to be the original `lidar2image` matrix from the dataset loader, while if you have augmentations you need to consider LiDAR and image augmentation matrices.

**Comment by kentang-mit** [comment]
Closed due to inactivity. Please feel free to reopen if you feel it necessary.
