### ISSUE TITLE
cfg["sync_bn"]

### ISSUE THREAD

**Issue by Bincle-Yin** [mit-han-lab/bevfusion#32]
Heip!!!!! what is cfg["sync_bn"]? Is it about distributed train?Can you tell me how to get it in cfg?

**Comment by kentang-mit** [comment]
Yes, it is used for distributed training, but I remember that we did not specify it in our experiments. 

There are two ways you can use the `sync_bn` flag in the config. Simply applying 
```yaml
sync_bn: true
```
will convert all BN layers to SyncBN layers. If you write 
```yaml
sync_bn:
  exclude:
    - encoder
```
It means that all BN layers whose name in state_dict starts with `encoder` will not be converted to SyncBN.

**Comment by Bincle-Yin** [comment]
thank you so much

**Comment by kentang-mit** [comment]
No problem. I will temporarily close this issue.

**Comment by Paul-Zhu** [comment]
what is the reason why did not use SyncBN ? Is it because of the pytorch version not support or when use SyncBN not improve precision so did not use?

**Comment by Paul-Zhu** [comment]
hello,   what is the reason why did not use SyncBN ? Is it because of the pytorch version not support or when use SyncBN not improve precision so did not use? @kentang-mit
