### ISSUE TITLE
“height” represents the heights of the top center？

### ISSUE THREAD

**Issue by U201310646** [mit-han-lab/bevfusion#320]
Hi,

Thanks for open-sourcing the awesome work! A question is bothering me: 
The output of TransfusionHead in the bevfusion model contains keywords such as center, **`height`**, dim, rot, etc.
During the inference phase the output will be executed by the **get_bboxes** function, as follows:
https://github.com/mit-han-lab/bevfusion/blob/db75150717a9462cb60241e36ba28d65f6908607/mmdet3d/models/fusion_models/bevfusion.py#L284-L285

In function **get_bboxes** the predicted bboxes will be decoded as follows:
https://github.com/mit-han-lab/bevfusion/blob/db75150717a9462cb60241e36ba28d65f6908607/mmdet3d/models/heads/bbox/transfusion.py#L741-L749

In function **decode** **`height`** first subtracted from dim[:2] by half
https://github.com/mit-han-lab/bevfusion/blob/db75150717a9462cb60241e36ba28d65f6908607/mmdet3d/core/bbox/coders/transfusion_bbox_coder.py#L67

In visulize.py  **`height`**  subtracted from dim[:2] by half again
https://github.com/mit-han-lab/bevfusion/blob/db75150717a9462cb60241e36ba28d65f6908607/tools/visualize.py#L118-L119

At last **`height`** is visualized as the center of the bottom surface with `visualize_camera` and `visualize_lidar`.
so the predicted ”height” in Header model represents the heights of the top center？ why so strange?

best wishes

**Comment by kentang-mit** [comment]
I did some experiments according to another issue and found that we may want to change the origin [here](https://github.com/mit-han-lab/bevfusion/blob/db75150717a9462cb60241e36ba28d65f6908607/mmdet3d/datasets/nuscenes_dataset.py#L321) from (0.5, 0.5 0) to (0.5, 0.5, 0.5). i.e., make sure the box origin is in the center. I'll publish a PR later to introduce this fix. The current implementation is written such that the visualization on 2D images is correct.

**Comment by U201310646** [comment]
yeah, the visualization is right but it conflicts with lidar data augmentation like this issue #280. Changing origin form (0.5,0.5,0) to (0.5, 0.5, 0.5) can resolve this conflict, but need to remove _height -= dim[:2]/2_ in visualize.py. Base my understanfing the pred_dict[" height "] of TransfusionHead represents the height of the geometric center after set origin as (0.5,0.5,0.5) , whereas before it represents the height of the top surface.

**Comment by U201310646** [comment]
One more question:
during the training phase if the backbone of lidar and camera need to freeze or just end-to-end to fineturn all paramaters.
Looking forward to your response!

**Comment by Jayden9912** [comment]
> I did some experiments according to another issue and found that we may want to change the origin [here](https://github.com/mit-han-lab/bevfusion/blob/db75150717a9462cb60241e36ba28d65f6908607/mmdet3d/datasets/nuscenes_dataset.py#L321) from (0.5, 0.5 0) to (0.5, 0.5, 0.5). i.e., make sure the box origin is in the center. I'll publish a PR later to introduce this fix. The current implementation is written such that the visualization on 2D images is correct.

I am able to reproduce the result using the repo code (i.e. using 0.5,0.5,0). In this case, is it right to conclude that the model learn to offset the bbox center to the bottom center?
