### ISSUE TITLE
Image pre-processing

### ISSUE THREAD

**Issue by autumn-wong** [mit-han-lab/bevfusion#321]
Hello, thanks for your great work. 
In the process of reproducing the code, we finded that after the image pre-processing, such color images are obtained and they were fed to the SwinTransformer moudle as input to extract image features. (It should be the ImageNormalize function that does the change to color images) 
Is there any special reason for pre-processing the original image into such a color image? Maybe for Extracting edge? We think that this operation may damage the rich context from camera.

![tmpfpm8pe4l](https://user-images.githubusercontent.com/93367180/220908248-64d29083-6f9f-4528-9c58-6413c464fa3f.PNG)

**Comment by kentang-mit** [comment]
Actually the `ImageNormalize` function is not changing the colors of the original image. It just converts the 8-bit RGB values to a float tensor using standard z-score normalization (and the mean and std values are from ImageNet).

**Comment by kentang-mit** [comment]
Closed due to inactivity. Please feel free to reopen if you feel it necessary.

**Comment by hehern** [comment]
maybe you use the "cv2.imwrite" to save the img. PIL reads in the order of rgb and cv2 writes in the order of bgr
