### ISSUE TITLE
About format convertion.

### ISSUE THREAD

**Issue by YangChen1234567** [mit-han-lab/bevfusion#322]
Hi, thanks for your greate work!
I am tring to train bevfusion on our own datasets, but when i generate the .pkl file, I found that the box format used in your project is [x, y, z, w, l, h, -rot - pi/2] rather than [x, y, z, l, w, h, rot].
Is there any reason for this transformation? 
Look forward to your reply, thanks~~

**Comment by kentang-mit** [comment]
We follow the coordinate system convention of mmdet3d in late 2021. This is because we forked from their codebase at that time when we started developing this project.

**Comment by YangChen1234567** [comment]
ok， thanks~~~

**Comment by kentang-mit** [comment]
I'm closing this issue since it is resolved. Feel free to reopen if there are further questions.
