### ISSUE TITLE
questions about pretrained img_backbone

### ISSUE THREAD

**Issue by gubei1998** [mit-han-lab/bevfusion#324]
I want to use your method to import the pretrained swint net into my model,But I don't know how to define a load_checkpoint module in my network to load pre-training parameters, so I would like to ask you where this module is located in your bevfusion, 
      The second question is that I went to the original swint code and found that it does not define convert_weights and init_cfg parameters, and your bevfusion does not have the complete swint code, so I would like to ask if you can provide me with the download address of the complete swint code used by img_backbone in your network?
      Thank you very much!

**Comment by kentang-mit** [comment]
Hi @gubei1998,

Our SwinT implementation is inherited from mmdet 2.20.0. You can find their implementation [here](https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/backbones/swin.py).

Best,
Haotian

**Comment by kentang-mit** [comment]
Closed due to inactivity. Please feel free to reopen if you feel it necessary.
