### ISSUE TITLE
Config on waymo

### ISSUE THREAD

**Issue by minrui-hust** [mit-han-lab/bevfusion#326]
I know you are doing some code cleaning work before release the config for waymo dataset. 
Before that be done, could you give some hint on how to tune on waymo dataset?
What changed compared to nuscenes?

**Comment by kentang-mit** [comment]
We will release the code for Waymo in the next version of this codebase. The major difference from nuScenes detection experiments is that we use CenterPoint instead of TransFusion.

**Comment by minrui-hust** [comment]
Thanks a lot.
I also found that transfusion head does not work well on waymo dataset, when I previously evaluating Transfusion.
I have reproduced Bevfusion on nuscenes with a similar result,  however when I try it on waymo dataset, with image backbone  swin-t pretrained on coco and centerpoint head, it seems no gain compared to raw centerpoint.  I guess pretraining image backbone on waymo is cirtical,  am I right?  What's more, what is your image augmentation setting in detail on waymo?

**Comment by minrui-hust** [comment]
I try a depth modulation on the predicted weight of different depth(like the spatial modulated attention), and got considerable gain.
On nuscenes val with out tta or enssemble:
![bevfusion_nusc](https://user-images.githubusercontent.com/42531084/226635509-7815e55d-041a-4e1e-9257-c82c08a936ca.png)
about 1mAP

**Comment by kentang-mit** [comment]
Your new results sound very promising to me. 

For Waymo, we did pretraining on its own images dataset instead of COCO. Our configurations for the fusion model is similar to DeepFusion (CVPR'22), where a larger rotation augmentation on LiDAR could matter a lot.

**Comment by minrui-hust** [comment]
OK, I will refer DeepFusion for more details

**Comment by lcc815** [comment]
> We will release the code for Waymo in the next version of this codebase. The major difference from nuScenes detection experiments is that we use CenterPoint instead of TransFusion.

hi, do  you have any plan when will you release your next version code?

**Comment by kentang-mit** [comment]
Hi @lcc815,

I am switching to a different research project recently so it is hard to give a concrete timeline. But we have someone working on code cleanning now and hopefully we can get it done asap.

Best,
Haotian

**Comment by Provemj** [comment]
> We will release the code for Waymo in the next version of this codebase. The major difference from nuScenes detection experiments is that we use CenterPoint instead of TransFusion.

Sorry to bother, but when would this version be released?
