### ISSUE TITLE
Nusecenes data process problems

### ISSUE THREAD

**Issue by Slienceseeker** [mit-han-lab/bevfusion#327]
![wx_camera_1677476840895](https://user-images.githubusercontent.com/47714564/222083754-1f530db2-b163-404b-8b2c-ce8eee55722b.jpg)
When I use the command to process the dataset follow the instruction, the process had been killed and occurred these errors.
mmdetection3d
├── mmdet3d
├── tools
├── configs
├── data
│   ├── nuscenes
│   │   ├── maps
│   │   ├── samples
│   │   ├── sweeps
│   │   ├── v1.0-test
|   |   ├── v1.0-trainval
│   │   ├── nuscenes_database
│   │   ├── nuscenes_infos_train.pkl
│   │   ├── nuscenes_infos_val.pkl

So that I just got these files without the others although I tried many times.

**Comment by kentang-mit** [comment]
Looks like there are some problems when creating the GT database. Would you mind locating what is the file name that causes this load error? You may inject some print statements around ln 211 of the `mmdet3d/datasets/pipelines/loading.py` file.

**Comment by kentang-mit** [comment]
Closed due to inactivity. Please feel free to reopen if you feel it necessary.
