### ISSUE TITLE
Training details

### ISSUE THREAD

**Issue by haoshuai714** [mit-han-lab/bevfusion#329]
Thank you for your excellent work.I have several questions about the training details: How many epochs have you trained for 3d object detection and segmentation tasks? What is the size of each batch? From the ablation experiment, we can find that the size of epoch has a great influence on the experimental results. In addition, what GPU machine did you use in the training phase and how long did you train? Looking forward to your reply!

**Comment by kentang-mit** [comment]
Hi @haoshuai714,

I sent you an Email about the details. I will close this issue.

Best,
Haotian
