### ISSUE TITLE
have you ever use fusion model weight to inference in lidar model？

### ISSUE THREAD

**Issue by AndyYuan96** [mit-han-lab/bevfusion#332]
Hi，I find some times，for occluded objects，lidar-only model can detect the object，but fusion can‘t，and I find if I use the fusion weight to inference with lidar-only model，the performance drop。did your guys find the situation。

**Comment by kentang-mit** [comment]
Hi Andy,

The observation is very interesting. I did not try out LiDAR-only inference with fusion weights. I guess you can do some ensemble between LiDAR-only model and the fusion model to see whether it can improve the recall on these occluded objects. If so, it might be an interesting direction to try out.

Best,
Haotian

**Comment by kentang-mit** [comment]
Closed due to inactivity. Please feel free to reopen if you feel it necessary.
