### ISSUE TITLE
Where are the results of the Evaluation?

### ISSUE THREAD

**Issue by syh1620** [mit-han-lab/bevfusion#334]
where are the results of the evaluation?

Results writes to /tmp/tmp3ntpwyqw/results/result.json
Where is this document, please?

**Comment by kentang-mit** [comment]
This is a temporarily generated file during training and will be removed when evaluation is done. If you want to generate this file for future processing, you may need to add a flag like that to your execution command:

```bash
--eval-options 'jsonfile_prefix=[path to desired folder]/result.json'
```

**Comment by kentang-mit** [comment]
Closed due to inactivity. Please feel free to reopen if you feel it necessary.
