### ISSUE TITLE
evaluation 

### ISSUE THREAD

**Issue by youngfly** [mit-han-lab/bevfusion#346]
**Dear author, would you please show the config which includes below operation?**

(We slightly increased the input resolution (to match the computation cost of concurrent work) and updated the input preprocessing pipeline.)

![屏幕截图 2023-03-15 144803](https://user-images.githubusercontent.com/30973033/225483212-aa83e9b2-a5b8-45ac-8a69-d048ea4b1380.png)

**Comment by kentang-mit** [comment]
We just increase the input image resolution from 704x256 to 1056x384.

**Comment by youngfly** [comment]
Thanks you for your kindness.
