### ISSUE TITLE
 can i train bevfusion with kitti dataset

### ISSUE THREAD

**Issue by Baron6977** [mit-han-lab/bevfusion#349]
Thank you for the author's contribution ：）
Can I train bevfusion with kitti dataset？？？？

**Comment by kentang-mit** [comment]
Yes it is also possible, but probably you will have to implement the dataloaders for KITTI by yourself. There might be some references from mmdet3d that could be very helpful, but I am not very familiar with it.

**Comment by SeungHwi0613** [comment]
I want to test and evaluate bevfusion with kitti dataset. then i don't have to change anything?  maybe it is little bit silly question for you... i just want to confirm it.

**Comment by xxp912** [comment]
@Baron6977 
Hello,  I meet the same problem with you, may I ask if you were successful?

**Comment by chenzb0712** [comment]
Hello, I meet the same problem with you, may I ask if you were successful?

**Comment by Lcl159** [comment]
Hello, I meet the same problem with you, may I ask if you were successful?

**Comment by liuyuansheng624** [comment]
> @Baron6977 Hello, I meet the same problem with you, may I ask if you were successful?

i can

**Comment by liuyuansheng624** [comment]
> Hello, I meet the same problem with you, may I ask if you were successful?

sure

**Comment by guoningwang** [comment]
@liuyuansheng624  你好，请问您是怎么训练kitti数据集的，方便分享一下吗？我怎么联系您？你可以guoningwang@163.com 联系我.

**Comment by weilli** [comment]
> > @Baron6977 Hello, I meet the same problem with you, may I ask if you were successful?
> 
> i can

Hello! How about the performance in the KITTI (compared to the Voxel-RCNN)? Would you share the evaluation? Thanks!

**Comment by liuyuansheng624** [comment]
you can &nbsp;wechat 13731082126 for me



发自我的iPhone


------------------ Original ------------------
From: weilli ***@***.***&gt;
Date: Sun,Dec 17,2023 10:08 PM
To: mit-han-lab/bevfusion ***@***.***&gt;
Cc: liuys ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [mit-han-lab/bevfusion]  can i train bevfusion with kitti dataset(Issue #349)

**Comment by c-yyyy** [comment]
> Hello, I meet the same problem with you, may I ask if you were successful?

hello! Have you succeeded, please！

**Comment by liuyuansheng624** [comment]
加我微信13731082126

发自我的iPhone


------------------ Original ------------------
From: chen ***@***.***&gt;
Date: Tue,Apr 9,2024 7:06 PM
To: mit-han-lab/bevfusion ***@***.***&gt;
Cc: liuys ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [mit-han-lab/bevfusion]  can i train bevfusion with kitti dataset(Issue #349)





  
Hello, I meet the same problem with you, may I ask if you were successful?
  
hello! Have you succeeded, please！
