### ISSUE TITLE
Reference to frame on out.pkl file on Evaluation

### ISSUE THREAD

**Issue by GDMG99** [mit-han-lab/bevfusion#352]
Thank you authors for your great work. 
I ran the evaluation command on the detection mode of the fusion network and got the out.pkl file with the flag --out. I wanted to visualize the results using that file on a custom visualizer. The detections of the elements of the list in the file do not seem to match the order of the files in the val info file. There are the same number of samples in the file as samples in the validation dataset (6019). I was wondering if it is possible to retrieve the data (cameras + pointcloud) from each element of the list in the out.pkl file. The nuscenes token of the sample would be fine.
Thank you in advance.

**Comment by kentang-mit** [comment]
Good question. Would you mind having a look at the predictions in `out.pkl` and see if they match the order in `nuscenes_infos_val.pkl`? If so, you can reuse the paths to images and point clouds in `nuscenes_infos_val.pkl`.
