### ISSUE TITLE
question about lidar intensity

### ISSUE THREAD

**Issue by alchemz** [mit-han-lab/bevfusion#353]
Dear Author @kentang-mit ,

In the [mmdet3d doc ](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/en/datasets/nuscenes_det.md), it has the below paragrah on addressing lidar intensity

Compared to general cases, nuScenes has a specific 'LoadPointsFromMultiSweeps' pipeline to load point clouds from consecutive frames. The default use_dim in 'LoadPointsFromMultiSweeps' is [0, 1, 2, 4], where the first 3 dimensions refer to point coordinates and the last refers to timestamp differences. **Intensity is not used by default due to its yielded noise when concatenating the points from different frames.**

I am trying to change the bevfusion config of **use_dim=5 to use_dim=[0, 1, 2, 4] to train without intensity**, but it throw many errors. Is it intensity being used/is useful in BEVFusion?
(https://github.com/mit-han-lab/bevfusion/blob/db75150717a9462cb60241e36ba28d65f6908607/configs/nuscenes/default.yaml#L1-L7)

 I would like to learn if you have compared the performance with/without intensity?

**Comment by kentang-mit** [comment]
Good question. I think intensity is very important and I vaguely remember that the performance of the LiDAR-only detector could drop a lot without intensity (but I'm not quite sure, I ran these experiments in 2021). One of the reason you might encounter bugs when modifying `use_dim` from 5 to `[0, 1, 2, 4]` is that you probably have not updated the input dimension to the LiDAR encoder accordingly. You may check out this [line](https://github.com/mit-han-lab/bevfusion/blob/db75150717a9462cb60241e36ba28d65f6908607/configs/nuscenes/det/transfusion/secfpn/lidar/voxelnet_0p075.yaml#L14). For fusion model I believe there are similar fields that you need to modify.

**Comment by alchemz** [comment]
@kentang-mit Thanks for your response. I have managed to change use_dim from 5 to [0, 1, 2, 4], and I do need to change input dim to be 4 and few other places to get it work. Here is my observation. **With intensity removed, there is 0.5% NDS drop, and over 1.5% mAP drop in lidar model performance.** 

This is in fact very interesting, because this finding conflicts with the recommendation in the [mmdet3d doc](https://github.com/open-mmlab/mmdetection3d/blob/master/docs/en/datasets/nuscenes_det.md), which suggests nuscenes lidar default should have intensity removed. 

I have checked the mmdet-centerpoint implementation, it also uses intensity. I wonder if the noise from intensity could in fact be beneficial for model performance.

**Comment by kentang-mit** [comment]
Hi @alchemz,

I think intensity should be helpful for LiDAR-only models because they do convey messages about the color of objects. If you remove them you basically only have geometric (and time) information from the features, which could make it harder for the model to learn. In all our experiments with BEVFusion we always try to utilize all information available.

Best,
Haotian
