### ISSUE TITLE
Testing with 2 GPUs doesn't finish running

### ISSUE THREAD

**Issue by ssuralcmu** [mit-han-lab/bevfusion#354]
Command run-
torchpack dist-run -np 2 python tools/test.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml pretrained/bevfusion-det.pth --eval bbox

I was able to run this with 2 2080Ti GPUs and get results. I upgraded to 2 A6000 GPUs today and ran the same thing. It hangs midway through execution. The same occurs with training with -np 2 argument. Testing works fine with np set to 1. Do you know what might be going wrong? The CUDA version is still the same and I did not reinstall anything. The A6000 GPUs work in general and show up in nvidia-smi.

For the above mentioned command, it doesn't proceed after the following output-
2023-03-24 03:42:41,739 - mmdet - INFO - load checkpoint from http path: https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_tiny_patch4_window7_224.pth. 

Even loading a pretrained model without downloading has the same issue.

To add, 
training with np set to 1 has the following error-
RuntimeError: sigmoid_focal_loss_forward_impl: implementation for device cuda:0 not found 

More details-
Driver Version: 465.19.01    CUDA Version: 11.3 
I am running this in a docker and have installed everything using the latest DockerFile.

**Comment by kentang-mit** [comment]
Did you have a chance to rerun `python setup.py develop`? It seems to me that the focal loss kernel is not compiled for your current device.

**Comment by kentang-mit** [comment]
Hi @ssuralcmu,

Thanks a lot for your solution and explanation! I may want to highlight it to all other users that meet with the problem.

Best,
Haotian

**Comment by ssuralcmu** [comment]
I tried installing mmcv from scratch as well by following their instructions. That didn’t resolved the problem  for me. Cuda did not get picked up during installation as there is something called an “MMCV Cuda compiler” that has to be installed and the additional steps added to the dockerfile were required.
