### ISSUE TITLE
no vfe in lidar encoder

### ISSUE THREAD

**Issue by alchemz** [mit-han-lab/bevfusion#356]
Dear author @kentang-mit ,

I found that the lidar only detector with transfusion does not have VFE layer but take 3D sparse convolution in lidar encoder config, and I wonder if this is the chosen model architecture? Previously, **I thought vfe is the main contribution of voxelnet, thus I am surpised to find bevfusion has not used vfe for voxelnet config.**

https://github.com/mit-han-lab/bevfusion/blob/db75150717a9462cb60241e36ba28d65f6908607/configs/nuscenes/det/transfusion/secfpn/lidar/voxelnet_0p075.yaml#L4-L16

For reference [mmdet-3d-centerpoint mode config](https://github.com/open-mmlab/mmdetection3d/blob/47285b3f1e9dba358e98fcd12e523cfd0769c876/configs/_base_/models/centerpoint_01voxel_second_secfpn_nus.py#L1-L11) has HardSimpleVFE included.

Assuming Bevfusion chose to not use vfe, have you experimented with vfe before?

**Comment by kentang-mit** [comment]
Indeed we did not use VFE for LiDAR models. The intuition is that the voxel sizes we are using are small enough, such that the points within each grid have similar enough features and we can just randomly select one point within each grid. I've experimented with VFE around 1.5 years ago, and at that time I found there is no obvious improvement with this module. But when the voxel sizes are large (say, in pointpillars, where people usually use 0.2mx0.2m), I remember that VFE could have large impact (~2mAP) on the final performance.
