### ISSUE TITLE
No protocol specified

### ISSUE THREAD

**Issue by gubei1998** [mit-han-lab/bevfusion#358]
when I run the train,it will show like this:
     No protocol specified
     No protocol specified
     and then It will get stuck and not move, I I don't know what this problem is and how to solve it?

**Comment by kentang-mit** [comment]
Hi @gubei1998,

Would you mind adding a `-v` flag to your training command and see if there are some more specific error messages? I vaguely remember that I saw the same warning during my training runs which did not end up being stuck.

Best,
Haotian

**Comment by lixinghe1999** [comment]
@gubei1998 
From my experience, the reason can be the failure of multi-GPU processing, so please comment all the parallel-related code, for example dist.init() and then the test.py is ok.

**Comment by liuyuansheng624** [comment]
> when I run the train,it will show like this: No protocol specified No protocol specified and then It will get stuck and not move, I I don't know what this problem is and how to solve it?

can you sloved it? can you tell me how to slove?
