### ISSUE TITLE
Voxelization returned arguments/coordinates

### ISSUE THREAD

**Issue by antragoudaras** [mit-han-lab/bevfusion#361]
I am having difficulty interpreting the returned arguments of [self.voxelize(x)](https://github.com/mit-han-lab/bevfusion/blob/main/mmdet3d/models/fusion_models/bevfusion.py#L130) during LiDAR feature extraction. The first argument returned, feats, is the selected valid voxels originating from point clouds with shape (N, 5), where the first three dimensions refer to point coordinates and the last refers to timestamp differences as described by @kentang-mit  in issue #353 . However, I don't understand the coords argument with shape (N, 3). In which coordinate system do these 3 columns of each point/feature _N_ refer to? Additionally, in issue #285 , @kentang-mit  explicitly mentions that "both camera and LiDAR features are aligned in LiDAR-centric coordinate systems.

**Note that the voxelization in my case is carried out by the [hard_voxelize](https://github.com/mit-han-lab/bevfusion/blob/main/mmdet3d/ops/voxel/voxelize.py/#L55-L66) call invoked by the forward method of [self.encoders["lidar"]["voxelize"] ](https://github.com/mit-han-lab/bevfusion/blob/main/mmdet3d/models/fusion_models/bevfusion.py#L140) which is an object instance of [class Voxelization(nn.Module)](https://github.com/mit-han-lab/bevfusion/blob/main/mmdet3d/ops/voxel/voxelize.py/#L77).**

I would appreciate any assistance in resolving my concerns regarding the returned arguments of [self.voxelize(x)](https://github.com/mit-han-lab/bevfusion/blob/main/mmdet3d/models/fusion_models/bevfusion.py#L130), particularly in understanding the **coords** argument and the coordinate system it refers to.

**Comment by kentang-mit** [comment]
Hi @antragoudaras,

Yes the raw LiDAR coordinates are in the LiDAR-centric system. This is determined by the nuScenes dataset itself. For hard voxelize, we actually first quantize the coordinates with a voxel size of [0.075m, 0.075m, 0.2m]. After that we take an average across all features within each voxel grid. The final output coordinates are integers (`round(coords / [0.075, 0.075, 0.2])`).  The reason why we need voxelization is that the sparse convolution modules that extract features from the point cloud require the input points to have unique coordinates.
Best,
Haotian
