### ISSUE TITLE
Some problems about test

### ISSUE THREAD

**Issue by usugami** [mit-han-lab/bevfusion#365]
I know that BEV Fusion requires multiple GPUs such as A6000 to train the model in order to ensure sufficient computing power and memory. However, I want to know if the trained model can be deployed on a small computer such as Xavier NX.  If not, what is the minimum required configuration for it to run? Thanks a lot.

**Comment by YaqinLong** [comment]
I tried to train the bevfusion on Xavier NX, but it failed because out of memory.

**Comment by VeeranjaneyuluToka** [comment]
I was able to run the inference of camera or LiDAR alone models using 8GB memory GPU card but Camera+LiDAR failed to run in 8GB and ran successfully using 24GB GPU card. I think you can run camera+LiDAR model using 12 or 16GB memory GPU card also, however i have not tried.
