### ISSUE TITLE
In the 3D detection task, map.json is needed?

### ISSUE THREAD

**Issue by JinSeoung-Oh** [mit-han-lab/bevfusion#367]
Hi, first, thank for your wonderful work. 
Theses days I'm making a custom dataset and loader for 3D detection task not segmentation.
And as you know map.json in nuScenes dataset is so difficult to make.
When I analyzed your code, I noticed map.json is not needed when 3D detection task.
It just need to make info.pkl file, maybe
It is true? My understanding is right? 
If not, I have to assume that map.json is given?

Thank for your reading and sorry about my pool english.
Thanks!

**Comment by VeeranjaneyuluToka** [comment]
Hi, I am also training models with my own custom dataset without having map files for detection and i could train successfully. However i am yet to get good results.

**Comment by JinSeoung-Oh** [comment]
> Hi, I am also training models with my own custom dataset without having map files for detection and i could train successfully. However i am yet to get good results.

Oh, thanks!
Actually, I am also face with that problem...
Training without map files is possible, but result is so pool..
Maybe map files is used for filtering detected box, I guess.. Maybe not
Anyway, I really appreciate your comment. 
Have a nice day!

Thanks!
