### ISSUE TITLE
About the downloading of pre-trained weights

### ISSUE THREAD

**Issue by LiewFeng** [mit-han-lab/bevfusion#368]
Hi, @zhijian-liu , I use the link in download_pretrained.sh to download the weights in the browser, but obtain something strange and it doesn't donwload the weights. Could you give me some suggestions? Lots of thanks!
![image](https://user-images.githubusercontent.com/42316773/229505790-f230db60-606a-48ff-bf1d-d97ea594b668.png)

**Comment by kentang-mit** [comment]
I don't think binary weights could be directly parsed in a text editor. You may need to use `torch.load`.

**Comment by lee1221** [comment]
Hello, the official address for downloading the pre-training model of the project is invalid. If you download "bevfusion-det.pth" and "bevfusion-seg.pth", could you share it with my email address [185285659@qq.com], Wish you all the best in scientific research.
