### ISSUE TITLE
 execute download_pretrained.sh Error

### ISSUE THREAD

**Issue by liuliuliu11** [mit-han-lab/bevfusion#378]
Hi ,Thanks for your awesome paper and code!
When I run the script to download the model, I find that the web page is no longer accessible.
![image](https://user-images.githubusercontent.com/41572695/231402072-96beda54-c03f-4b30-9bdc-612d295ca7cd.png)

**Comment by BigGold0202** [comment]
Same problem, the home page of this project is not feasible too

**Comment by mohamed-ebbed** [comment]
I see that bevfusion.mit.edu is down

**Comment by flymin** [comment]
The website seems still not working. Can anyone share the downloaded weights?

**Comment by lcc815** [comment]
@flymin Could you please share the weights with us.
baidu net disk is ok.

**Comment by lcc815** [comment]
> @flymin Could you please share the weights with us. baidu net disk is ok.

or my email is ccong.li@qq.com. Thanks a lot!

**Comment by flymin** [comment]
> > @flymin Could you please share the weights with us. baidu net disk is ok.
> 
> or my email is [ccong.li@qq.com](mailto:ccong.li@qq.com). Thanks a lot!

I sent an email to you with the link, please check.

**Comment by kentang-mit** [comment]
Thanks for reporting this problem. It seems to be a problem impacting users in many countries (e.g. in Europe and China). A VPN in the US will be helpful, but I will definitely discuss with my labmates to see whether we can find a solution without proxy servers.

**Comment by kkrl1111** [comment]
I also need weight connections. Can you send me a copy? My email is iakrulan@wust.edu.cn ，Thank you！

**Comment by Mandylove1993** [comment]
I also need weight connections too. Can you send me a copy? My email is zhuft161@163.com，Thank you！ @flymin

**Comment by zhuliudanbao** [comment]
I also need weight connections too. Can you send me a copy? My email is charleyzhoucn@gmail.con，Thank you！ @flymin

**Comment by BoomSky0416** [comment]
I also need weight connections too. Can you send me a copy? My email is [shoutian@umich.edu](mailto:shoutian@umich.edu)，Thank you！ @flymin

**Comment by yukiser** [comment]
I also need weight connections too. Can you send me a copy? My email is 20173629@cqu.edu.cn，Thank you！ @flymin

**Comment by kentang-mit** [comment]
Hi folks, 

Feel free to have a look at [this](https://drive.google.com/drive/folders/1Jru7VTfgvFF949DlP1oDfriP3wrmOd3c?usp=sharing) Google drive link and see if it works for you. I heard that our department is updating its HTTP server so there might be some impact on our project websites. We are still waiting for their feedback.

Best,
Haotian

**Comment by Darkerok** [comment]
> > @flymin Could you please share the weights with us. baidu net disk is ok.
> 
> or my email is [ccong.li@qq.com](mailto:ccong.li@qq.com). Thanks a lot!

Could U plz share the weights with us? My email is 717376696@qq.com. Thanks a lot. We are still waiting for your feedback.

**Comment by zhijian-liu** [comment]
Please update your local repository, as we have moved all the checkpoints to Dropbox.
