### ISSUE TITLE
BEVFusion4d

### ISSUE THREAD

**Issue by RG2806** [mit-han-lab/bevfusion#379]
Hey,
I thoroughly enjoyed the paper on BEVFusion4D. Just wanted to know if the code related to the paper will be made public?
2303.17099.pdf (arxiv.org)

**Comment by hasaikeyQAQ** [comment]
这个是上汽的产品

**Comment by kentang-mit** [comment]
Hi folks,

Yes, it is not a paper from our team. I think it's definitely a great one and you may contact their authors for more information.

Best,
Haotian
