### ISSUE TITLE
Confusion transfusion_bbox_coder.py

### ISSUE THREAD

**Issue by parthmehta15** [mit-han-lab/bevfusion#384]
Hello I am trying to run the train model for a dataset which has fewer no. of classes:
(Can you provide some guidance as to how to do it)
Also:

File: 
bevfusion/mmdet3d/core/bbox/coders/transfusion_bbox_coder.py 
 Why is index 2 commented in the encoder function:

 `
 def encode(self, dst_boxes):
        targets = torch.zeros([dst_boxes.shape[0], self.code_size]).to(dst_boxes.device)
        targets[:, 0] = (dst_boxes[:, 0] - self.pc_range[0]) / (self.out_size_factor * self.voxel_size[0])
        targets[:, 1] = (dst_boxes[:, 1] - self.pc_range[1]) / (self.out_size_factor * self.voxel_size[1])
        **# targets[:, 2] = (dst_boxes[:, 2] - self.post_center_range[2]) / (self.post_center_range[5] - self.post_center_range[2])**
        targets[:, 3] = dst_boxes[:, 3].log()
        targets[:, 4] = dst_boxes[:, 4].log()
        targets[:, 5] = dst_boxes[:, 5].log()
        targets[:, 2] = dst_boxes[:, 2] + dst_boxes[:, 5] * 0.5  # bottom center to gravity center
        targets[:, 6] = torch.sin(dst_boxes[:, 6])
        targets[:, 7] = torch.cos(dst_boxes[:, 6])
        if self.code_size == 10:
            targets[:, 8:10] = dst_boxes[:, 7:]
        return targets

`

**Comment by kentang-mit** [comment]
Hi @ParthMehta15,

Sorry for the delayed response. I was busy with other projects recently. I think this line of code is implemented by Xuyang, the original author of TransFusion. No matter how the `targets` is implemented, as long as it is consistent with the box decoder, I think it is OK. 

Best,
Haotian
