### ISSUE TITLE
question about points

### ISSUE THREAD

**Issue by gubei1998** [mit-han-lab/bevfusion#386]
I am very sorry to bother you again，Still the problem with the previous points，The voxel module you mentioned earlier converts points into voxels and feeds them into the lidar network for processing, but after I debugged it, I found that before the points were voxelized, the format of the points was already a list, as
    138         ipdb.set_trace()
--> 139         feats, coords, sizes = [], [], []
    140         for k, res in enumerate(points):

ipdb> points
[tensor([[-4.9531, -0.1589, -1.2676, 15.0000,  0.0995],
        [ 1.5000,  0.3567,  0.8750,  0.0000,  0.0498],
        [ 1.3525,  0.1392,  0.8184,  1.0000,  0.3999],
        ...,
        [ 2.2617,  1.5859,  0.9717,  0.0000,  0.1996],
        [ 0.1449,  9.6719,  0.0618,  2.0000,  0.0000],
        [ 1.0498, -0.2321, -0.6211,  1.0000,  0.0498]], device='cuda:0'), tensor([[ -8.4688,   2.0137,  -1.5957,   4.0000,   0.1504],
        [  8.1016,  -0.6143,  -0.8906,   5.0000,   0.2505],
        [-17.2031,  12.4375,  -2.3789,   2.0000,   0.1504],
        ...,
        [  0.4233,  -4.9492,  -0.9219,  46.0000,   0.0503],
        [-14.8047, -15.8203,  -0.4553,  10.0000,   0.4004],
        [ -5.1758,  -2.5527,  -1.2520,   6.0000,   0.3506]], device='cuda:0')]
ipdb> len(points)
2
When I processed with other models I found that the points simply add up when the batchsize changes, for example, when batch=2, points=(400000+,5), not a list like in bevfusion, the shape is about [2,200000+.5], I just want to know the data of bevfusion How does the generation phase turn the input points into a list, and where is this module located? I hope to get your answer!

**Comment by kentang-mit** [comment]
Hi @gubei1998,

Sorry for the delayed response. I was busy with other projects recently. Yes, your understanding is correct about the batching mechanism for point clouds in this codebase. Actually the reason why we do not want create a [2, 200k, 5] tensor is that the number of points in different samples might have a large variance and we do not want to pad them to the same length. You can see that the batching mechanism is implemented [here](https://github.com/mit-han-lab/bevfusion/blob/db75150717a9462cb60241e36ba28d65f6908607/mmdet3d/models/fusion_models/bevfusion.py#L137).

Best,
Haotian
