### ISSUE TITLE
Project website is down

### ISSUE THREAD

**Issue by mohamed-ebbed** [mit-han-lab/bevfusion#389]
I can see that the website of the project bevfusion.mit.edu is down. It is causing also a problem when downloading the pretrained models.

**Comment by kentang-mit** [comment]
Hi @mohamed-ebbed,

Thanks for the information. We noticed that our project website and group website might not be accessible in some regions in the world. We are not sure about the reason, but it would be appreciated if you could try out an VPN to access our websites. Some of my friends living in other country reported that they can access our websites with a VPN.

Best,
Haotian
