### ISSUE TITLE
Question about fp32 implement

### ISSUE THREAD

**Issue by liyiheng0913** [mit-han-lab/bevfusion#395]
Thanks for open sourcing the BEVFusion! Recently I have been working on re-implementing the [code](https://github.com/mit-han-lab/bevfusion/blob/main/configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml) and have noticed that the difference in mAP between fp16 and fp32 can be more than 0.03.  And I found that the mAP of fp16 is better than fp32. I was wondering if you had any suggestions for implementing fp32 and if it would be possible for me to see the train log.

**Comment by kentang-mit** [comment]
Hi @liyiheng0913,

That's interesting to know. One potential reason is that we train the model with mixed precision. To train it entirely with FP32 you could add a `--fp16 None` flag to your command.

Best,
Haotian
