### ISSUE TITLE
Pretrain Model

### ISSUE THREAD

**Issue by liyiheng0913** [mit-han-lab/bevfusion#398]
Hello，I can't download the pretrain model in tools/download_pretrained.sh，is there any other way to download the pretrain model？

**Comment by qianqianqianqian** [comment]
Same question, could you provide bevfusion-L pre-trained model, I reproduce for a long time but get 0.6nds lower than reported.
And how about scaling up the MACs and image size experience, I try it but OOM(on 80g A100),  is there some solution?
Thanks a lot!

**Comment by atlantins** [comment]
Same question

**Comment by iyaqiao** [comment]
Same question,I also can't download the pretrain model !

**Comment by kentang-mit** [comment]
Hi folks, I mentioned [elsewhere](https://github.com/mit-han-lab/bevfusion/issues/305) that there is a small bug in the center of GT boxes. I ran some experiments after fixing this and I was able to get the reported results quite often.

**Comment by kentang-mit** [comment]
Regarding pretrained models, we noticed that our lab website was not accessible in some regions. You could try out VPNs to see whether it is possible to download these checkpoints. If it is still difficult, please send me an Email and I will try to send a copy to Google Drive.

**Comment by Mandylove1993** [comment]
> Regarding pretrained models, we noticed that our lab website was not accessible in some regions. You could try out VPNs to see whether it is possible to download these checkpoints. If it is still difficult, please send me an Email and I will try to send a copy to Google Drive.

Hello, can you share the Google Drive download link,？ I can't download it by “tools/download_pretrained.sh“ either，Thanks!!!

**Comment by kentang-mit** [comment]
Sorry for the delay. I just finished a conference deadline last week. Please have a look at [this link](https://drive.google.com/drive/folders/1Jru7VTfgvFF949DlP1oDfriP3wrmOd3c?usp=share_link) to download all the checkpoints.

**Comment by ldtho** [comment]
Hi @kentang-mit , I applied the fix in the GT box center ( origin=(0.5, 0.5, 0) to  origin=(0.5, 0.5, 0.5)), now can I use your checkpoint to evaluate, is it still compatible or do I need to re-train a new model? 
Thank you
