### ISSUE TITLE
How can I use my own images and point cloud data to run BEVFusion eval

### ISSUE THREAD

**Issue by Laobyy** [mit-han-lab/bevfusion#401]
I have my own dataset with calibrated LIDAR_TOP files and 6 cameras files
I want to keep all other data files as the same but replace the images and point cloud files into my own dataset
How can I change the data loader to load from the correct path and filenames when running the test.py

**Comment by kentang-mit** [comment]
Hi @Laobyy,

Yes you can do that. One simple way to do that is to reorganize your dataset info file similar to nuScenes. You could refer to [this file](https://github.com/mit-han-lab/bevfusion/blob/main/tools/data_converter/nuscenes_converter.py) about the expected fields in the info file. I believe as long as your dataset info file is in the same format as nuScenes, you should be able to reuse most of the dataset code from nuScenes.

Best,
Haotian
