### ISSUE TITLE
depth estimation - different from the paper

### ISSUE THREAD

**Issue by lixinghe1999** [mit-han-lab/bevfusion#402]
Dear author and people who are interested in this project.

From the paper: “we explicitly predict the discrete depth distribution of each pixel”, seems the depth is learned from rgb.
However, the implementation in "https://github.com/mit-han-lab/bevfusion/tree/main/mmdet3d/models/vtransforms/base.py" actually use points (from lidar) to get the depth.

**Comment by kentang-mit** [comment]
Hi @lixinghe1999,

Yes, your understanding is correct, but I need to point out that the depth-assisted LSS (DLSS) transformation implemented in this codebase actually does not provide notable performance improvement over the LSS baseline, and it is obviously less efficient. This is the reason why we only mention we use LSS in the paper.

Best,
Haotian

**Comment by TongNing-Albert** [comment]
> 

So why do you choose LSS to generate bev features in camera modality?

**Comment by kentang-mit** [comment]
Hi Tong,

The reason why we choose LSS is that it is much more efficient than other alternatives with a good CUDA implementation and the performance is decent.

Best,
Haotian
