### ISSUE TITLE
When will update the code exporting pytorch model to onnx?

### ISSUE THREAD

**Issue by shannon233** [mit-han-lab/bevfusion#406]
I want to export camera-only-seg model to onnx, but faild at bev pool. 

In other issue, I saw you are working on exporting model to onnx. Could you please give a about date when the export code will be public?

**Comment by kentang-mit** [comment]
Sorry for the delayed response. I cannot provide a clear timeline since I am recently switching to projects in other domain. But we do have a student actively working on that. If you have very urgent need please send me an Email and I will try getting some information from him.

**Comment by mikevian** [comment]
any chance there is a solution for exporting this model to ONNX ?
