### ISSUE TITLE
how to train model with multiple machine?

### ISSUE THREAD

**Issue by lcc815** [mit-han-lab/bevfusion#407]
Hi Haotian,

Sorry I am not familiar with torchpack, according README, by `torchpack dist-run -np 8 python tools/train.py` we can use 8 gpus in a single machine, and i want to ask is there any way to use 2 (or more) machines to train the model?

thanks,

**Comment by kentang-mit** [comment]
Hi @lcc815,

Thanks for the interest. I haven't tried training bevfusion on multiple machines. Maybe @zhijian-liu has more expertise on this topic. I remember that there are some prerequisites, for example you need to make sure that the path to the codebase is the same on all machines and you can connect to each machine from another one without inputing passwords. 

Best,
Haotian
