### ISSUE TITLE
Evaluation processing time

### ISSUE THREAD

**Issue by SMSajadi99** [mit-han-lab/bevfusion#409]
Hello
I'm testing the `evaluation `stage, but after downloading the checkpoint for Torch, it waits here and does nothing?
Is there a problem or should I really wait?

![image](https://github.com/mit-han-lab/bevfusion/assets/69210109/43649c1f-a53b-4c3f-b23d-4b79faa31e73)

**Comment by SMSajadi99** [comment]
![image](https://github.com/mit-han-lab/bevfusion/assets/69210109/28ae6b54-9b12-4a65-9a39-76574d84ba30)

![image](https://github.com/mit-han-lab/bevfusion/assets/69210109/a4eef752-b1c0-4d57-a92c-e9bc9b9020f3)

**Comment by SMSajadi99** [comment]
How much time is needed to do the evaluation?

**Comment by VanderBieu** [comment]
I had similar issue during evaluation. You can try reducing number of nodes by change `torchpack -np 8` to `torchpack -np 1` It works for me.
So it appears that the number of nodes must match the number of GPUs.

**Comment by SMSajadi99** [comment]
thanks so much
