### ISSUE TITLE
kitti

### ISSUE THREAD

**Issue by kkrl1111** [mit-han-lab/bevfusion#410]
Hello author, the Nuscenes dataset is too large for me. Is there a solution for kitti data？

**Comment by kentang-mit** [comment]
Hi @kkrl1111,

We haven't tried KITTI yet. However if you feel nuScenes is too large you may also downsample the dataset by 2X or 4X during training. According some of my collaborators the accuracy on the downsampled nuScenes could be quite indicative. Hope that will help.

Best,
Haotian
