### ISSUE TITLE
mAP are misaligned between the training phase and the standalone validation phase

### ISSUE THREAD

**Issue by shouxieai** [mit-han-lab/bevfusion#411]
Is anyone encounter this issue?

**Comment by kentang-mit** [comment]
Hi @shouxieai,

Yes, I encountered this issue. One of our collaborators reported that he could fix this issue by changing the `test_mode` to True (default is False [here](https://github.com/mit-han-lab/bevfusion/blob/db75150717a9462cb60241e36ba28d65f6908607/mmdet3d/datasets/nuscenes_dataset.py#L137)) during training phase validation. Maybe you can also have a try.

Best,
Haotian

**Comment by shouxieai** [comment]
Thanks, I also found that the **test_mode** setting was only used as the default value, but I didn't check it.
