### ISSUE TITLE
Lidar branch Network pretrained ckpt

### ISSUE THREAD

**Issue by imyyf** [mit-han-lab/bevfusion#414]
In cam branch, the model has pretrained ResNet ckpt. Why Lidar branch doesn't have/use pretrained ckpt.

**Comment by kentang-mit** [comment]
Hi @imyyf,

Actually we did not use ResNet pretraining for the camera branch. Instead we are using SwinT. For the LiDAR branch, if you are using the fusion model, we actually also utilized the pretrained LiDAR-only checkpoint (see README.md for instructions).

Best,
Haotian

**Comment by imyyf** [comment]
Thanks for your reply. 
Sorry for the wrong question about cam branch.
Actually, I'm curious about that.
We find that on cam branch it has pretrained ckpts for training.
But on lidar branch, it doesn't.
Is there any obstacle for lidar branch pretrained ckpts for training. Or it is trivial, need not do that.
