### ISSUE TITLE
Voxelization

### ISSUE THREAD

**Issue by RG2806** [mit-han-lab/bevfusion#423]
Hey there,

I wanted to know why was this line commented out 
https://github.com/mit-han-lab/bevfusion/blob/db75150717a9462cb60241e36ba28d65f6908607/mmdet3d/ops/voxel/voxelize.py#L119
the **[::-1]** part
when it's not in the official documentation
https://mmcv.readthedocs.io/en/latest/_modules/mmcv/ops/voxelize.html

**Comment by zhijian-liu** [comment]
This is because we are using a different coordinate system than `mmdetection3d`.
