### ISSUE TITLE
TTA and model ensembling

### ISSUE THREAD

**Issue by NoOneUST** [mit-han-lab/bevfusion#424]
Thank you for your great work. Did you provide any tutorial or code on how to do TTA and model ensembling? It seems that these techniques benefit the effectiveness a lot.

**Comment by jamesgunnfiveai** [comment]
I would be very interested in this information as well if it's able to be provided. Concrete questions I have about it are:
* Ablation of the TTA strategies (double flip, rotation, ensembling)
* Do you concatenate the different strategy classes or take the cartesian product?
* For your best nuScenes results did you use circlenms? Did you run the NMS on each class separately? If so, did you use class specific thresholds and what were they?

**Comment by zhijian-liu** [comment]
We follow the standard test-time augmentation, as many other methods on the leaderboard have done. We haven't released the implementation of this part yet. We have recently shifted focus to different research directions, so unfortunately, we don't have enough bandwidth to clean up the code for this.
