### ISSUE TITLE
LYFT - only CAM flow || boxes shifted in the output

### ISSUE THREAD

**Issue by mdfaheem786** [mit-han-lab/bevfusion#431]
Hi,

great work, with out transformers this code is build with amazing accuracies.

Just i was trying only CAMERA flow based fusion with LFYT dataset, notice there is a considerable shift in the boxes as attached in the sample output.  

Used loader for LYFT from mmdet3d and pretrianed weight of nuScenes - https://bevfusion.mit.edu/files/pretrained_updated/camera-only-det.pth

![image](https://github.com/mit-han-lab/bevfusion/assets/126733490/60b62c49-af3f-471b-8b7a-f76b55aa47fc)
![image](https://github.com/mit-han-lab/bevfusion/assets/126733490/d899f41b-3a01-43a1-8d3f-27b94be76188)
![image](https://github.com/mit-han-lab/bevfusion/assets/126733490/06748131-43ad-48f7-a0f1-b477337c014a)

**Comment by zhijian-liu** [comment]
I don't think the model would transfer across different datasets, which appears to be a common problem for 3D perception models. You probably need to retrain a model on Lyft.
