### ISSUE TITLE
Visualize NuScenes v1.0-test

### ISSUE THREAD

**Issue by kyle263** [mit-han-lab/bevfusion#432]
How can i use visualize.py to visualize the result of NuScenes v1.0-test?

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
