### ISSUE TITLE
About the Best Practice on TensorRT

### ISSUE THREAD

**Issue by hopef** [mit-han-lab/bevfusion#434]
Thanks for the excellent work of the author.

Recently we developed TensorRT inference for BEVFusion on the ORIN platform.  We solved several challenges(spconv/bevpool/int8 etc.) in BEVFusion, and we achieved excellent performance.

I would like to recommend our work here.
Repo: https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/tree/master/CUDA-BEVFusion

Best Regards,
Jingwei.

**Comment by zhijian-liu** [comment]
Wow! That's fantastic. Feel free to submit a PR to add a link to your repo in our README. Thanks!

**Comment by hopef** [comment]
I submitted PR at #462. Thanks!
