### ISSUE TITLE
nuScene trained weights for camera only || other dataset - LYFT, Waymo

### ISSUE THREAD

**Issue by mdfaheem786** [mit-han-lab/bevfusion#435]
Hi,

nice work which has fusion and separate flows - lidar and camera.

just wanted to know whether these nuScene weights will directly work on other dataset like LYFT and Waymo?

or need to trained again on those datasets ?

thank you in advance :)

**Comment by zhijian-liu** [comment]
I don't think the model would transfer across different datasets, which appears to be a common problem for 3D perception models.
