### ISSUE TITLE
KeyError: "BEVFusion: 'SwinTransformer is not in the models registry'"

### ISSUE THREAD

**Issue by adasfag** [mit-han-lab/bevfusion#436]
When I tried to run the train.py,this error ocurred,how can i do to handle with it?

**Comment by mdfaheem786** [comment]
hi,
you need to install mmdet package. pls check requirement and install all necessary packages.

**Comment by zhijian-liu** [comment]
Thanks @mdfaheem786! Yes, you need to install MMDetection with the right version (mentioned in our README).

**Comment by alletsr** [comment]
> When I tried to run the train.py,this error ocurred,how can i do to handle with it?

are you able to solve this
