### ISSUE TITLE
BEV Segmentation Map Scaling

### ISSUE THREAD

**Issue by MaekTec** [mit-han-lab/bevfusion#439]
Hi,
I saw that you are using the GlobalRotScaleTrans data augmentation, but why do you not scale the BEV ground truth map in the LoadBEVSegmentation class as well? Is it on purpose or did you just forget it? I think without the scaling, the features for the object detection are not 100% correctly aligned with the features for the map segmentation.

**Comment by quotation2520** [comment]
I was wondering the same thing, and I suppose LoadBEVSegmentation do the alignment by referencing "lidar_aug_matrix" via `lidar2global` and `map_pose`. If you can look into it yourself and give confirmation, it would be very helpful.

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
