### ISSUE TITLE
training interrupted unexpectedly

### ISSUE THREAD

**Issue by GHT0320** [mit-han-lab/bevfusion#441]
How can I continue training with partially trained weights after an unexpected program interruption, following two epochs of training for bevfusion?

**Comment by VeeranjaneyuluToka** [comment]
@GHT0320 , i think you can search for resume_from in config files and pass the trained .pth file path, so that it should be resumed from the epoch where it got stopped.

**Comment by zhijian-liu** [comment]
Thanks @VeeranjaneyuluToka!
