### ISSUE TITLE
Inference with lidar-only model

### ISSUE THREAD

**Issue by AV-adrian** [mit-han-lab/bevfusion#444]
I am trying to deploy the lidar-only model on ROS. Could someone provide instructions on what is required to perform lidar-only inference. I loaded the configuration for the lidar only model, but the test pipeline still includes the camera components. Am i doing something wrong here?

`
cfg.data.test.pipeline[0] 
{'type': 'LoadMultiViewImageFromFiles', 'to_float32': True}
`
`
cfg.data.test.modality
{'use_lidar': True, 'use_camera': True, 'use_radar': False, 'use_map': False, 'use_external': False}
`
config file: bevfusion/configs/nuscenes/det/transfusion/secfpn/lidar/voxelnet_0p075.yaml

**Comment by VeeranjaneyuluToka** [comment]
@AV-adrian, I had a discussion on this with author some time ago and he mentioned that there is no clear separation between Camera and LiDAR when we use them because of implementation redundancy, So i think your approach is  correct.
