### ISSUE TITLE
Questions about variants of models in the nuScenes test

### ISSUE THREAD

**Issue by zoomkinseok** [mit-han-lab/bevfusion#445]
Thank you for your exciting research.
You recorded the performance of three models BEVFusion-e, BEVfusion, and BEVfusion-base* on the nuScenes test set.
Can you tell me what improvements have been made to each of BEVFusion-e and BEVfusion-base*?

Best,
Minseok Joo

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
