### ISSUE TITLE
about nuscenes_converter.py calibration

### ISSUE THREAD

**Issue by SeungHwi0613** [mit-han-lab/bevfusion#446]
Thank you for your amazing work!

I want to use bevfusion with out input of ego_pose["translation"]
currently, I just change little bit of code so i use bevfusion only for detection.
I know lidar map based translation is benefit for detection ability. 
but i want to divide every map related information from this model.

In conclusion, I want to know how can i change nuscense_convert T(translation) equation?
Can you give me some inspiration for this? please i need your help.

**Comment by VeeranjaneyuluToka** [comment]
@SeungHwi0613 , Are you taking about the implementation of obtain_sersor2top(xx) function at line 295 in [nuscen](https://github.com/mit-han-lab/bevfusion/blob/main/tools/data_converter/nuscenes_converter.py)?
