### ISSUE TITLE
Implementation in CARLA

### ISSUE THREAD

**Issue by GoodarzMehr** [mit-han-lab/bevfusion#452]
Hi,

I would like to use the pre-trained BEVFusion model in a CARLA simulation for real-time map segmentation. I was wondering

a) would there be a significant performance degradation due to domain transfer that would require retraining the model? and

b) what is the best approach to implementing it in CARLA? I am considering either using MMDeploy or following something similar to the tools/test.py code, but not sure which is better.

Thanks!

**Comment by zhijian-liu** [comment]
I don't think that the pre-trained model would transfer well to CARLA directly due the significant domain shift. I would recommend collecting some data from CARLA simulation and fine-tune the model.
