### ISSUE TITLE
question about implementation under mmdetection3d

### ISSUE THREAD

**Issue by fatemehazimi990** [mit-han-lab/bevfusion#453]
Hi @kentang-mit 
Thanks for releasing the code for your great work! I was facing some issues training the model implementation under mmdetection3d (https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). I was wondeing if it would be relevant to discuss it here ... Thanka!

**Comment by zhijian-liu** [comment]
I would recommend creating an issue in the MMDetection3D repo. Feel free to keep us in the loop.
