### ISSUE TITLE
Question about pointcloud data.

### ISSUE THREAD

**Issue by avi9700** [mit-han-lab/bevfusion#457]
Hello, 
Thank you for your excellent job.

I have beginner's questions about pointcloud data.
In your config file, the sweeps_num of train_pipeline and test_pipiline is 9. 
That is, one current pointcloud and nine past pointcloud data(temporal pointcloud data) were used for training and testing. is that right?
My newbie's question is whether there is a difference in performance when using large number of pointcloud data(ex : multiple 64ch-lidar outputs) instead of using temporal pointcloud data.

**Comment by zhijian-liu** [comment]
Your understanding is correct. Having a denser LiDAR input from multiple sensors is definitely better than from multiple frames due to the synchronization.
