### ISSUE TITLE
create_data question

### ISSUE THREAD

**Issue by xiaopan999** [mit-han-lab/bevfusion#461]
![截屏2023-07-20 15 21 40](https://github.com/mit-han-lab/bevfusion/assets/43646121/0cceeeaf-78ec-48f0-b149-4c9c236c3cb1)
请问这种问题如何解决

**Comment by VeeranjaneyuluToka** [comment]
You need to provide location information while creating .pkl files if you are experimenting with your dataset.

**Comment by JSC1375** [comment]
> You need to provide location information while creating .pkl files if you are experimenting with your dataset.

I download nuscenes v1.0-mini and map expansion. After I run create_data.py by 
python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes
I find pkl file is named as like nuscenes_infos_train_radar.pkl and is not generated in bevfusion/data/nuscenes but bevfusion/nuscenes and finally create_data.py raise error for failing to find .pkl files. I change the name "nuscenes_infos_train_radar.pkl "  to "nuscenes_infos_train_radar.pkl"  and place them in bevfusion/data/nuscenes and rerun create_data.py, it works.

However, when I try to run 
torchpack dist-run -np 1 python tools/test.py configs/nuscenes/seg/fusion-bev256d2-lss.yaml pretrained/bevfusion-seg.pth --eval map
I get the same problem KeyError: 'location'. it would be highly appreciated if you could explain how to provide location information while creating .pkl files

**Comment by minje335park** [comment]
in line 192 of the nuscenes_converter.py, try to add this line 
        location = nusc.get(
            "log", nusc.get("scene", sample["scene_token"])["log_token"]
        )["location"]
In my case, it worked.

**Comment by quantumdotsss** [comment]
![image](https://github.com/mit-han-lab/bevfusion/assets/46307359/7c550d58-8b22-4c54-b863-88a83af6adf5)
I still get the error.
I think the location should be in the info dict. Is that right?

**Comment by Lewis-Lu** [comment]
> ![image](https://user-images.githubusercontent.com/46307359/259654616-7c550d58-8b22-4c54-b863-88a83af6adf5.png) I still get the error. I think the location should be in the info dict. Is that right?

Yes, `location` should be the key of the info.

**Comment by Excutioner** [comment]
> > ![image](https://user-images.githubusercontent.com/46307359/259654616-7c550d58-8b22-4c54-b863-88a83af6adf5.png) I still get the error. I think the location should be in the info dict. Is that right?
> 
> Yes, `location` should be the key of the info.

I've tried this,but there is another error

**Comment by Excutioner** [comment]
> > ![image](https://user-images.githubusercontent.com/46307359/259654616-7c550d58-8b22-4c54-b863-88a83af6adf5.png) I still get the error. I think the location should be in the info dict. Is that right?
> 
> Yes, `location` should be the key of the info.

I've tried this, but there is another error 
AttributeError: 'dict' object has no attribute 'in_range_bev'
How can I solve this? Thanks for help

**Comment by Excutioner** [comment]
> > ![image](https://user-images.githubusercontent.com/46307359/259654616-7c550d58-8b22-4c54-b863-88a83af6adf5.png) I still get the error. I think the location should be in the info dict. Is that right?
> 
> Yes, `location` should be the key of the info.
I've tried this
![1](https://github.com/mit-han-lab/bevfusion/assets/124240859/4c0ea0ce-a69a-4a4a-a89b-70702c9cfea7)
but there is another error 
AttributeError: 'dict' object has no attribute 'in_range_bev'
![2](https://github.com/mit-han-lab/bevfusion/assets/124240859/fda26d73-c555-4777-8461-4b6ef96d9ca3)
How can I solve this?Thanks for your help

**Comment by Qizhi697** [comment]
I got the same error. I wonder how to add 'location' information to the generated .pkl file.

**Comment by EpicGilgamesh** [comment]
@Qizhi697 Hi, did you managed to solve this issue?
