### ISSUE TITLE
Warning: could not find environment variable "-x"

### ISSUE THREAD

**Issue by wyf0414** [mit-han-lab/bevfusion#470]
![d8635101632299d332f53c2356f0384](https://github.com/mit-han-lab/bevfusion/assets/137131028/71690db9-266c-422a-90d6-a5abfde026fe)
When I execute the following code, an error occurs:
`torchpack dist-run -np 1 python tools/test.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml pretrained/bevfusion-det.pth --eval bbox`
May I ask how to solve it?
Due to memory issues, I am using the v1.0 mini dataset.
Thanks very much!

**Comment by catziyan** [comment]
I have the same problem, could you tell me how did you solve it ? thanks

**Comment by wyf0414** [comment]
> I have the same problem, could you tell me how did you solve it ? thanks

I I haven't found a solution yet.

**Comment by liuwanchangl** [comment]
请问您解决了吗？

**Comment by liuwanchangl** [comment]
Have you solved it yet?

**Comment by Jaywxy** [comment]
> No, I met this error when I used a 3090 GPU rented on AutoDL.[https://www.autodl.com/login?url=/market/list](url) Now I'm using the GPU of my own. And this error didn't occur. Maybe this error related to the AutoDL platform.

请问你最后有再尝试解决这个问题吗？我现在也遇到了一样的问题，弄了好久不知道怎么解决，实在不想改代码了，太麻烦了
