### ISSUE TITLE
mAP=0 when testing on Night data (per class mAP) 

### ISSUE THREAD

**Issue by MinkyoungCho** [mit-han-lab/bevfusion#471]
Hello,

I would like to ask the meaning of "mAP=0" when testing on night data.
When I test on original validation dataset, I get the following mAPs for some classes.
<img width="242" alt="image" src="https://github.com/mit-han-lab/bevfusion/assets/29696200/0be0a2f8-7451-45de-a0c3-1fff79c851ec">

However, when I test only on night dataset (filtered from original validation dataset, like #https://github.com/mit-han-lab/bevfusion/issues/139#issue-1378745190), I found some classes' AP values are 0. Does this mean that all the detection results for those classes are incorrect, or there was no object at all in the night dataset?
<img width="189" alt="image" src="https://github.com/mit-han-lab/bevfusion/assets/29696200/0369b6fb-8015-48e7-874c-c2b5e0a21f1b">

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
