### ISSUE TITLE
only one GPU was occupied

### ISSUE THREAD

**Issue by wulinaaa** [mit-han-lab/bevfusion#472]
When training, I run: torchpack dist-run -np 2 python tools/train.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml --model.encoders.camera.backbone.init_cfg.checkpoint pretrained/swint-nuimages-pretrained.pth --load_from pretrained/lidar-only-det.pth --run-dir output/bev_result/
I looked at the GPU usage and found that only one GPU was occupied, how do I make the other piece also occupied.

**Comment by quantumdotsss** [comment]
> When training, I run: torchpack dist-run -np 2 python tools/train.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml --model.encoders.camera.backbone.init_cfg.checkpoint pretrained/swint-nuimages-pretrained.pth --load_from pretrained/lidar-only-det.pth --run-dir output/bev_result/ I looked at the GPU usage and found that only one GPU was occupied, how do I make the other piece also occupied.

Hi Have you solved the problem? It seems I'm using the CPU rather than the GPU...

**Comment by quantumdotsss** [comment]
I'm facing the same issue now. Have you solved this?
![Screenshot from 2023-08-06 22-37-54](https://github.com/mit-han-lab/bevfusion/assets/46307359/e47a8410-f159-48c2-95ff-95766fb5c847)

**Comment by quantumdotsss** [comment]
> I'm facing the same issue now. Have you solved this? ![Screenshot from 2023-08-06 22-37-54](https://user-images.githubusercontent.com/46307359/258709326-e47a8410-f159-48c2-95ff-95766fb5c847.png)

vram, I think

**Comment by wulinaaa** [comment]
> > 我现在面临同样的问题。你解决了这个问题吗？![截图来自 2023-08-06 22-37-54](https://user-images.githubusercontent.com/46307359/258709326-e47a8410-f159-48c2-95ff-95766fb5c847.png)
> 
> 弗拉姆，我想

I think the memory was not freed when running torchpack before. I first looked at the GPU usage and found that there was a process that kept taking up memory, so I killed it. But killing it remains. Then I'll reboot just fine.
