### ISSUE TITLE
Question about TTA

### ISSUE THREAD

**Issue by liyiheng0913** [mit-han-lab/bevfusion#473]
Hi, thank you for your excellent work. Can you provide the code on how to do TTA and model ensembling?
Thanks very much!

**Comment by zhijian-liu** [comment]
We follow the standard test-time augmentation, as many other methods on the leaderboard have done. We haven't released the implementation of this part yet. We have recently shifted focus to different research directions, so unfortunately, we don't have enough bandwidth to clean up the code for this
