### ISSUE TITLE
Lidar SCN ONNX load fails with error in libprotobuf

### ISSUE THREAD

**Issue by sandeepnmenon** [mit-han-lab/bevfusion#474]
I exported the pretrained model for bevfusion using `qat/export-scn.py` and when trying to load it in cpp at
```cpp
    native_scn_ = spconv::load_engine_from_onnx(param_.model, static_cast<spconv::Precision>(param_.precision));
```
I get the error
```bash
[libprotobuf FATAL /usr/include/google/protobuf/repeated_field.h:1506] CHECK failed: (index) < (current_size_): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (index) < (current_size_): 
tool/run.sh: line 43: 350002 Aborted                 (core dumped) ./build/bevfusion $DEBUG_DATA $DEBUG_MODEL $DEBUG_PRECISION
```

My libprotobuf dev version is `3.6.1.3-2ubuntu5.2`, so it is 3.6.1 as mentioned in other issues as resolution for protobuf errors.
Requesting help on this

**Comment by zhijian-liu** [comment]
We currently do not support exporting the model to ONNX, but it is under consideration for future updates.
