### ISSUE TITLE
TypeError: CyclicLrUpdaterHook: __init__() got an unexpected keyword argument 'min_lr_ratio

### ISSUE THREAD

**Issue by quantumdotsss** [mit-han-lab/bevfusion#479]
Hi there,
I've run into this problem.
![Screenshot from 2023-08-05 23-05-21](https://github.com/mit-han-lab/bevfusion/assets/46307359/d912095e-6cbd-41e8-a60d-d39bc94f6259)
I check the default.yaml and there is no min_lr_ratio
but the log file has that
lr_config = dict(
    policy='cyclic',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.33333333,
    min_lr_ratio=0.001,
    target_ratio=5.0,
    cyclic_times=1,
    step_ratio_up=0.4)

where is the wrong part? torchpack?

**Comment by Ricardolyg** [comment]
这个好像是权限问题，得把bevfusion项目放在当前用户目录下的任意文件夹

**Comment by quantumdotsss** [comment]
> 这个好像是权限问题，得把bevfusion项目放在当前用户目录下的任意文件夹
you are right....

**Comment by quantumdotsss** [comment]
> 这个好像是权限问题，得把bevfusion项目放在当前用户目录下的任意文件夹

NO. It's a learning ratio

**Comment by Anna1ximi** [comment]
I simply delete the '**min_lr_ratio: 1.0e-3**' in **configs/nuscenes/det/centerhead/lssfpn/default.yaml** and it works.

**Comment by quantumdotsss** [comment]
> @quantumdotsss I simply delete the '**min_lr_ratio: 1.0e-3**' in **configs/nuscenes/det/centerhead/lssfpn/default.yaml** and it works.

yeap!
