### ISSUE TITLE
About training strategy

### ISSUE THREAD

**Issue by JamesHao-ml** [mit-han-lab/bevfusion#48]
Thanks for open-sourcing the awesome work! I am trying to reproduce the performances and would like to know the training strategy:

1. The lidar encoder is first trained following the steps in Transfusion. 
2. The image encoder is from SwinTransformer. 
3. Load the pre-trained lidar encoder and image encoder, **randomly initialize GeneralizedLSSFPN, DepthLSSTransform, ConvFuser** and **finetune all parameters**.

Is this the correct way to train BEV fusion？

**Comment by kentang-mit** [comment]
That's correct. We'll release the details in the future.

**Comment by jqfromsjtu** [comment]
> Thanks for open-sourcing the awesome work! I am trying to reproduce the performances and would like to know the training strategy:
> 
> 1. The lidar encoder is first trained following the steps in Transfusion.
> 2. The image encoder is from SwinTransformer.
> 3. Load the pre-trained lidar encoder and image encoder, **randomly initialize GeneralizedLSSFPN, DepthLSSTransform, ConvFuser** and **finetune all parameters**.
> 
> Is this the correct way to train BEV fusion？

Hi! How's your training? Did you get some results? I'm wondering that in the fine-tuning part, some parts are pretrained and some parts are randomly initialized, so will it lead to even worse performance if using the same lr for all? Since pretrained parts ought to use a small lr to finetune.
