### ISSUE TITLE
radars_dict = results['radar']

### ISSUE THREAD

**Issue by quantumdotsss2** [mit-han-lab/bevfusion#481]
![Screenshot from 2023-08-06 01-56-46](https://github.com/mit-han-lab/bevfusion/assets/73956832/d8902874-3351-4699-b8b9-d94a396bd7d5)
Hi guys,
I've been stuck on this for a while. Is this because of the creat_data.py? I have the same issue as #480
I install the original mmdet3D to create the tran_info.pkl and rerun the create_date.py under perfusion to solve this. But I was stuck on the radar...

Thanks for the help.

**Comment by MaxLeo-LMZ** [comment]
https://github.com/mit-han-lab/bevfusion/issues/480#issuecomment-1667112241
