### ISSUE TITLE
missing pth file for LiDAR-based segmentation

### ISSUE THREAD

**Issue by Provemj** [mit-han-lab/bevfusion#482]
running
`torchpack dist-run -np 8 python tools/train.py configs/nuscenes/seg/lidar-centerpoint-bev128.yaml`
get
`OSError: ./pretrained/mae_lidar.pth is not a checkpoint file`
so, where is the
`load_from: ./pretrained/mae_lidar.pth`
in lidar-centerpoint-bev128.yaml

**Comment by zhijian-liu** [comment]
LiDAR-based segmentation doesn't require any pre-training, so you can safely remove this from the configuration.
