### ISSUE TITLE
'dict' object has no attribute 'rotate'

### ISSUE THREAD

**Issue by quantumdotsss** [mit-han-lab/bevfusion#483]
![image](https://github.com/mit-han-lab/bevfusion/assets/46307359/de396d9b-2960-4cc3-8ba9-a7dae6ee3942)
This happens when I run:
torchpack dist-run -np 1 python tools/train.py configs/nuscenes/seg/fusion-bev256d2-lss.yaml --model.encoders.camera.backbone.init_cfg.checkpoint pretrained/swint-nuimages-pretrained.pth

Thanks for the help.

**Comment by heli223** [comment]
i encounter the same issue

**Comment by Charlie0804** [comment]
I'm also having the same issue, would like to ask if you solved it

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
