### ISSUE TITLE
can't use np>1

### ISSUE THREAD

**Issue by Anna1ximi** [mit-han-lab/bevfusion#484]
**When I run the command:** torchpack dist-run -np 4 python tools/train.py \
	configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml \
	--model.encoders.camera.backbone.init_cfg.checkpoint pretrained/swint-nuimages-pretrained.pth \
	--load_from pretrained/lidar-only-det.pth \
	--run-dir output/bev_result/
**I get this problem:**
![image](https://github.com/mit-han-lab/bevfusion/assets/119270577/40259447-950f-4829-b137-182d6c391bc5)
**And when I want to train the camera-only variant for object detection, I get this:**
![image](https://github.com/mit-han-lab/bevfusion/assets/119270577/66a49caf-7a54-4418-944a-2ded647110c7)
![image](https://github.com/mit-han-lab/bevfusion/assets/119270577/1fd57363-f70b-444b-ae40-4f32f79dd2a7)
**Does anyone know how to fix it？Thanks！**

**Comment by quantumdotsss** [comment]
I think you need to provide more error info

**Comment by VanderBieu** [comment]
the number of np must match the number of gpus.

**Comment by Anna1ximi** [comment]
That's all the information, only a few lines. @quantumdotsss

**Comment by Anna1ximi** [comment]
I know,  I adhere strictly to this point,  but it always goes wrong. @VanderBieu

**Comment by enhuima** [comment]
same question.

**Comment by Anna1ximi** [comment]
> same question.

I started with the environment configuration all over again and it worked.

**Comment by ChirsHuanhuan** [comment]
<img width="803" alt="3b1632720ae0a57b05736c6742e3c27" src="https://github.com/mit-han-lab/bevfusion/assets/141637974/e0c4fcaf-1f0c-49fa-bea2-989878d48085">
same question when I run the test.py 
error: address already use

**Comment by huzhihen** [comment]
> <img alt="3b1632720ae0a57b05736c6742e3c27" width="803" src="https://user-images.githubusercontent.com/141637974/276514844-e0c4fcaf-1f0c-49fa-bea2-989878d48085.png"> same question when I run the test.py error: address already use

Hello, I have also encountered this problem. Have you resolved it?
