### ISSUE TITLE
location = data["location"]

### ISSUE THREAD

**Issue by quantumdotsss** [mit-han-lab/bevfusion#485]
![image](https://github.com/mit-han-lab/bevfusion/assets/46307359/19d8251e-eccf-4109-b798-aeb5fd3e5f1f)
Hi guys,
This error comes when I was running 
torchpack dist-run -np 1 python tools/train.py configs/nuscenes/seg/lidar-centerpoint-bev128.yaml

I have the **pip install setuptools==59.5.0** from a previous issue but it still doesn't work.
I think this is the data creation problem.
Thanks for the help.

**Comment by Rxdem** [comment]
hello, I also had this error. 
You can verify whether your have correctly execute the "./tools/download_pretrained.sh"
