### ISSUE TITLE
'dict' object has no attribute 'rotate'

### ISSUE THREAD

**Issue by quantumdotsss** [mit-han-lab/bevfusion#491]
![image](https://github.com/mit-han-lab/bevfusion/assets/46307359/20ca3cd6-9850-4a81-8533-0b0a7cda9782)
Hi guys,
I would like to know how the radar data is used.
![image](https://github.com/mit-han-lab/bevfusion/assets/46307359/f3dd1785-10cd-4536-9bff-8bc59a50f1e3)
from the figure of the paper, I didn't see the usage of ladar
![image](https://github.com/mit-han-lab/bevfusion/assets/46307359/674b8de1-c6d3-4f42-bd4a-b7b7ffa66f13)
So I think I can just comment those lines.
Am I right.
This happens when I was running 
torchpack dist-run -np 1 python tools/train.py configs/nuscenes/seg/fusion-bev256d2-lss.yaml --model.encoders.camera.backbone.init_cfg.checkpoint pretrained/swint-nuimages-pretrained.pth

**Comment by Charlie0804** [comment]
I'm also having the same issue, would like to ask if you solved it

**Comment by zhijian-liu** [comment]
Feel free to comment out the code related to radar if you are only working on lidar-only, camera-only, or camera-lidar fusion models.
