### ISSUE TITLE
May I know the release time of waymo config 

### ISSUE THREAD

**Issue by RaymondByc** [mit-han-lab/bevfusion#493]
may i know the rough releasing time about waymo config?

You developed a awesome projects, which win the waymo challenge. However, when I want to reproduce the results, there are some problems I can not solve, In specific, I want to know how to process the missing part of camera images, padding with zero?

**Comment by zhijian-liu** [comment]
Thanks for your interest in our project. We have recently switched gear to work on different research directions, so unforuntately we don't have enough bandwidths to clean up the code for Waymo.
