### ISSUE TITLE
About Swin-T

### ISSUE THREAD

**Issue by wulinaaa** [mit-han-lab/bevfusion#495]
Hi, in the backbone folder, I did not see the code for swin-t. How did you use swin-t as the backbone to extract features

**Comment by liyih** [comment]
mmdet has swin-t, we can quickly init swin-t by define type = 'mmdet.SwinTransformer' in the config.
For the code of swin-t, look at https://github.com/open-mmlab/mmdetection/blob/main/mmdet/models/backbones/swin.py.
