### ISSUE TITLE
I want to know the meaning of 'sensor2lidar', 'camera2lidar' parameter

### ISSUE THREAD

**Issue by SeungHwi0613** [mit-han-lab/bevfusion#498]
Now, i develop this repo to fit on real-time ROS2 detection. In this process, I have one question about 'sensor2lidar' parameter.
I'm using the 'yaml' file as a parameter file instead of 'pkl'. I copy the content related with calibration of 'pkl' and paste it to 'yaml'. And it is working well still. But as you know, this 'camera2lidar' value is related with 'sensor2lidar' and this value is related with 'ego coordinate'. I want to get external calibration parameter of 'camera' and 'lidar' directly without any information of ego and put in my own 'yaml' file. 

So, I guess 'camera2lidar' is defining 'camera' rotation and translation based on 'lidar coordinate system' . I want to know this understanding is correct or not.

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
