### ISSUE TITLE
Is it practical to apply BEVFusion to KITTI dataset?

### ISSUE THREAD

**Issue by qnH6** [mit-han-lab/bevfusion#50]
Hi, thanks for open-sourcing this awesome work.
I wonder if it's possible to apply this project to KITTI dataset?
Does the method still work well when using only 1 camera?

**Comment by kentang-mit** [comment]
We haven't tried out the KITTI dataset yet. As far as I know KITTI performs evaluation in the camera FoV, so I think BEVFusion should still be able to work even if there is only 1 camera.
