### ISSUE TITLE
Wrong Visualization on Training Set

### ISSUE THREAD

**Issue by NoOneUST** [mit-han-lab/bevfusion#502]
I can generate correct visualizations on validation and testing sets, but the results are wrong on training sets.

![1526915243047392-f9878012c3f6412184c294c13ba4bac3](https://github.com/mit-han-lab/bevfusion/assets/48406286/1f035aab-6998-4f98-97db-c0bbef0702b8)
![1526915251397102-366efab9d8e4475e9a5f28c7ae7850f7](https://github.com/mit-han-lab/bevfusion/assets/48406286/6dd59aeb-7373-46d5-919b-714e2202ca55)

The code I use is the stable branch.

These two images are the gt and pred results on the training set. I have confirmed that this error impacts all images in the training set.

**Comment by Anna1ximi** [comment]
@NoOneUST  Hey! I want to know how you modified visualize.py for visualization. I have been stuck on this question for days. Thanks!

**Comment by sangjinpark97** [comment]
I'm not author or contributor of this project.

In my opinion, it seems to be related to data augmentation. Training data is processed by specific pipeline which contains augmentation.
