### ISSUE TITLE
Nuscenes detection errors on validation set

### ISSUE THREAD

**Issue by donand** [mit-han-lab/bevfusion#505]
Hello! Thanks for the great work!

Could you please share what errors you get for Nuscenes detection on the validation set? By errors, I mean mATE, mASE, mAOE, mAVE, mAAE.

Thank you!

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
