### ISSUE TITLE
SECOND format

### ISSUE THREAD

**Issue by Jayden9912** [mit-han-lab/bevfusion#506]
Anyone know the position and orientation of the coordinate system used by SECOND format?

Thank you.

**Comment by heli223** [comment]
i am also confused about the transformation in nuscenes_converter.py/_fill_trainval_infos. why we should use  -rots - np.pi / 2? the original rot is in which coordinate system?
            # we need to convert rot to SECOND format.
            gt_boxes = np.concatenate([locs, dims, -rots - np.pi / 2], axis=1)

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
