### ISSUE TITLE
How to convert a trained model to onnx

### ISSUE THREAD

**Issue by YueSun0609** [mit-han-lab/bevfusion#508]
Thank you for your kind release of the codes, I have successfully applied it to my own data and got good performace. But may I ask how to export a trained model to onnx format? In tools/export.py, you gave an example but missing "forward_test" function. I tried to write one, but when I run torch.onnx.export() function, it meets an error like "RuntimeError: Tracer cannot infer type of [{'boxes_3d': LiDARInstance3DBoxes", could you give me some clues on how to solve this issue? Thank you so much!

**Comment by ueke616** [comment]
I got the same error, can anyone give some solution? thanks

**Comment by zhijian-liu** [comment]
We currently do not support exporting the model to ONNX, but it is under consideration for future updates.
