### ISSUE TITLE
Location key not present in main branch

### ISSUE THREAD

**Issue by CSautier** [mit-han-lab/bevfusion#514]
Hi,

I believe there is an issue on the main branch in nuscenes_converter.py, as it does not prepare the "location" key (see https://github.com/mit-han-lab/bevfusion/blob/main/tools/data_converter/nuscenes_converter.py#L192).
However the "location" key was present in a [previous version](https://github.com/mit-han-lab/bevfusion/blob/db75150717a9462cb60241e36ba28d65f6908607/tools/data_converter/nuscenes_converter.py#L193).

As the code is in the main branch, the segmentation pipeline is not running as we lack this key and it is required in https://github.com/mit-han-lab/bevfusion/blob/main/mmdet3d/datasets/pipelines/loading.py#L294

**Comment by zhijian-liu** [comment]
Thank you reporting this issue. Could you please submit a short PR for this? Thanks!

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
