### ISSUE TITLE
pretrained model checkpoint link not work

### ISSUE THREAD

**Issue by Zeus233** [mit-han-lab/bevfusion#516]
Hi,

Thanks for the great work (I was actually able to reproduce your map segmentation evaluation on nuScenes).

It appears the links for the checkpoints no longer work. Would it be possible to provide new links so that we can build upon this project again?

**Comment by zhijian-liu** [comment]
Please use `hanlab18.mit.edu` in place of `hanlab.mit.edu` in the link as a temporary solution.
