### ISSUE TITLE
why downsample factor assertion?

### ISSUE THREAD

**Issue by zhaowenZhou** [mit-han-lab/bevfusion#520]
In the image branch, the downsample factor of image neck is asserted to 2 after dtransform and depthnet. But why? 
If I changed the lidar voxel size and grid size the bev feature map size will change so the image bev feature map size should be changed accordingly. 
I understand I can do that through changing xbound, ybound, but I can also do that througn changing downsample factor, so why is it set to be a fixed number?

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
