### ISSUE TITLE
Pre train link is invalid

### ISSUE THREAD

**Issue by ChirsHuanhuan** [mit-han-lab/bevfusion#526]
https://hanlab.mit.edu/projects/bevfusion/files/pretrained_updated/bevfusion-det.pth
This link is invalid makes the bevfusion-det.pth undowloadble.

**Comment by zhijian-liu** [comment]
Please use `hanlab18.mit.edu` in place of `hanlab.mit.edu` in the link as a temporary solution.

**Comment by ChirsHuanhuan** [comment]
Thanks for your timely reply!
