### ISSUE TITLE
Primary job  terminated normally, but 1 process returned

### ISSUE THREAD

**Issue by ChirsHuanhuan** [mit-han-lab/bevfusion#527]
![Uploading image.png…]()
When I ran the single-card test, it was normal, but when I ran the multi-card test, this problem occurred and no error was reported. Do you know how to solve it?

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
