### ISSUE TITLE
How to debug train.py through vscode?

### ISSUE THREAD

**Issue by lrbob** [mit-han-lab/bevfusion#529]
如何使用"./vscode/launch.json"
 debug train.py代码？

{
"version": "0.2.0",
"configurations": [

      {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "console": "integratedTerminal",
            "args": [
                "--np","2",
                "tools/train.py",
            ],
            "env": {"CUDA_VISIBLE_DEVICES":"0,1"},

             "program": "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py",
      }
    ]
}
这样设置以后运行debug还是提示KeyError: 'MASTER_HOST'
![123](https://github.com/mit-han-lab/bevfusion/assets/96453822/bc70dffa-0093-45c8-8fce-7d0bc5984363)
![124](https://github.com/mit-han-lab/bevfusion/assets/96453822/79e6fc58-f5f6-46b2-82f2-c30924385071)

**Comment by chfyyds** [comment]
I also encountered the same problem in pycharm. Did you solve it?

**Comment by lrbob** [comment]
> I also encountered the same problem in pycharm. Did you solve it?

oh yes, run command on the current bevfusion env terminal:
"export MASTER_HOST=your ipv4 address : a port number not used"
