### ISSUE TITLE
When training: FileNotFoundError: [Errno 2] No such file or directory: 'data/nuscenes/nuscenes_infos_train.pkl'

### ISSUE THREAD

**Issue by viborgen** [mit-han-lab/bevfusion#535]
When trying to train I get the following error. The file is there. What can I do?

FileNotFoundError: [Errno 2] No such file or directory: 'data/nuscenes/nuscenes_infos_train.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 87, in <module>
    main()
  File "tools/train.py", line 66, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/cvrr/bevfusion2/mmdet3d/datasets/builder.py", line 38, in build_dataset
    dataset = CBGSDataset(build_dataset(cfg["dataset"], default_args))
  File "/cvrr/bevfusion2/mmdet3d/datasets/builder.py", line 42, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: NuScenesDataset: [Errno 2] No such file or directory: 'data/nuscenes/nuscenes_infos_train.pkl'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[755,1],7]
  Exit code:    1

**Comment by iyaqiao** [comment]
I have the same problem, how do you solve it
