### ISSUE TITLE
Can I get your pre-trained model for R+C?

### ISSUE THREAD

**Issue by geonhobang** [mit-han-lab/bevfusion#536]
Can I get your pre-trained model for R+C?

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
