### ISSUE TITLE
question about depthss

### ISSUE THREAD

**Issue by yu8ri1** [mit-han-lab/bevfusion#537]
https://github.com/mit-han-lab/bevfusion/blob/531bf67dd56192cf1cff7baf2995312efdba1ea9/mmdet3d/models/vtransforms/base.py#L295C1-L298C39

https://github.com/mit-han-lab/bevfusion/blob/531bf67dd56192cf1cff7baf2995312efdba1ea9/mmdet3d/models/vtransforms/base.py#L92C19-L92C22

I would like to know more about the functionality of these two links: what is entered into the variable dist in the first link, and more about the functionality of the function in the second link.

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
