### ISSUE TITLE
how to adapt to custom datasets

### ISSUE THREAD

**Issue by heli223** [mit-han-lab/bevfusion#539]
If I have a custom datasets and we assume it has the same data format with nuscenes. 

How to adapt the commands （including create data， training， and testing）to custom datasets?   Can you give me detailed commands example?

By the way, i am confused about the yaml file in config directory. The YAML files appear to be nested hierarchically. Is it possible give some explanation? Thanks a lot!

**Comment by zhijian-liu** [comment]
Adding support for a custom dataset is beyond the scope of this codebase, and unfortunately, we don't have the capacity to accommodate such customized requests.
