### ISSUE TITLE
Questions about Camera + Radar

### ISSUE THREAD

**Issue by Terencedu** [mit-han-lab/bevfusion#541]
Hi,

Thanks for your great job!

Could you release the code of training camera+radar and the pretrained model of radar?

Additionally, #449 would comment some code about feature_decorator, would it affect radar feature extraction?

Best wishes!

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
