### ISSUE TITLE
Evaluation of Lidar-only model works, but Camera-only fails

### ISSUE THREAD

**Issue by Terencedu** [mit-han-lab/bevfusion#542]

**Comment by Terencedu** [comment]
Hi,

My GPU is one 4060(laptop, 8GB). Cuda version: 11.8

Environment:
mmcv-full = 1.4.0
mmdet = 2.20.0
mmdet3d = 0.0.0
nuscenes-devkit = 1.1.10
torch = 1.9.1+cu111

When I use "torchpack dist-run -np 1 python tools/test.py configs/nuscenes/det/transfusion/secfpn/lidar/voxelnet_0p075.yaml pretrained/lidar-only-det.pth --eval bbox" to evaluate the lidar-only model, it works:
![lidar-only](https://github.com/mit-han-lab/bevfusion/assets/102672687/5552cf38-cfdd-43ac-bfdf-7d2face9de0e)

However, when I use "torchpack dist-run -np 1 python tools/test.py configs/nuscenes/det/centerhead/lssfpn/camera/256x704/swint/default.yaml pretrained/camera-only-det.pth --eval bbox" to evaluate the camera-only model, it fails:
![camera-only](https://github.com/mit-han-lab/bevfusion/assets/102672687/3ae4626c-a7d6-4a90-affe-375e17ae76f6)

Is this an environment version issue or OOM issue?

Best wishes!

**Comment by Terencedu** [comment]
It was an environmental problem, and now it is solved. Thanks.

**Comment by BeMuCa** [comment]
@Terencedu  How did you solve the Issue? I have the exact opposite, Image worked, Lidar is failing with the same error handle
