### ISSUE TITLE
bevfusion-det.pth. not found

### ISSUE THREAD

**Issue by nican2018** [mit-han-lab/bevfusion#544]
Hello. 
I'm trying to evaluate bevfusion but the bevfusion-det.pth is not found. Can someone send a directory that contains the pre-trained. Even this page not found https://hanlab.mit.edu/projects/bevfusion/files/pretrained_updated/bevfusion-det.pth.

Thanks

**Comment by viborgen** [comment]
Hi! This worked for me
https://hanlab18.mit.edu/projects/bevfusion/files/pretrained_updated/bevfusion-det.pth
