### ISSUE TITLE
Question about `score_threshold` in centernet head config

### ISSUE THREAD

**Issue by fligit** [mit-han-lab/bevfusion#545]
In config file here:
https://github.com/mit-han-lab/bevfusion/blob/531bf67dd56192cf1cff7baf2995312efdba1ea9/configs/nuscenes/det/centerhead/default.yaml#L23
and 
https://github.com/mit-han-lab/bevfusion/blob/531bf67dd56192cf1cff7baf2995312efdba1ea9/configs/nuscenes/det/centerhead/default.yaml#L49

The `score_threshold` is set to `0.1`

Does it mean when you run the evaluation to compute mAP metric, the results come from boxes with score > 0.1? That is, your mAP is not computed with all predictions? (which means you could be losing some small area from the high recall part)

**Comment by zhijian-liu** [comment]
This is correct.
