### ISSUE TITLE
About Training Strategies

### ISSUE THREAD

**Issue by lhcezx** [mit-han-lab/bevfusion#550]
Hi, I'd like to ask the question about the training strategy, As I am using both mmdetection3d and openpcdet frameworks and both found in it that they require to train the lidar branch without pre-training model first, then train the whole bevfusion model after loading the pre-training model of the image and trained lidar model, as I didn't find too much training related content in the paper, may I ask if this is the case with your original training strategy?

**Comment by zhijian-liu** [comment]
This is exactly the training pipeline we have used.
