### ISSUE TITLE
Training with torchpack is unresponsive

### ISSUE THREAD

**Issue by 1180100407** [mit-han-lab/bevfusion#551]
I followed the instructions in the readme but there is no output, the problem seems to be with the torchpack but I don't know how to fix it, using "torchpack dist-run -np 1" doesn't produce any output either, and I've waited for at least 10 minutes.

**Comment by alexzhuuuu** [comment]
Same problem. What's the reason? I tried to run it without torchpack, and just python the test.py file.

**Comment by alexzhuuuu** [comment]
> I followed the instructions in the readme but there is no output, the problem seems to be with the torchpack but I don't know how to fix it, using "torchpack dist-run -np 1" doesn't produce any output either, and I've waited for at least 10 minutes.
Same problem. What's the reason? I tried to run it without torchpack, and just python the test.py file.

**Comment by alexzhuuuu** [comment]
> I followed the instructions in the readme but there is no output, the problem seems to be with the torchpack but I don't know how to fix it, using "torchpack dist-run -np 1" doesn't produce any output either, and I've waited for at least 10 minutes.

Same problem. What's the reason? I tried to run it without torchpack, and just python the test.py file.

**Comment by Lawrence-Cheung** [comment]
I met another problem like below:

Traceback (most recent call last):
  File "C:\Users\18369\.conda\envs\bevfusion\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\18369\.conda\envs\bevfusion\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\18369\.conda\envs\bevfusion\Scripts\torchpack.exe\__main__.py", line 7, in <module>
  File "C:\Users\18369\.conda\envs\bevfusion\lib\site-packages\torchpack\launch\main.py", line 17, in main
    drunner.main()
  File "C:\Users\18369\.conda\envs\bevfusion\lib\site-packages\torchpack\launch\launchers\drunner.py", line 104, in main
    os.execve('/bin/sh', ['/bin/sh', '-c', command], environ)
FileNotFoundError: [Errno 2] No such file or directory: '/bin/sh'

who can help?is this problem result in torchpack?

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
