### ISSUE TITLE
Can't find file

### ISSUE THREAD

**Issue by cgoldbird** [mit-han-lab/bevfusion#553]
QS: Where are the pth file？

**Comment by hwdyy** [comment]
> QS: Where are the pth file？

revise tools/download_pretrained.sh as

wget http://hanlab18.mit.edu/projects/bevfusion/files/pretrained_updated/bevfusion-det.pth &&
wget http://hanlab18.mit.edu/projects/bevfusion/files/pretrained_updated/bevfusion-seg.pth &&
wget http://hanlab18.mit.edu/projects/bevfusion/files/pretrained/lidar-only-det.pth &&
wget http://hanlab18.mit.edu/projects/bevfusion/files/pretrained/lidar-only-seg.pth &&
wget http://hanlab18.mit.edu/projects/bevfusion/files/pretrained_updated/camera-only-det.pth &&
wget http://hanlab18.mit.edu/projects/bevfusion/files/pretrained_updated/camera-only-seg.pth &&
wget http://hanlab18.mit.edu/projects/bevfusion/files/pretrained_updated/swint-nuimages-pretrained.pth
