### ISSUE TITLE
Other pretrained models

### ISSUE THREAD

**Issue by callenmacphee** [mit-han-lab/bevfusion#554]
Would it be possible to get the checkpoints for the ResNet backbone and TTA models? Thanks!

**Comment by liuyuansheng624** [comment]
> Would it be possible to get the checkpoints for the ResNet backbone and TTA models? Thanks!

Have you found any other checkpoints weights？can you call me e-mail liuys624@qq.com Thanks!

**Comment by zhijian-liu** [comment]
We've currently released the configuration files and pre-trained models only for the results reported in the paper. For any other configurations and models, you would need to train the model yourselves. Thank you for your understanding.
