### ISSUE TITLE
error for test seg task

### ISSUE THREAD

**Issue by Excutioner** [mit-han-lab/bevfusion#556]
During run `torchpack dist-run -np 1 python tools/test.py configs/nuscenes/seg/fusion-bev256d2-lss.yaml pretrained/bevfusion-seg.pth --eval map`
I had the same problem as #461at first, but I added the following code after line 185 in `nusences_converter.py`
` file location = nusc.get(
            "log", nusc.get("scene", sample["scene_token"])["log_token"]
        )["location"]`
And added location to the info
`'location': location, `
![1](https://github.com/mit-han-lab/bevfusion/assets/124240859/96b01010-93ea-47c2-874d-0b02736cbd10)
Rerun nusecenes_converter to regenerate the PKL file, the following error was encountered
AttributeError: 'dict' object has no attribute 'in_range_bev'
![2](https://github.com/mit-han-lab/bevfusion/assets/124240859/84a683f1-4a49-4b0f-a0e1-5f830d2ddd29)

**Comment by Yunge6666** [comment]
Have you solved this problem? I have the same problem...

**Comment by Qizhi697** [comment]
Have you solved this problem? I have the same problem...

**Comment by Qizhi697** [comment]
I have also got this problem during run `torchpack dist-run -np 1 python tools/test.py configs/nuscenes/seg/fusion-bev256d2-lss.yaml pretrained/bevfusion-seg.pth --eval map`. 
I don't know how to evaluate the pretrained model for the segmentation variant of BEVFusion.

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
