### ISSUE TITLE
How to train model with camera backbone ResNet50?

### ISSUE THREAD

**Issue by FantineFu** [mit-han-lab/bevfusion#558]
I found that there had been configs for resnet50 at "bevfusion/configs/nuscenes/det/transfusion/secfpn/camera+lidar/resnet50/convfuser.yaml", but now there is only swin-T, how to train with resnet50 now? Does it not available forever?

**Comment by liuyuansheng624** [comment]
> Same question

Have you solved it? Can I have further communication with you? Please contact me at liuys624@qq.com

**Comment by zhijian-liu** [comment]
We've currently released the configuration files and pre-trained models only for the results reported in the paper. For any other configurations and models, you would need to train the model yourselves. Thank you for your understanding.
