### ISSUE TITLE
All types object class AP=0

### ISSUE THREAD

**Issue by YHao29** [mit-han-lab/bevfusion#559]
#### 2. Prepared the full version nuscenes dataset and established a link to  `/data/nuscenes`
![1](https://github.com/mit-han-lab/bevfusion/assets/33367415/ed4f8473-5db4-4c9f-927e-04ecfa4503fb)

#### 3. prepared the pretrained model like 
![2](https://github.com/mit-han-lab/bevfusion/assets/33367415/a65d58c5-b7cc-4d87-8d71-fb49ad55695f)

#### it goes well with no error, only two warnings: 
1. `NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.`
2. `UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').`

#### But the results are weird:
![3](https://github.com/mit-han-lab/bevfusion/assets/33367415/f35d7871-46da-44cb-a60d-f703ee2e0a7c)

![4](https://github.com/mit-han-lab/bevfusion/assets/33367415/fa3f57e9-f964-4354-bd97-ef33f9454654)

### So are there any tips for me to fix it?

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
