### ISSUE TITLE
How to use torchpack

### ISSUE THREAD

**Issue by SuperHenry2333** [mit-han-lab/bevfusion#56]
Dear authors,
Thanks for your amazing work! When I ran your code, I got an error like this
<img width="920" alt="image" src="https://user-images.githubusercontent.com/22131577/177028620-1b737515-14dc-4da1-a822-76f65d44cb40.png">
How could I solve this problem?

**Comment by kentang-mit** [comment]
Hi @SuperHenry2333,

Thanks for your interest. What about first reading through some discussions [here](https://github.com/mit-han-lab/bevfusion/issues/21)? I think you will have to install OpenMPI and mpi4py on your machine.

Best,
Haotian
