### ISSUE TITLE
About Authorization required,but no authorization protocol specified

### ISSUE THREAD

**Issue by liuyuansheng624** [mit-han-lab/bevfusion#561]
![C7A6Q%@6KLAD63AVK~BTOPB](https://github.com/mit-han-lab/bevfusion/assets/108811669/6ebbdf56-153a-446c-997e-a3e1a57d64e4)
Do you have this problem?

**Comment by EpicGilgamesh** [comment]
Yes

**Comment by liuyuansheng624** [comment]
how to solve this question？



发自我的iPhone


------------------ Original ------------------
From: EpicGilgamesh ***@***.***&gt;
Date: Thu,Dec 21,2023 6:47 AM
To: mit-han-lab/bevfusion ***@***.***&gt;
Cc: liuys ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [mit-han-lab/bevfusion] About Authorization required,but noauthorization protocol specified (Issue #561)





 
Yes

**Comment by EpicGilgamesh** [comment]
Thanks to this tread https://github.com/mit-han-lab/bevfusion/issues/248
I found out that you need to install ninja and openmpi...
Idk how such an oversight could have been made, cuz I spend like 5 days trying to solve this using other methods like using torch.launch instead of torchpack, etc. XD
