### ISSUE TITLE
Wrong depth map

### ISSUE THREAD

**Issue by Jayden9912** [mit-han-lab/bevfusion#564]
Hi. I retrained the model and try to visualize the depth map predicted and find that it doesn't make sense. However, the performance of the model is about the same as recorded in the paper.

![image](https://github.com/mit-han-lab/bevfusion/assets/85933053/afaaea3b-9954-4800-be71-fac0d529b898)
![image](https://github.com/mit-han-lab/bevfusion/assets/85933053/9fce646b-cd2a-438a-acc5-5a4fba230d16)

I am using viridis colour scale.
![image](https://github.com/mit-han-lab/bevfusion/assets/85933053/97119e13-b3d3-4958-a76a-ff8d60fe3094)

**Comment by liyih** [comment]
Maybe you should close all the data augmentation and visualize the depth map again. If you don't close them the depth map corresponds to the augmented picture (scale, flip, rot, mask...)

**Comment by Jayden9912** [comment]
Thanks for the suggestion. Would give it a try later.

In the meantime, did you get a reasonable depth map on your side? May I have a look at it?

**Comment by liyih** [comment]
I only segment the object in the picture and project them into 3d space by depth. And I find the projected visual points overlap well with the original points cloud. In some way, it may prove the depth is right. The 2d pictures and 3d points may not in the same frame as I don't have enough time to do correspondence.
![图片3](https://github.com/mit-han-lab/bevfusion/assets/94298387/9858f79b-9a85-4c00-a8a3-1b4bad039613)
![图片4](https://github.com/mit-han-lab/bevfusion/assets/94298387/6bc85e6c-fa24-4c86-8d50-2fa90252fe61)

![图片1](https://github.com/mit-han-lab/bevfusion/assets/94298387/7502f953-719b-4d33-bd71-3c96c40010cd)
![图片2](https://github.com/mit-han-lab/bevfusion/assets/94298387/127a3ae4-fec6-4639-89de-e6accd5421dd)

**Comment by Jayden9912** [comment]
Hi, thanks for the visualization. May I know how you got the depth value? Are u using LSS transform for depth prediction as well?

**Comment by liyih** [comment]
I'm sorry that I misunderstand your meaning at begin. In fact, if you directly use the depth prediction by depth net it make no sense. Because in bevfusion the output of depth net is not be supervised. In the BaseDepthTransform of original code, it gives the right way to use lidar to get the depth of pixels (you could use this depth map to do visualization). If you want to make the output of depth net have right depth prediction, you should give a supervision like what bevdepth do. Please scan for bevdepth, which may give you some help.
Best

**Comment by Jayden9912** [comment]
I see, thanks for the suggestion.

I am quite confused because although the depth predicted by lss transform is not logical but it works with 3d object detection...

Any clue on this?

**Comment by liyih** [comment]
please look at part 3.2 in bevdepth, you may get some inspiration.

**Comment by dingmiaomiao** [comment]
I added AwareBEVDepth and the corresponding dense depth loss during training, but I found that the loss decreased by less than a small value, and there was no improvement in detection accuracy. Has anyone tried to add this loss?

**Comment by Jayden9912** [comment]
I remember in one of the issue the author mentioned the same observation. I am quite curious how accurate is the depth map trained using AwareBEVDepth
