### ISSUE TITLE
Question about table2 in paper

### ISSUE THREAD

**Issue by mc171819** [mit-han-lab/bevfusion#57]
Hi, I found you tested pointpillars and centerpoint in bev map segmentation task. I wonder how you perform this experiment? Did you just using pseudo image after pillar scatter or features provided by 2d CNN, than handle the feature with map head? @kentang-mit

**Comment by kentang-mit** [comment]
We just replace the `CenterHead` in CenterPoint with a map segmentation head. Unless explicitly specified, CenterPoint means the VoxelNet variant in the original paper.

**Comment by kentang-mit** [comment]
I will temporarily close this due to inactivity. Feel free to reopen if you have further questions.
