### ISSUE TITLE
Question about the Position of Lidar Backbone in the Model Architecture

### ISSUE THREAD

**Issue by barrydoooit** [mit-han-lab/bevfusion#576]
Hi Authors, thanks for your fancy paper and code. I've been reading the forward procedures of BEVFusion. Regarding [these lines](https://github.com/mit-han-lab/bevfusion/blob/main/mmdet3d/models/fusion_models/bevfusion.py#L331-L340), it shows that the Lidar backbone SECOND is applied after the fusion module. I wonder that if this is an update from your original design, or that "Lidar Backbone" is actually the "BEV encoder" shown in Fig 2 (the model pipeline) of your paper. Looking forward to your reply.

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
