### ISSUE TITLE
Dimension inconsistency in convolusion operations in Conv2d and F.conv2d

### ISSUE THREAD

**Issue by alexzhuuuu** [mit-han-lab/bevfusion#577]
Run the command like this:
"python tools/test.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml pretrained/bevfusion-det.pth --eval bbox" 

and I got an error like the following sentence:
'RuntimeError: Given groups=1, weight of size [8, 1, 1, 1], expected input[6, 6, 256, 704] to have 1 channels, but got 6 channels instead'

Problem of nn.Conv2d and F.conv2d??
How can I fix it?

**Comment by alexzhuuuu** [comment]
similar with 
[https://github.com/mit-han-lab/bevfusion/issues/478](url)

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
