### ISSUE TITLE
Key Error: 'ann_info' when evaluating on Nuscenes test set

### ISSUE THREAD

**Issue by vtghsr** [mit-han-lab/bevfusion#580]
I know the test set of Nuscenes does not have annotation, but how do I solve this problem?
![image](https://github.com/mit-han-lab/bevfusion/assets/37099758/430735ef-f927-4094-95b9-b468f9722bf7)

**Comment by alexzhuuuu** [comment]
> I know the test set of Nuscenes does not have annotation, but how do I solve this problem? ![image](https://private-user-images.githubusercontent.com/37099758/293494868-430735ef-f927-4094-95b9-b468f9722bf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NTQzMzksIm5iZiI6MTcwNTc1NDAzOSwicGF0aCI6Ii8zNzA5OTc1OC8yOTM0OTQ4NjgtNDMwNzM1ZWYtZjkyNy00MDk0LTk1YjktYjQ2OGY5NzIyYmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDEyMzM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExOWUxNTk3ZTgzMTRmMzhjMzU1YmQ0NDVmMzY5Y2IyMzNlMDNiYWQ4MzdmMzdlNDBlNmZkZDYzNTk3OGY2MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.73HgrcBto5iuwQDUkFU65QyM8aFfm02Q2e0zQ6PnVw8)
change the codes in NuScenesDataset get_data_info function:
if not self.test_mode:                      
        annos = self.get_ann_info(index)        
        data['ann_info'] = annos          
        
return data

Maybe it works.

**Comment by esh64** [comment]
Same problem, followed the #233 but got this same error. Does anybody know how to solve this?
