### ISSUE TITLE
performance drops - float16 vs float32

### ISSUE THREAD

**Issue by tomschw800** [mit-han-lab/bevfusion#581]
I noticed that the performance drops a lot when the training originally run in float16 (half precision) is changed to float32.

I run the training as this
`torchpack dist-run -np 4 python tools/train.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml  --load_from pretrained/lidar-only-det.pth 
`

In `convfuser.yaml` I added the lines:

> fp16: null # -> float32
> data:
>   samples_per_gpu: 3
>   workers_per_gpu: 3

Why is that?

**Comment by zhijian-liu** [comment]
We always used half-precision in all our experiments and haven't experimented with FP32, so unfortunately, we haven't observed this ourselves.
