### ISSUE TITLE
Missing some implementation of transfusion?

### ISSUE THREAD

**Issue by YueSun0609** [mit-han-lab/bevfusion#586]
Dear author,

I just found it seems that in your code of transfusion head, in "transformer decoder layer (img feature as K,V)" 
(refer to https://github.com/mit-han-lab/bevfusion/blob/531bf67dd56192cf1cff7baf2995312efdba1ea9/mmdet3d/models/heads/bbox/transfusion.py#L320), features are not passing through the decoder in your code, so I just want to ask whether you skip the implementation there? If yes, may I ask what's reason to skip it? Thank you so much!

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
