### ISSUE TITLE
Image BEV feature was getting worse during training

### ISSUE THREAD

**Issue by eugenebak** [mit-han-lab/bevfusion#587]
Hi

I'm trying to train the BEVFusion using a single image and its corresponding point cloud for my custom dataset.

But, the performance gap was not large between LiDAR and fusion model.

So, I visualized the image features at a specific iteration during training. I observed that image bev feature was getting worse. It means that It cannot represent the scene in BEV map. I think the depth estimation seems to be a problem.

iteration 0.
![image](https://github.com/mit-han-lab/bevfusion/assets/60248657/803e0774-32c1-4f52-bf5b-abf76a356f81)

iteration 1900
![image](https://github.com/mit-han-lab/bevfusion/assets/60248657/bd7967f1-458d-4a9e-927c-d217835ab90e)

I think the image bev feature is enforced to be zero map during training because it didn't provide useful information for object detection.

Can you give me some advice?
Thank you in advance.

**Comment by gerardmartin2** [comment]
Hello @eugenebak, do you remeber the changes you have done to the code?

**Comment by zhijian-liu** [comment]
Adding support for custom dataset is beyond the scope of this codebase, and unfortunately, we don't have the bandwidth with such customized requests.
