### ISSUE TITLE
learning rate configuration

### ISSUE THREAD

**Issue by konyul** [mit-han-lab/bevfusion#590]
Thank you for sharing such a great work!
I am struggling to reproduce the L+C result of Bevfusion.
Currently, the repreduced result is 70.14 NDS.
What I did was modifying sweeps from 0 -> 9.
And I am now trying to freeze the img_backbone pipeline now.

If the above work doesn't work, then I am going to do following thing.
1. Modifying lr schedule
I reproduced the bevfusion in mmdetection3d. So I am comparing between the bevfusion in mmdetection3d and bevfusion in this repository.
The bevfusion in mmdetection3d and bevfusion in this repository both uses CosineAnnealingLR config but is slightly different.
lr used in bevfusion in mmdetection3d
![image](https://github.com/mit-han-lab/bevfusion/assets/70498916/f3c1f0a6-42db-4b6a-811f-434fea5d5530)
the lr seems to decrease during the epoch
however lr used in bevfusion in this repository is 
![image](https://github.com/mit-han-lab/bevfusion/assets/70498916/9787a412-c697-4b8a-a694-64ae2f402af9)
It seems static during the epoch
So is there any way to change the lr config in mmdetection3d to bevfusion in this repository.

Is there any other way to try to reproduce?

**Comment by Li-Whasaka** [comment]
have you reproduced the results?

**Comment by gerardmartin2** [comment]
@konyul Any updates?

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
