### ISSUE TITLE
Inquiry regarding use of RGB-D camera

### ISSUE THREAD

**Issue by Poodlee** [mit-han-lab/bevfusion#592]
hello. I currently have an RGB-D camera and would like to do 3D object detection. So, while looking for various codes, I found this GitHub. So, I read a paper on this and was wondering if it would be possible to proceed using an RGB-D camera, so I am writing this post.

I am very inexperienced in this field, so I would appreciate it if you could explain it in detail if possible.

For example, the paper used 6 cameras as an example, but I don't know how to change it to 1 camera and limit the range of LiDAR's point cloud to apply it in practice.

**Comment by gerardmartin2** [comment]
@Poodlee  Have you been able to solve it?

**Comment by Poodlee** [comment]
> @Poodlee  Have you been able to solve it?

sorry for lately reply. Currently, I couldn't find a way in that way, and I'm studying mmdet3d and proceeding with other directions.
