### ISSUE TITLE
error raised by setup.py

### ISSUE THREAD

**Issue by fdy61** [mit-han-lab/bevfusion#593]
when I run "python setup.py develop",It will raise error "nvcc fatal: Unsupported gpu architecture compute_80" as well as compute_86,but I use RTX3090.How could I solve it?

![image](https://github.com/mit-han-lab/bevfusion/assets/134828384/7c88ee64-ad8c-458e-a458-e4ca9086ab0e)

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
