### ISSUE TITLE
Why is this fix needed? newest release of mmdetection3d still does not do this

### ISSUE THREAD

**Issue by kabouzeid** [mit-han-lab/bevfusion#598]
https://github.com/mit-han-lab/bevfusion/blob/531bf67dd56192cf1cff7baf2995312efdba1ea9/mmdet3d/models/heads/bbox/transfusion.py#L570-L573

**Comment by zhijian-liu** [comment]
This is because we are using a different coordinate system than `mmdetection3d`.
