### ISSUE TITLE
The training of bevfusion only modifies the POINT-CLOUD-RANGE algorithm, resulting in significant differences in effectiveness

### ISSUE THREAD

**Issue by zzwforver** [mit-han-lab/bevfusion#599]
May I ask for your advice? When training the bevfusion model with the same data and configuration, the algorithm performs well when the XY value of POINT-CLOUD-RANGE is the same, but when the XY value is twice that of X or the difference between XY is significant, the algorithm performs worse, only changing the value of XY. What is the reason for this

**Comment by zhijian-liu** [comment]
We haven't experimented with that. In principle, I don't expect to see such a drastic performance difference with different spatial range settings.
