### ISSUE TITLE
how can I dump a bevfusion model to onnx?

### ISSUE THREAD

**Issue by hych2020** [mit-han-lab/bevfusion#60]
I try to dump a detection model to onnx by following command, but failed

```
python tools/export.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml pretrained/bevfusion-det.pth
```
error
![图片](https://user-images.githubusercontent.com/108866107/177752726-da65d493-88d7-4d1c-b79f-03a5e8545c58.png)

after fix the config problem, another error occurred
![图片](https://user-images.githubusercontent.com/108866107/177753242-009eaca6-bc93-46f9-89ae-b399d4765cf3.png)

**Comment by kentang-mit** [comment]
Hi @hych2020,

It might be hard to export BEVFusion to onnx currently. The input problem you met with can be solved by manually passing these arguments into the forward function instead of relying on the containers in `mmcv`. However, our model is composed of SparseConv layers and customized CUDA ops (such as BEV pooling). Exporting them to onnx will require significant work and we haven't started trying that. 

Best,
Haotian

**Comment by hych2020** [comment]
Hi @kentang-mit 

Thank you.

I got it.

So How do you measure FPS on Specific hardware， using the pytorch model directly?
I thought it was converting to onnx first，then deployed with TensorRT。

**Comment by kentang-mit** [comment]
Hi @hych2020,

You can check out [this issue](https://github.com/mit-han-lab/bevfusion/issues/14). TensorRT is not used in latency measurement. With that being said, I expect the latency to be lower than what is reported in the paper if we eventually have the pipeline you mentioned.

Best,
Haotian

**Comment by hych2020** [comment]
OK! Thank you very much!

**Comment by RangineniBalaji** [comment]
> I try to dump a detection model to onnx by following command, but failed
> 
> ```
> python tools/export.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml pretrained/bevfusion-det.pth
> ```
> 
> error ![图片](https://user-images.githubusercontent.com/108866107/177752726-da65d493-88d7-4d1c-b79f-03a5e8545c58.png)
> 
> after fix the config problem, another error occurred ![图片](https://user-images.githubusercontent.com/108866107/177753242-009eaca6-bc93-46f9-89ae-b399d4765cf3.png)

Hi hych, do you exported the model to onnx.?
