### ISSUE TITLE
Why is the height of LiDAR voxelized grid 41

### ISSUE THREAD

**Issue by duanmushuangquan** [mit-han-lab/bevfusion#600]
The lidar range is [-54, -54, -5, 54, 54, 3], the step length is [0.075, 0.075, 0.2], the height line should be calculated to be 40, but why is the input network 41

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
