### ISSUE TITLE
fatal: unable to access 'https://github.com/mit-han-lab/bevfusion/': gnutls_handshake() failed: Error in the pull function.

### ISSUE THREAD

**Issue by OrangeJuice3211** [mit-han-lab/bevfusion#601]
when i run `cd home && git clone https://github.com/mit-han-lab/bevfusion && cd bevfusion` in docker container which is built by
```bash
cd docker && docker build . -t bevfusion
```
this git error occurred. 
![image](https://github.com/mit-han-lab/bevfusion/assets/74034577/dc779ffd-61be-4d7e-a2ae-4f6cb5f19a18)
Can someone help me？

**Comment by zhijian-liu** [comment]
This seems related: https://github.com/NVIDIA/nvidia-docker/issues/714
