### ISSUE TITLE
problems about test and visualize

### ISSUE THREAD

**Issue by 18lalala** [mit-han-lab/bevfusion#604]
Thanks a lot for your work. I tried to test the pretrained model on 2 3090 gpus and encountered with some problems

1. I run `torchpack dist-run -np 2 python tools/test.py configs/nuscenes/seg/fusion-bev256d2-lss.yaml pretrained/bevfusion-seg.pth --eval map` and the program stuck in the last like this 
![problem1](https://github.com/mit-han-lab/bevfusion/assets/58280081/70016a2b-eb10-4906-a728-a39900ec443d)

2. I alse tried to visualize the result. I run `torchpack dist-run -np 2 python tools/visualize.py configs/nuscenes/seg/fusion-bev256d2-lss.yaml --model pred --checkpoint pretrained/bevfusion-seg.pth --out-dir result/visualize`  , then the error was ` N > 0 assert faild. CUDA kernel launch blocks must be positive, but got N= 0`, I followed other issues to checkout the version of mmcv mmcv-full are 1.4.0 and when run test.py I did not meet the same problem. Then I run the visualize code on detection model the following error appears, it seems like the authors added radar data in to the pipeline, how can I used the downloaded pretrained model?
![problem3](https://github.com/mit-han-lab/bevfusion/assets/58280081/274ac03b-273f-4a8c-9db4-9ef8659fd4b6)

**Comment by zhijian-liu** [comment]
Could you try `torchpack dirt-run -v -np 2 ...` to see if there's a more detailed error message?
