### ISSUE TITLE
The problem with the test

### ISSUE THREAD

**Issue by Ange1ika** [mit-han-lab/bevfusion#607]
The problem with the test

![image](https://github.com/mit-han-lab/bevfusion/assets/91610545/8ded6bd8-f74d-48ae-b02c-a2162cef9a7a)

if run
torchpack dist-run -np 8 python tools/test.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml pretrained/bevfusion-det.pth --eval bbox
he falls out somewhere, into an endless cycle - it is unclear what he is doing...
![image](https://github.com/mit-han-lab/bevfusion/assets/91610545/b99034a9-7c51-455d-b3c8-0c72f5b70b57)

I tried to do debugging, at the last it outputs 185 and loads checkpoints

**Comment by zhijian-liu** [comment]
Could you try `torchpack dirt-run -v -np 8 ...` to see if there's a more detailed error message?

**Comment by Ange1ika** [comment]
I'm sorry that I took a long time to answer, now I will answer every day, because there is an urgent need to complete the project. There is such an error hanging now:

![image](https://github.com/mit-han-lab/bevfusion/assets/91610545/80ef5305-0501-4016-aca5-a8948d8a9540)
Thanks for the answer

**Comment by Ange1ika** [comment]
![image](https://github.com/mit-han-lab/bevfusion/assets/91610545/df92b826-8bd2-4c80-a833-14b714705523)

**Comment by Ange1ika** [comment]
torchpack dist-run -np 8 python visualize.py /configs/nuscenes/seg/fusion-bev256d2-lss.yaml --model.encoders.camera.backbone.init_cfg.checkpoint pretrained/swint-nuimages-pretrained.pth --load_from pretrained/bevfusion-seg.pth

torchpack dist-run -np 1 python tools/visualize.py configs/nuscenes/seg/lidar-centerpoint-bev128.yaml --model.encoders.camera.backbone.init_cfg.checkpoint pretrained/swint-nuimages-pretrained.pth --load_from pretrained/lidar-only-seg.pth
Can you tell me what the errors are? 


torchpack dist-run -np 2 python tools/visualize.py configs/nuscenes/seg/fusion-bev256d2-lss.yaml --model pred --checkpoint pretrained/bevfusion-seg.pth --out-dir result/visualize fixed it, but
[create_data question](https://github.com/mit-han-lab/bevfusion/issues/461#top)
#461   
![image](https://github.com/mit-han-lab/bevfusion/assets/91610545/453c0944-9ac2-4f2c-bee5-cf4e74e7afab)

**Comment by Ange1ika** [comment]
And can you explain how to figure out what is the dimension of the input data, for example, for the lidar-only-det(seg) model, what are the outputs and their dimension ? Is there any way to withdraw it? Sorry for the number of questions

**Comment by Ange1ika** [comment]
https://github.com/mit-han-lab/bevfusion/issues/512   After installation, there was still an error... I started it 
torchpack dist-run -np 8 python tools/train.py configs/nuscenes/det/transfusion/secfpn/lidar/voxelnet_0p075.yaml

**Comment by Ange1ika** [comment]
![image](https://github.com/mit-han-lab/bevfusion/assets/91610545/af2539a4-f197-4810-8e5e-b2edd4de15ee)
 back to the last message

**Comment by Ange1ika** [comment]
I've solved almost all those problems. 
![image](https://github.com/mit-han-lab/bevfusion/assets/91610545/51684a3e-8310-4272-8ec0-860236c66cfd)
There was a problem during training - [RuntimeError: sigmoid_focal_loss_forward_impl: implementation for device cuda:0 not found. · Issue #228 · mit-han-lab/bevfusion (github.com)](https://github.com/mit-han-lab/bevfusion/issues/228) ---I have cuda 12.3, and docker 11.3 - most likely, this is the problem, but the solutions presented here did not help me.

**Comment by Ange1ika** [comment]
I can ask you to describe the dimensions of the main modules of the model for understanding. The article contains fragments, but it is difficult to put them together

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
