### ISSUE TITLE
Reproducing code with low accuracy

### ISSUE THREAD

**Issue by xmutyjs** [mit-han-lab/bevfusion#612]
Hello, I am reproducing your code, but my training accuracy is far from reaching. How should I handle this? The training is for bevfusion det(L+C), which can output two modalities through visualization, but the training accuracy is too low(NDS=0.4665). We earnestly request your reply and help!

**Comment by xmutyjs** [comment]
The system is ubuntu20.04, and the GPU is a single a100. Although there are four a100, parallel training is not feasible and can only temporarily use a single GPU

**Comment by wyf0414** [comment]
Parallel training may affect performance. 
Try adding `CUDA_VISIBLE-DEVICES=0, 1, 2, 3` before the training code.

Another reason may be that The model does not converge.
Try adding the epoch.

PS: I'm a beginner. My opinion is for reference only.
