### ISSUE TITLE
Input/output shapes of the BEVFusion.voxelize() method

### ISSUE THREAD

**Issue by maxvandenhoven** [mit-han-lab/bevfusion#616]
Thanks for the amazing work on BEVFusion!

I was trying to understand the code for the LiDAR encoder to re-use it in my own project, but I am having some issues with getting the entire project to run in order to inspect the tensor shapes. Could you help me with the input and output shapes of the `BEVFusion.voxelize()` method? I am particularly interested in the shape of the `points` input argument and the `feats`, `coords`, and `sizes` outputs. A brief description of what the dimensions are supposed to represent would also be greatly appreciated!

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
