### ISSUE TITLE
Extrinsic and intrinsic matrices after ImageAug3D and GlobalRotScaleTrans

### ISSUE THREAD

**Issue by ME-SJTU** [mit-han-lab/bevfusion#617]
Hi, thank you for your nice work.
I noticed that the fusion with images delivers five parameter matrices, including lidar2img, cam2img, lidar2cam, img_aug_matrix, and lidar_aug_matrix. During training, it was found that the direct use of lidar2img was not aligned. I would like to ask whether cam2img and lidar2cam are transformed. If I want to get the real lidar2img after transformation, do I need to use these two for calculation? Or do img_aug_matrix and lidar_aug_matirx need to be taken into account? Thank you.

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
