### ISSUE TITLE
config for camera+lidar with centerhead

### ISSUE THREAD

**Issue by zyh321** [mit-han-lab/bevfusion#618]
@zhijian-liu  Hi, thanks great for sharing your work.

Now I am trying to replace the Transfusion_L head with the centerhead. I find there only the "camera" and "camera + radar" part config in the centerhead branch, could you provide the related configs if you've  done this before?

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
