### ISSUE TITLE
How do I train the model？

### ISSUE THREAD

**Issue by Fengshihao1** [mit-han-lab/bevfusion#62]
Hi boss，
  Thank you very much for your work！I want to try BEVFusion to train a model, but I don't have a full configfile, can you provide a full profile? Thank you very much.

**Comment by kentang-mit** [comment]
Training details will be released in the future. Please stay tuned.

**Comment by Fengshihao1** [comment]
Thank you very much for your answer, I will very much look forward to your training details.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mit-han-lab/bevfusion"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月8日(星期五) 上午10:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mit-han-lab/bevfusion] How do I train the model？ (Issue #62)





 
Training details will be released in the future. Please stay tuned.

**Comment by HuangVictorAuto** [comment]
> Training details will be released in the future. Please stay tuned.

@kentang-mit , have you released the training details already? 
I have seen the training for camera_only detection, segmentation, lidar only detection, segmentation.  Will there be a config to train the multi task and fusion model all in one? thanks!
