### ISSUE TITLE
config and training setps for train a multitask model?

### ISSUE THREAD

**Issue by shupinghu** [mit-han-lab/bevfusion#621]
Hello, Thank you for your contribution and this is really a nice work.

Recently I'm trying to train a multi-task model based on your work, the method I used is simply adding the map head to the det config, but the det and seg performances all degraded severely. Have you ever tried to improve the performance of multitask model? I wander If it's possible to share the config and method for multitask model? My email is [hushp3@qq.com](mailto:hushp3@qq.com).

Thanks!!

**Comment by think-twice-1218** [comment]
hello, we have the save problem. We try to add config in the nuscenes\det\default.yaml
<img width="332" alt="image" src="https://github.com/mit-han-lab/bevfusion/assets/82155690/0dbc8999-8774-4b21-94a4-e94106852112">

- we change the grid_transform to match those in detection. 
- But the result is very low for the first epoch, map/mean/iou@max: 0.2930, object/map: 0.6539.
- Strangely,when we train on det, it takes 3 days for 6 epoches. When training seg, it takes 5 days  for 20 epoches. But when trained together, it only takes 1 day for 6 epoches. 
Do you have any suggestions or guess?

PS: We followed https://github.com/mit-han-lab/bevfusion/issues/263#issuecomment-1346905589 , the results are  map/mean/iou@max: 0.3571 and object/map: 0.6554

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
