### ISSUE TITLE
About the test accuracy not reaching

### ISSUE THREAD

**Issue by npuxdy** [mit-han-lab/bevfusion#622]
Hello , I recently tried to reproduce your experiment. I used the latest code from the master, but when I used bevfusion.pth for testing, I found that the accuracy did not reach the accuracy you mentioned.

**Comment by npuxdy** [comment]
![屏幕截图 2024-06-04 235222](https://github.com/mit-han-lab/bevfusion/assets/150421955/ab81fc45-41e3-43ef-a636-9fc81c285ec7)

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
