### ISSUE TITLE
What changes are needed to modify the detection range to 100 meters before and after？

### ISSUE THREAD

**Issue by Tamako668** [mit-han-lab/bevfusion#623]
Modify the point cloud detection range to: point_cloud_range: [-108, -108, -5.0, 108, 108, 3.0]
What other modifications are needed besides modifying sparse_shape?

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
