### ISSUE TITLE
How to make custom dataset only with Lidar information？

### ISSUE THREAD

**Issue by mx2013713828** [mit-han-lab/bevfusion#627]
Thanks for your great work.
I just have labeled pointcloud data ,can I train  lidar-only bev model?with custom dataset? 
best wishes!

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
