### ISSUE TITLE
Inconsistent reproducing results on the nuscene dataset!

### ISSUE THREAD

**Issue by zyqww** [mit-han-lab/bevfusion#630]
I downloaded the latest code and checkpoint files
When testing the Lidar-only and Camera-only models, the results obtained were mAP=0.6468, NDS=0.6924 and mAP=0.3554, NDS=0.4121, which are very similar to the paper results, using the commands respectively:
- torchpack dist-run -np 1 python tools/test.py configs/nuscenes/det/transfusion/secfpn/lidar/voxelnet_0p075.yaml pretrained/lidar-only-det .pth --eval bbox
- torchpack dist-run -np 1 python tools/test.py configs/nuscenes/det/centerhead/lssfpn/camera/256x704/swint/default.yaml pretrained/camera- only-det.pth --eval bbox
However, when testing the fusion model the results obtained are mAP=0.6728 and NDS=0.7069, which is inconsistent with the paper results mAP=0.6852 and NDS=0.7138, why does this problem arise?
The command used is:
 torchpack dist-run -np 1 python tools/test.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml pretrained/bevfusion-det.pth --eval bbox

**Comment by zyqww** [comment]
It's worth mentioning that I trained on RTX3090 with samples_per_gpu and workers_per_gpu set to 2 and 0 respectively.

**Comment by zyqww** [comment]
It is worth mentioning that I can only train on one RTX3090 now, samples_per_gpu and workers_per_gpu are set to 2 and 0 respectively, and there will be an error when training with the original parameters, that is "ValueError: matrix contains invalid numeric entries". I will try to change the learning rate for this problem, but I want to ask if this training method is feasible at present? In addition, the training time is also very long, how can I change it to train on four RTX3090?

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
