### ISSUE TITLE
Problems about tasks, min_radius, nms_type and nms_scale

### ISSUE THREAD

**Issue by zhujiagang** [mit-han-lab/bevfusion#631]
Thanks for sharing your excellent code! I am not sure the meaning of `tasks`  and other settings here https://github.com/mit-han-lab/bevfusion/blob/4d1ab76686ab53ccf8ead4a1bdf5b6d39c10b5ee/configs/nuscenes/det/centerhead/default.yaml#L30, 
https://github.com/mit-han-lab/bevfusion/blob/4d1ab76686ab53ccf8ead4a1bdf5b6d39c10b5ee/configs/nuscenes/det/centerhead/default.yaml#L30C1-L36C41
https://github.com/mit-han-lab/bevfusion/blob/4d1ab76686ab53ccf8ead4a1bdf5b6d39c10b5ee/configs/nuscenes/det/centerhead/default.yaml#L22,
https://github.com/mit-han-lab/bevfusion/blob/4d1ab76686ab53ccf8ead4a1bdf5b6d39c10b5ee/configs/nuscenes/det/centerhead/lssfpn/camera/default.yaml#L21,
https://github.com/mit-han-lab/bevfusion/blob/4d1ab76686ab53ccf8ead4a1bdf5b6d39c10b5ee/configs/nuscenes/det/centerhead/lssfpn/camera/default.yaml#L28.
Are these classes arranged according to detection difficulties? Are other nms settings set according to the size of classes?
        - ["car"]
        - ["truck", "construction_vehicle"]
        - ["bus", "trailer"]
        - ["barrier"]
        - ["motorcycle", "bicycle"]
        - ["pedestrian", "traffic_cone"]
 If I have a different dataset and N classes, can I set tasks -[C_1, C_2, ..., C_N] or 
-[C_1], 
-[C_2],
-... ,
-[C_N], because it is tricky to decide the difficulty of different categories, or measure their sizes.

**Comment by zhijian-liu** [comment]
Thank you for your interest in our project. This repository is no longer actively maintained, so we will be closing this issue. Please refer to the amazing implementation at [MMDetection3D](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/BEVFusion). Thank you again!
