### ISSUE TITLE
Did you load pre-trained weights when training?

### ISSUE THREAD

**Issue by SuperHenry2333** [mit-han-lab/bevfusion#68]
Dear authors,
Thank you for your amazing work! Did you load pre-trained weights or external data during training?

**Comment by kentang-mit** [comment]
Hi @SuperHenry2333,

Thanks for your interest. Pretrained weights are used but no external data (such as DD3D) is used.

Best,
Haotian

**Comment by SuperHenry2333** [comment]
Thank you very much for your quick reply. Could you give a hint on which pre-trained checkpoint is loaded?
