### ISSUE TITLE
Multitask config files. 

### ISSUE THREAD

**Issue by Capchenxi** [mit-han-lab/bevfusion#7]
Hello,

Thanks for your excellent work! I'm reading the paper and codes of this work and realize the released configs and pretrained models are for det or seg tasks specifically while the model you use in paper is a multitask framework. Is there anything I miss or do you have any plan for releasing the multitask configs/pretrained models? Thanks.

**Comment by Capchenxi** [comment]
Got it. Will keep eye on the project. Thanks.

**Comment by kentang-mit** [comment]
You're welcome. I'll temporarily close this issue. Feel free to reopen if you have further questions.
