### ISSUE TITLE
pretrained checkpoints

### ISSUE THREAD

**Issue by SuperHenry2333** [mit-han-lab/bevfusion#71]
Hi @SuperHenry2333,

Thanks for your interest. Pretrained weights are used but no external data (such as DDAD15M) is used.

Best,
Haotian

_Originally posted by @kentang-mit in https://github.com/mit-han-lab/bevfusion/issues/68#issuecomment-1180686009_

**Comment by SuperHenry2333** [comment]
Thank you very much for your quick reply. Could you give a hint on which pre-trained checkpoint is loaded?

**Comment by kentang-mit** [comment]
We follow the common practice (PointPainting, MVP, TransFusion) to retrain the image backbone on nuImages. Note that nuImages is not considered as external dataset by nuScenes.

**Comment by SuperHenry2333** [comment]
Thank you very much!
