### ISSUE TITLE
Training details

### ISSUE THREAD

**Issue by VeeranjaneyuluToka** [mit-han-lab/bevfusion#78]
Hi, Have seen a couple of issues already stating that training details will be populated in some time later. But wondering if there is any help that i can get priority to that to make training works or anybody already trained a model could share details. I tried to trigger training and end up having the below error

AttributeError: 'ConfigDict' object has no attribute 'optimizer_config'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[13274,1],0]
  Exit code:    1

Would be great help if there any pointers to solve the above error and make training works.

Thanks,
Veeru.

**Comment by xuxiaoxxxx** [comment]
> 

Hi, I also meet this problem，do you solve this problem?
