### ISSUE TITLE
Does the code support training?

### ISSUE THREAD

**Issue by XiangboGaoBarry** [mit-han-lab/bevfusion#84]
When I try to train the camera only model, `configs/nuscenes/det/centerhead/lssfpn/camera/256x704/swint/default.yaml`, I got error 'ConfigDict' object has no attribute 'optimizer_config_config'.
When I try to train the camera-lidar model, `configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml`, I got error 'ConfigDict' object has no attribute 'lr_config'.

For the latter one, the error is gone after I add `lr_config : null` to the config file, but I am not sure it this is the right thing to do.

**Comment by kentang-mit** [comment]
Training details will be released in the future.
