### ISSUE TITLE
How to get the BEV feature of Lidar?

### ISSUE THREAD

**Issue by sunnyHelen** [mit-han-lab/bevfusion#87]
Hi, thanks a lot for releasing this great work. I want to know how did you get the BEV feature of Lidar. I notice you are using Sparse Encoder to extract the pts features. So is this line to get the BEV feature?
https://github.com/mit-han-lab/bevfusion/blob/008b4a8b3287a6aba159712c4baff637e73d20e1/mmdet3d/models/backbones/sparse_encoder.py#L130

**Comment by kentang-mit** [comment]
Yes, your understanding is correct.

**Comment by sunnyHelen** [comment]
Hi, thanks for your quick reply. Actually, I feel a bit strange because (N, C * D, H, W) seems like a front-view feature. And (N, C * H, D, W) is more likely to be the BEV feature. Could you please help me figure it out?

**Comment by kentang-mit** [comment]
Hi @sunnyHelen,

Perhaps the naming of different dimensions is a bit confusing. D refers to the z dimension, and here we are actually performing Spatial2Channel as is mentioned in M2BEV.

Best,
Haotian

**Comment by sunnyHelen** [comment]
Got it! Thanks for the discussion.

**Comment by kentang-mit** [comment]
No problem. I will temporarily close this issue since it is resolved.
