### ISSUE TITLE
yaml file test:  ann_file: ${dataset_root + "nuscenes_infos_val.pkl"}

### ISSUE THREAD

**Issue by BaiLiping** [mit-han-lab/bevfusion#88]
hi, the nuscenes default.yaml file stipulates     ann_file: ${dataset_root + "nuscenes_infos_val.pkl"} this is wrong right? it should be     ann_file: ${dataset_root + "nuscenes_infos_test.pkl"}?

**Comment by kentang-mit** [comment]
If you need to submit to the test server, you need to make this change.
