### ISSUE TITLE
About the use of objectpaste, when training the lidar branch

### ISSUE THREAD

**Issue by miaochunle** [mit-han-lab/bevfusion#89]
Hello,
Thanks for your inspiring work, and I am trying to run the code you provided.
Did you use ObjectPaste when training lidar branch？I don't know why when I use it the score drops instead.

Objectpaste is set as follows:
gt_paste_stop_epoch: 15
-
    type: ObjectPaste
    stop_epoch: ${gt_paste_stop_epoch}
    db_sampler:
      dataset_root: ${dataset_root}
      info_path: ${dataset_root + "nuscenes_dbinfos_train.pkl"}
      rate: 1.0
      prepare: 
        filter_by_difficulty: [-1]
        filter_by_min_points:
          car: 5
          truck: 5
          bus: 5
          trailer: 5
          construction_vehicle: 5
          traffic_cone: 5
          barrier: 5
          motorcycle: 5
          bicycle: 5
          pedestrian: 5
      classes: ${object_classes}
      sample_groups:
        car: 2
        truck: 3
        construction_vehicle: 7
        bus: 4
        trailer: 6
        barrier: 2
        motorcycle: 6
        bicycle: 6
        pedestrian: 2
        traffic_cone: 2
      points_loader:
        type: LoadPointsFromFile
        coord_type: LIDAR
        load_dim: ${load_dim}
        use_dim: ${use_dim}
        reduce_beams: ${reduce_beams}

![image](https://user-images.githubusercontent.com/72178672/182346736-3080646e-7f69-4420-8a9e-2a757a49d221.png)

**Comment by kentang-mit** [comment]
Hello, we used that. And this is the fading strategy used by multiple papers such as PointAugmenting, FUTR3D and TransFusion. I will start answering training-related questions after we release the training code due to limited bandwidth.
