### ISSUE TITLE
There is a strange question occurring

### ISSUE THREAD

**Issue by qfwysw** [mit-han-lab/bevfusion#91]
![image](https://user-images.githubusercontent.com/53482524/183234325-f916bd05-3254-4e2c-8117-565e135f7fcc.png)
My code:
`torchpack dist-run -np 8 python tools/test.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml pretrained/bevfusion-det.pth --eval bbox
`
Looking at previous questions, I have openmpi installed.

**Comment by kentang-mit** [comment]
Hello @qfwysw,

Would you mind running the following command again and provide the error message?

```bash
torchpack dist-run -np 8 -v python tools/test.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml pretrained/bevfusion-det.pth --eval bbox
```

Best,
Haotian

**Comment by qfwysw** [comment]
![image](https://user-images.githubusercontent.com/53482524/183238490-3407447e-ff70-4c62-95ca-f5d972b7814d.png)
Just like this.
But, I dont run another program.

**Comment by qfwysw** [comment]
![image](https://user-images.githubusercontent.com/53482524/183238569-ee3d86c7-f153-4a55-8624-61131678d363.png)
I try to do this, but it doesn't work.

**Comment by kentang-mit** [comment]
Probably you can try launching the script when there is no other distributed job running.

**Comment by qfwysw** [comment]
No matter which port I choose, he prompts me that the address is already in use

**Comment by qfwysw** [comment]
![image](https://user-images.githubusercontent.com/53482524/183243450-4dd3532b-1333-44a4-910d-a3b8cd9eb311.png)
![image](https://user-images.githubusercontent.com/53482524/183243489-cc6ed235-b1e0-4b22-baf4-290783d90da5.png)
I have chose another port, it is really strange.

**Comment by kentang-mit** [comment]
Probably changing the `MASTER_HOST` will not work, I remember that @zhijian-liu mentioned that to me a while ago.

**Comment by kentang-mit** [comment]
Temporarily closed due to inactivity. Feel free to reopen if new issues occur.
