### ISSUE TITLE
no singapore-onenorth.json

### ISSUE THREAD

**Issue by qfwysw** [mit-han-lab/bevfusion#92]
![image](https://user-images.githubusercontent.com/53482524/183244502-cb3f8bfe-e3c8-42d8-98af-d37579bf63c3.png)
I check my dataset, I didn't fint it. What's wrong with this?

**Comment by kentang-mit** [comment]
You will have to download the full map extension from nuScenes.

**Comment by qfwysw** [comment]
![image](https://user-images.githubusercontent.com/53482524/183791403-246dbdbc-7094-4887-8a1b-fc53fac5cbcc.png)
![image](https://user-images.githubusercontent.com/53482524/183791426-9dcae2de-fca2-4de2-ac5e-bd27fb0243cd.png)
Except full dataset，do I have to download the Map expansion? Just like the picture.

**Comment by youchaoqin** [comment]
Which version of the map expansion should we use? Is v1.3 ok?
