### ISSUE TITLE
Address alread used

### ISSUE THREAD

**Issue by qfwysw** [mit-han-lab/bevfusion#95]
If I set the gpu 1, the program can run. However, when I set the num > 1, the code will notes me address already used.
I print the MASTER_HOST, every thread uses the same MASTER_HOST.
So what can I do ?

**Comment by kentang-mit** [comment]
I just want to confirm whether there are other distributed jobs running on your machine, as is mentioned in the previous issue.

**Comment by qfwysw** [comment]
Sorry, I am not sure if there are other distributed programs running, I am running this program on a cluster.

**Comment by kentang-mit** [comment]
You may just use `nvidia-smi` to check out whether there are other jobs running on the machine. It will be better if you can test whether you will still meet with this error when the GPUs are vacant.

**Comment by qfwysw** [comment]
I check it just now, no other program.
![image](https://user-images.githubusercontent.com/53482524/183823994-68d4f1f4-233d-4600-9892-06b34ba57990.png)
![Uploading image.png…]()

**Comment by qfwysw** [comment]
![image](https://user-images.githubusercontent.com/53482524/183827948-e85213d1-ba0c-4553-b3c2-1751740f9c44.png)
I don't know if output like this means my mpirun installation was successful.

**Comment by zhijian-liu** [comment]
You could add `-H localhost:<p>` with different `<p>` to avoid port conflicts.

**Comment by qfwysw** [comment]
Thanks for your help!

**Comment by qfwysw** [comment]
![image](https://user-images.githubusercontent.com/53482524/184277534-cfb8136c-8c3f-451e-85f6-aa6ace4ee13c.png)
![image](https://user-images.githubusercontent.com/53482524/184277642-04b1697c-4973-4c09-b521-e00bb1acb3bf.png)
I set the H, but I get the same error.
If I set the gpu 1, the code works fine.

**Comment by qfwysw** [comment]
I slove the problem. I replaced train.py in the code with train.py of mmdetection3d

**Comment by zhenghw111** [comment]
> 

Hi ！I have encountered the same problem. How do you replace the train.py file? Need to change somewhere? Look forward to your reply

**Comment by zhenghw111** [comment]
> I slove the problem. I replaced train.py in the code with train.py of mmdetection3d

Hello, I have encountered the same problem. How do you replace the train.py file? Need to change somewhere? Look forward to your reply

**Comment by huzhihen** [comment]
> I slove the problem. I replaced train.py in the code with train.py of mmdetection3d

Hello, I have encountered the same problem. Can you tell me how to modify the train.py? Thank you very much!

**Comment by Sranc3** [comment]
> > I slove the problem. I replaced train.py in the code with train.py of mmdetection3d
> 
> Hello, I have encountered the same problem. Can you tell me how to modify the train.py? Thank you very much!

Any suggestions? I met the same problem on  two of my machines, I can only use one GPU for training and testing.

**Comment by REFRAING** [comment]
> I slove the problem. I replaced train.py in the code with train.py of mmdetection3d
Hello, I meet same problem, could you tell me how do you replace the train.py？ Thanks
