### ISSUE TITLE
Some question about the dataset

### ISSUE THREAD

**Issue by qfwysw** [mit-han-lab/bevfusion#97]
I'm so sorry to bother you. I have some difficulties.
I have download the map extention like below. Do I need to generate data according to your code? My original data generation is also before the coordinate system is changed.
![image](https://user-images.githubusercontent.com/53482524/184064384-03dd5573-6950-4c97-937f-f20050dfa643.png)
![image](https://user-images.githubusercontent.com/53482524/184064564-671222db-85b9-46f1-a514-d226f60524f6.png)
![image](https://user-images.githubusercontent.com/53482524/184064602-5d52706c-d87e-4694-b037-c9695b8e26bf.png)
I have no idea to slove this. Could you help me ?

**Comment by kentang-mit** [comment]
Would you mind trying out the data preprocessing pipeline mentioned in the README? Please make sure that all the library versions match our descriptions in the README (especially mmcv and mmdet).

**Comment by qfwysw** [comment]
I have done this, but the error is still here.  I'm not quite sure if the dataset I downloaded is correct. 
![image](https://user-images.githubusercontent.com/53482524/184265772-6079bb86-b134-4620-a968-94540f760e7f.png)
![image](https://user-images.githubusercontent.com/53482524/184265683-960ac0b7-78b1-4986-b551-b15b87f41e02.png)

**Comment by qfwysw** [comment]
Thanks for your help, I slove the problems.
