### ISSUE TITLE
cuda execution failed with error

### ISSUE THREAD

**Issue by qfwysw** [mit-han-lab/bevfusion#98]
The code works fine when I set the gpu <=2. When I set the gpu ==4, the error occurs. What can I do to slove it ?
![image](https://user-images.githubusercontent.com/53482524/184300752-4e406111-b1cf-40e0-894b-74856d3fa849.png)

**Comment by kentang-mit** [comment]
Typically this is an error related to OOM. Please check whether there are other processes running on the GPUs you are using. [Here](https://github.com/mit-han-lab/bevfusion/issues/26) is a solution that can reduce the inference memory. 

By the way, We will release a new version of the codebase that consumes significantly less memory than the current version in the near future.

**Comment by qfwysw** [comment]
I use the A100 48G to inference. But I get the same result.

**Comment by kentang-mit** [comment]
It's better if you can provide more details about your experiments. For example: command used, full error log, the environment (versions of key libraries, type of GPU), etc. I will work on a docker version soon to avoid these problems in the future.

**Comment by qfwysw** [comment]
python -m torch.distributed.launch --nproc_per_node=$GPUS --master_port=$PORT  tools/test——mmdet3d.py $CONFIG --launcher pytorch ${@:3}
![image](https://user-images.githubusercontent.com/53482524/184465143-b73ad057-5335-4f62-bd3a-a8dec09005a2.png)
I just replaced the test.py with the one from mmdet3d. The program works fine when the number of gpus is less than 3. I think it should have nothing to do with the test.py.

**Comment by kentang-mit** [comment]
I think you probably want to try removing lines 22-25 in [this file](https://github.com/mit-han-lab/bevfusion/blob/c53e2283b0ebd00b5adbed8b3de0d39362ad3287/setup.py#L22) and rerun `python setup.py develop`. Our current code is not compiled for P40 by default (should be sm61/compute61).

**Comment by qfwysw** [comment]
Sorry, It's all my fault. I replaced the test.py with the one from mmdet3d.  But it doesn't open the muti tasks. However, adding -H localhost:<p> with different <p> to avoid port conflicts didn't work. 
![image](https://user-images.githubusercontent.com/53482524/184476417-0065d3ac-8d83-420c-8ee2-62b848e12f86.png)

**Comment by qfwysw** [comment]
![image](https://user-images.githubusercontent.com/53482524/184479048-3fc5e96c-d4aa-45ae-9b43-f48de7d462ee.png)
![image](https://user-images.githubusercontent.com/53482524/184479067-2db58a17-c202-4273-acd9-27e5d55a8d15.png)
I print the tcp. From the results, setting the port does not seem to have any effect

**Comment by kentang-mit** [comment]
For the TCP problem, I would suggest you to **open a separate issue** and clearly describe the problem. I remember that in [this issue](https://github.com/mit-han-lab/bevfusion/issues/95) we do have similar discussions and the problem was solved at that time.
