### ISSUE TITLE
Reproduction of the lidar branch

### ISSUE THREAD

**Issue by Zhongdao** [mit-han-lab/bevfusion#99]
Hi, nice work! 

Since the training details are not released yet, I'm here to share some of my progresses, and hopefully, discuss with you guys a bit.
I reproduced the lidar branch and get a number of around 63 mAP on nuscenes val, around 2 points lower than the reported number.
To get this number, I followed the exact [config](https://github.com/XuyangBai/TransFusion/blob/master/configs/transfusion_nusc_voxel_L.py) in TransFusion.  
A bit weird that there is still 2 points lower.

The only difference that I can see is in the "fading strategy" of GT sampling augmentation. In the implementation of TransFusion, the last 5 epoch training starts with lr=1e-4; while in contrast, in this implementation, the first 15 epoch and the last 5 shares a continuous LR schedule.

Anyone has any idea on this?

**Comment by kentang-mit** [comment]
I think your schedule is fine. We did use a continuous LR schedule in our experiments. By the way, probably you can try running the test script separately after training.

**Comment by Zhongdao** [comment]
That's definitely a good point. By separate evaluation, the results look a bit better, but still lower than the expectation. 
I cannot figure out the exact reason by far, so looking forward to the training details!

**Comment by qfwysw** [comment]
> Hi, nice work!
> 
> Since the training details are not released yet, I'm here to share some of my progresses, and hopefully, discuss with you guys a bit. I reproduced the lidar branch and get a number of around 63 mAP on nuscenes val, around 2 points lower than the reported number. To get this number, I followed the exact [config](https://github.com/XuyangBai/TransFusion/blob/master/configs/transfusion_nusc_voxel_L.py) in TransFusion. A bit weird that there is still 2 points lower.
> 
> The only difference that I can see is in the "fading strategy" of GT sampling augmentation. In the implementation of TransFusion, the last 5 epoch training starts with lr=1e-4; while in contrast, in this implementation, the first 15 epoch and the last 5 shares a continuous LR schedule.
> 
> Anyone has any idea on this?

Hi, did you just add trasfution's lr_config in voxelnet_0p075.yaml? I just do like this in convfuser.yaml. However, there are some problems. Have you encountered these problems?
![image](https://user-images.githubusercontent.com/53482524/184623786-bb6b0b1a-0c93-4c4a-8797-c009a2d86ac9.png)

**Comment by Zhongdao** [comment]
Hi @qfwysw 
Besides adding lr_config and momentum config, I find the most important hyparameters to be tuned are the ones for data augmentation. 
Regarding your problem, it seems the cost matrix contains non-numeric element. 
I cannot identify the real reason, but if you check the cost matrix carefully, it should be not difficult to find out.

**Comment by Zhongdao** [comment]
Random scale, rotation, translation, and GT paste.
See Line 30 to Line 76 in https://github.com/XuyangBai/TransFusion/blob/master/configs/transfusion_nusc_voxel_L.py

**Comment by qfwysw** [comment]
Thank you for your generous answer. This helped me a lot!

**Comment by kentang-mit** [comment]
> > Hi, nice work!
> > Since the training details are not released yet, I'm here to share some of my progresses, and hopefully, discuss with you guys a bit. I reproduced the lidar branch and get a number of around 63 mAP on nuscenes val, around 2 points lower than the reported number. To get this number, I followed the exact [config](https://github.com/XuyangBai/TransFusion/blob/master/configs/transfusion_nusc_voxel_L.py) in TransFusion. A bit weird that there is still 2 points lower.
> > The only difference that I can see is in the "fading strategy" of GT sampling augmentation. In the implementation of TransFusion, the last 5 epoch training starts with lr=1e-4; while in contrast, in this implementation, the first 15 epoch and the last 5 shares a continuous LR schedule.
> > Anyone has any idea on this?
> 
> Hi, did you just add trasfution's lr_config in voxelnet_0p075.yaml? I just do like this in convfuser.yaml. However, there are some problems. Have you encountered these problems? ![image](https://user-images.githubusercontent.com/53482524/184623786-bb6b0b1a-0c93-4c4a-8797-c009a2d86ac9.png)

Just to clarify, our finetuning schedule is different from TransFusion. Please stay tuned, we are working on cleanning the training code.

**Comment by qfwysw** [comment]
Thanks for the reminder, it should be the reason of lr config.

**Comment by kentang-mit** [comment]
Temporarily closed due to inactivity.

**Comment by IAMShashankk** [comment]
@Zhongdao Is it possible for you to share your config for training?
